<?php
require_once __DIR__ . '/../db_config.php';
$course = 'wd1';
$track = 'main';

$blocks = [
1=>['ch'=>"Chapter 1: The Developer's World · Day 1 of 14",'min'=>false,'obj'=>["Set up every account and tool you will use this year.","Build a folder structure a real web server can read."],'std'=>["NV 4.2.1 Create a maintainable directory structure for a website","NV 4.2.2 Apply appropriate file naming protocols"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"what do you think a web designer actually spends most of their day doing? Write one sentence. We will come back to this in June.",'tt'=>"Launching the Agency",'tasks'=>["Do Now & Clock In","Syllabus, class website, and Madlearn accounts","The file rules: lowercase, no spaces, hyphens","Lab: Know Your Guild","Exit Ticket"],'et'=>"set up every account and tool you will use this year.",'ms'=>null],
2=>['ch'=>"Chapter 1: The Developer's World · Day 2 of 14",'min'=>false,'obj'=>["Explain the difference between the Internet and the World Wide Web.","Describe who sets the rules for the web and why."],'std'=>["NV 2.1.1 Describe the role of the World Wide Web Consortium (W3C) in defining web standards","NV 2.1.2 Research the history of the World Wide Web","NV 2.1.3 Compare and contrast the Internet and the World Wide Web"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"yesterday you named the file rules. Why would a server care about a capital letter in a filename?",'tt'=>"Internet vs. Web: What You Are Actually Building On",'tasks'=>["Do Now & Clock In","Submarine cable map: the web is physical","Tim Berners-Lee, the W3C, and where standards come from","Lab: The Infrastructure Map","Exit Ticket"],'et'=>"explain the difference between the Internet and the World Wide Web.",'ms'=>null],
3=>['ch'=>"Chapter 1: The Developer's World · Day 3 of 14",'min'=>true,'obj'=>["Define the industry terms and acronyms you will hear all year."],'std'=>["NV 2.3.1 Define common terminology and their acronyms"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"name one thing from last class that is the Internet but is NOT the World Wide Web.",'tt'=>"Speaking the Language of the Trade (45 min)",'tasks'=>["Do Now & Clock In","Vocabulary sprint: 25 terms that show up on every job posting","Exit Ticket"],'et'=>"define the industry terms and acronyms you will hear all year.",'ms'=>null],
4=>['ch'=>"Chapter 1: The Developer's World · Day 4 of 14",'min'=>false,'obj'=>["Differentiate front-end from back-end development.","Explain the roles and careers in this industry."],'std'=>["NV 2.3.2 Differentiate between front-end and back-end development","NV 2.3.3 Explain the various roles and careers related to web design"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"a website has a \"front\" and a \"back.\" What do you think lives in the back that users never see?",'tt'=>"Front-End, Back-End, and Who Gets Paid What",'tasks'=>["Do Now & Clock In","Role teardown: four real job postings, four different jobs","Salary reality check for each pathway","Lab: The Professional Portfolio Audit","Exit Ticket"],'et'=>"differentiate front-end from back-end development.",'ms'=>null],
5=>['ch'=>"Chapter 1: The Developer's World · Day 5 of 14",'min'=>false,'obj'=>["Explain the relationship between a client and a server.","Describe what you are renting when you buy a domain and hosting."],'std'=>["NV 6.1.3 Explain the relationship between client and server"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"last class you picked a career class. Name one task that role does every single day.",'tt'=>"How You Actually Get a Website",'tasks'=>["Do Now & Clock In","Registrar vs. host: two different bills","The client-server request cycle on the board","Lab: Digital Real Estate","Exit Ticket"],'et'=>"explain the relationship between a client and a server.",'ms'=>null],
6=>['ch'=>"Chapter 1: The Developer's World · Day 6 of 14",'min'=>true,'obj'=>["Trace how a domain name becomes a physical server."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Predict','dn'=>"you type a domain into your browser. Before the page loads, what has to happen first?",'tt'=>"DNS: The Internet's Address Book (45 min)",'tasks'=>["Do Now & Clock In","Live ping and nslookup on the projector","Lab: The DNS Trace Log","Exit Ticket"],'et'=>"trace how a domain name becomes a physical server.",'ms'=>null],
7=>['ch'=>"Chapter 1: The Developer's World · Day 7 of 14",'min'=>false,'obj'=>["Break a URL into its parts.","Explain what the padlock does and does not promise."],'std'=>["NV 6.1.3 Explain the relationship between client and server"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"in your own words, what does DNS do? Do not look at your notes.",'tt'=>"URL Anatomy, HTTPS, and Reading a Link Before You Click It",'tasks'=>["Do Now & Clock In","Anatomy of an ugly Amazon URL","Real bank page vs. phishing clone: vote before the reveal","Lab: Secure URL Audit","Exit Ticket"],'et'=>"break a URL into its parts.",'ms'=>null],
8=>['ch'=>"Chapter 1: The Developer's World · Day 8 of 14",'min'=>false,'obj'=>["Create a maintainable directory structure for a website.","Apply professional file naming protocols."],'std'=>["NV 4.2.1 Create a maintainable directory structure for a website","NV 4.2.2 Apply appropriate file naming protocols"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"a server holds a million files. How does it know which one to hand you first?",'tt'=>"File Architecture and the index.html Rule",'tasks'=>["Do Now & Clock In","Rename the homepage, break the site, fix it","IaaS, PaaS, SaaS with the pizza analogy","Lab: Root Setup","Exit Ticket"],'et'=>"create a maintainable directory structure for a website.",'ms'=>null],
9=>['ch'=>"Chapter 1: The Developer's World · Day 9 of 14",'min'=>false,'obj'=>["Name the specific reasons a page reads as professional or amateur."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Reflect','dn'=>"what is the one filename rule you will never break again, and what happens if you do?",'tt'=>"Why Some Sites Look Expensive",'tasks'=>["Do Now & Clock In","The Squint Test on a clean site and a cluttered one","What your eye lands on first, and who decided that","Lab: The Design Teardown","Exit Ticket"],'et'=>"name the specific reasons a page reads as professional or amateur.",'ms'=>null],
10=>['ch'=>"Chapter 1: The Developer's World · Day 10 of 14",'min'=>false,'obj'=>["Define e-commerce as it relates to web development.","Evaluate payment-processing options and their security concerns."],'std'=>["NV 2.5.1 Define e-commerce as it relates to web development","NV 2.5.3 Evaluate payment-processing options","NV 2.5.4 Discuss security concerns as they relate to e-commerce"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"a small shop wants to sell online. Name one thing that could go wrong that has nothing to do with design.",'tt'=>"Getting Paid: E-Commerce, Payments, and Risk",'tasks'=>["Do Now & Clock In","Payment processors compared: fees, speed, and who carries the risk","What a breach actually costs a small business","Lab: The Payment Options Brief","Exit Ticket"],'et'=>"define e-commerce as it relates to web development.",'ms'=>null],
11=>['ch'=>"Chapter 1: The Developer's World · Day 11 of 14",'min'=>true,'obj'=>["Describe what a CTSO is and the requirements to participate.","Explain how federal law created this program."],'std'=>["NV 1.1.1 Discuss the requirements of CTSO participation/involvement as described in Carl D. Perkins Law","NV 1.1.2 Research nationally recognized CTSOs","NV 1.1.3 Investigate the impact of federal and state government regarding the progression and operation of CTSOs (e.g., Federal Statutes and Regulations, Nevada Administrative Code [NAC], Nevada Revised Statutes [NRS])"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"name one e-commerce security risk from last class and one way to reduce it.",'tt'=>"CTSOs and Where This Program Came From (45 min)",'tasks'=>["Do Now & Clock In","SkillsUSA and FBLA competition rules scavenger hunt","The Perkins Act: why this class is funded","Exit Ticket"],'et'=>"describe what a CTSO is and the requirements to participate.",'ms'=>null],
12=>['ch'=>"Chapter 1: The Developer's World · Day 12 of 14",'min'=>false,'obj'=>["Use parliamentary procedure correctly.","Explain offices, committees, and why a chapter has bylaws."],'std'=>["NV 1.2.1 Discuss the purpose of parliamentary procedure","NV 1.2.2 Demonstrate the proper use of parliamentary procedure","NV 1.2.3 Differentiate between an office and a committee","NV 1.2.6 Describe the importance of a constitution and bylaws to the operation of a CTSO chapter"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"what is the single thing that makes a meeting pointless? Write one sentence.",'tt'=>"Running a Meeting That Is Not a Waste of Time",'tasks'=>["Do Now & Clock In","Motion, second, discussion, vote — run it live","Officers vs. committees: who actually decides","Lab: Mock Chapter Meeting","Exit Ticket"],'et'=>"use parliamentary procedure correctly.",'ms'=>null],
13=>['ch'=>"Chapter 1: The Developer's World · Day 13 of 14",'min'=>false,'obj'=>["Explore community-service work-based learning opportunities.","Describe professional workplace attire and why it matters."],'std'=>["NV 1.3.1 Explore opportunities in community service-related work-based learning (WBL)","NV 1.3.3 Engage with business and industry partners for community service","NV 1.4.2 Describe the appropriate professional/workplace attire and its importance","NV 1.4.4 Participate in authentic contextualized instructional activities"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"from the mock meeting, what is one action item you owned and when was it due?",'tt'=>"Community Service, Work-Based Learning, and Looking the Part",'tasks'=>["Do Now & Clock In","Real local organizations that need web work","Dress, email tone, and the first ten seconds","Lab: Community Service Proposal","Exit Ticket"],'et'=>"explore community-service work-based learning opportunities.",'ms'=>null],
14=>['ch'=>"Chapter 1: The Developer's World · Day 14 of 14",'min'=>false,'obj'=>["Connect the program standards to a real career pathway.","Explain what completing this program of study gets you."],'std'=>["NV 1.5.1 Make a connection between program standards to career pathway(s)","NV 1.5.2 Explain the importance of participation and completion of a program of study","NV 1.5.3 Promote community awareness of local student organizations associated with CTE programs"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"what do you think \"CTE Program Completer\" appears on, and who reads it?",'tt'=>"Your Path to Completer Status — Milestone Due",'tasks'=>["Do Now & Clock In","Mapping your two-year path, credential, and assessment","Milestone: The Agency Founder's Blueprint [100 pts]","Founder pitches: 3 minutes each","Exit Ticket"],'et'=>"connect the program standards to a real career pathway.",'ms'=>['title'=>"The Agency Founder's Blueprint",'pts'=>100]],
15=>['ch'=>"Chapter 2: The \"Rules\" · Day 1 of 9",'min'=>false,'obj'=>["Research the laws that govern intellectual property.","Explain how copyright, trademark, and patent differ."],'std'=>["NV 3.1.1 Research laws that govern intellectual property in diverse forms","NV 3.1.4 Explain terms related to copyright, trademarks, patents, and other intellectual property"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"you find the perfect photo on Google Images for a paying client. What is the risk?",'tt'=>"Copyright, Trademarks, and Patents",'tasks'=>["Do Now & Clock In","Real takedown notices and a real settlement figure","Three kinds of protection, three different problems","Exit Ticket"],'et'=>"research the laws that govern intellectual property.",'ms'=>null],
16=>['ch'=>"Chapter 2: The \"Rules\" · Day 2 of 9",'min'=>true,'obj'=>["Evaluate Creative Commons and other free-content licenses.","Cite the boundaries of third-party work."],'std'=>["NV 3.1.2 Evaluate Creative Commons licensing and other free-content license types","NV 3.1.3 Cite the boundaries of third-party work"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"what is the difference between a trademark and a copyright? One sentence, no notes.",'tt'=>"Creative Commons and Where Someone Else's Work Ends (45 min)",'tasks'=>["Do Now & Clock In","Decoding BY, SA, NC, ND, and CC0","Lab: The Asset Integrity Lab","Exit Ticket"],'et'=>"evaluate Creative Commons and other free-content licenses.",'ms'=>null],
17=>['ch'=>"Chapter 2: The \"Rules\" · Day 3 of 9",'min'=>false,'obj'=>["Explain invasion of privacy in the use of technology.","Analyze the implications of a personal digital footprint."],'std'=>["NV 3.2.1 Explain invasion of privacy in the use of technology","NV 3.2.3 Analyze the implications of a personal digital footprint"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"an employer searches your name tonight. What are the first three results?",'tt'=>"Privacy and the Footprint You Are Already Leaving",'tasks'=>["Do Now & Clock In","Live search audit (volunteer only)","What a site can collect without telling you","Exit Ticket"],'et'=>"explain invasion of privacy in the use of technology.",'ms'=>null],
18=>['ch'=>"Chapter 2: The \"Rules\" · Day 4 of 9",'min'=>false,'obj'=>["Differentiate between secure and unsecure web protocols.","Describe how a security certificate protects a website."],'std'=>["NV 3.2.4 Differentiate between secure and unsecure web protocols","NV 3.2.8 Describe how a security certificate protects a website"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"name one thing you found in your own digital footprint that surprised you.",'tt'=>"Secure and Unsecure: What the Padlock Really Means",'tasks'=>["Do Now & Clock In","HTTP vs. HTTPS in the Network panel","Reading a certificate: issuer, expiry, and what it proves","Exit Ticket"],'et'=>"differentiate between secure and unsecure web protocols.",'ms'=>null],
19=>['ch'=>"Chapter 2: The \"Rules\" · Day 5 of 9",'min'=>true,'obj'=>["Model acceptable security practices."],'std'=>["NV 3.2.2 Model acceptable security practices"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"what is the most common way a small business website gets hacked?",'tt'=>"Security Practices You Will Actually Follow (45 min)",'tasks'=>["Do Now & Clock In","Passwords, updates, and least privilege","Exit Ticket"],'et'=>"model acceptable security practices.",'ms'=>null],
20=>['ch'=>"Chapter 2: The \"Rules\" · Day 6 of 9",'min'=>false,'obj'=>["Explain the implications of GDPR.","Explain the implications of the Nevada Consumer Privacy Act."],'std'=>["NV 3.2.5 Explain the implications of General Data Protection Regulations (GDPR)","NV 3.2.6 Explain the implications of Nevada Consumer Privacy Act"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"your client collects names and emails through a form. Name one obligation that creates.",'tt'=>"GDPR, CCPA, and the Nevada Consumer Privacy Act",'tasks'=>["Do Now & Clock In","Three laws, one form: what each one demands","Writing a privacy notice a human can read","Exit Ticket"],'et'=>"explain the implications of GDPR.",'ms'=>null],
21=>['ch'=>"Chapter 2: The \"Rules\" · Day 7 of 9",'min'=>false,'obj'=>["Compare global privacy policies and their cultural impacts.","Describe the purpose of a non-disclosure agreement."],'std'=>["NV 3.2.7 Compare and contrast global privacy policies and cultural impacts","NV 3.3.2 Describe the purpose of a non-disclosure agreement (NDA)"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"why would two countries write completely different privacy laws for the same internet?",'tt'=>"Privacy Around the World, and the NDA You Will Sign",'tasks'=>["Do Now & Clock In","Privacy expectations by region and why they differ","What an NDA actually stops you from saying","Exit Ticket"],'et'=>"compare global privacy policies and their cultural impacts.",'ms'=>null],
22=>['ch'=>"Chapter 2: The \"Rules\" · Day 8 of 9",'min'=>false,'obj'=>["Describe the legal requirements and standards for accessibility.","Identify types of disabilities that affect web design."],'std'=>["NV 4.6.1 Describe regional, national, and international legal requirements and standards for accessibility on the web","NV 4.6.2 Identify types of disabilities that should be considered when designing websites","NV 4.6.5 Research Americans with Disabilities Act (ADA) compliance regulations and policies"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"name one thing an NDA protects that is not code.",'tt'=>"Designing for People You Will Never Meet",'tasks'=>["Do Now & Clock In","Tab-key-only navigation on a real site","ADA, WCAG, and the Domino's case","Lab: The Inclusive Design Proposal","Exit Ticket"],'et'=>"describe the legal requirements and standards for accessibility.",'ms'=>null],
23=>['ch'=>"Chapter 2: The \"Rules\" · Day 9 of 9",'min'=>false,'obj'=>["Model legal and ethical use of information.","Analyze content for bias."],'std'=>["NV 3.3.1 Model legal and ethical use of information","NV 3.3.3 Analyze content for bias"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"name one trick a website has used on you that you noticed but could not name.",'tt'=>"Ethics, Dark Patterns, and Your Own Blind Spots — Milestone Due",'tasks'=>["Do Now & Clock In","Dark patterns: roach motel, confirmshaming, forced continuity","Who your design forgets, and the assumption behind it","Milestone: The Ethics & A11y Audit [100 pts]","Exit Ticket"],'et'=>"model legal and ethical use of information.",'ms'=>['title'=>"The Ethics & A11y Audit",'pts'=>100]],
24=>['ch'=>"Chapter 3: The Blueprint · Day 1 of 12",'min'=>true,'obj'=>["Describe the web design and development cycle."],'std'=>["NV 4.1.1 Describe the web design and development cycle"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"last chapter you audited a site for ethics and accessibility. What would you fix first if it were yours?",'tt'=>"The Design and Development Cycle (45 min)",'tasks'=>["Do Now & Clock In","Analyze, design, develop, implement, evaluate — the loop","Exit Ticket"],'et'=>"describe the web design and development cycle.",'ms'=>null],
25=>['ch'=>"Chapter 3: The Blueprint · Day 2 of 12",'min'=>false,'obj'=>["Demonstrate the web design and development cycle on a live project."],'std'=>["NV 4.1.2 Demonstrate the web design and development cycle (e.g., analyze, design, develop, implement, evaluate)"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"a client says \"just make it look nice.\" What is the first question you ask instead?",'tt'=>"Running the Cycle on a Real Client",'tasks'=>["Do Now & Clock In","Intake meeting: what to ask before you agree to anything","Lab: The Pain Point Audit","Exit Ticket"],'et'=>"demonstrate the web design and development cycle on a live project.",'ms'=>null],
26=>['ch'=>"Chapter 3: The Blueprint · Day 3 of 12",'min'=>false,'obj'=>["Identify target audiences and reading levels for a specific website."],'std'=>["NV 4.4.3 Identify target audiences and reading levels for specific websites"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"name one pain point you found in your interview that you did not expect.",'tt'=>"Who Is This Actually For",'tasks'=>["Do Now & Clock In","Turning interview quotes into a person","Reading level: writing for the audience you actually have","Lab: Meet Your Persona","Exit Ticket"],'et'=>"identify target audiences and reading levels for a specific website.",'ms'=>null],
27=>['ch'=>"Chapter 3: The Blueprint · Day 4 of 12",'min'=>false,'obj'=>["Audit competitors and identify the gap nobody is filling."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Predict','dn'=>"three competitors all do the same thing badly. Threat or opportunity? Why?",'tt'=>"Sizing Up the Competition",'tasks'=>["Do Now & Clock In","SWOT and the competitive feature matrix","Lab: The Blue Ocean Map","Exit Ticket"],'et'=>"audit competitors and identify the gap nobody is filling.",'ms'=>null],
28=>['ch'=>"Chapter 3: The Blueprint · Day 5 of 12",'min'=>false,'obj'=>["Scope a first release and defend what got cut."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Reflect','dn'=>"what gap did you find in the market, and what evidence says it is real?",'tt'=>"Deciding What You Will Not Build",'tasks'=>["Do Now & Clock In","User stories and MoSCoW: four Musts, no more","Lab: The MVP Scope List","Exit Ticket"],'et'=>"scope a first release and defend what got cut.",'ms'=>null],
29=>['ch'=>"Chapter 3: The Blueprint · Day 6 of 12",'min'=>false,'obj'=>["Develop an appropriate navigation system and sitemap."],'std'=>["NV 4.3.2 Develop an appropriate navigation system (site map)"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"how many clicks should it take to reach the most important page on a site?",'tt'=>"Sitemaps and How People Find Things",'tasks'=>["Do Now & Clock In","Card sorting with real content","From sitemap to folder structure to real filenames","Lab: The File Tree Map","Exit Ticket"],'et'=>"develop an appropriate navigation system and sitemap.",'ms'=>null],
30=>['ch'=>"Chapter 3: The Blueprint · Day 7 of 12",'min'=>false,'obj'=>["Develop wireframes for initial responsive design concepts."],'std'=>["NV 4.3.3 Develop wireframes for initial responsive design concepts"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"what surprised you about how someone else grouped your content in the card sort?",'tt'=>"Wireframes: Building in Grayscale First",'tasks'=>["Do Now & Clock In","Six-up sketching: six homepages in six minutes","Why lo-fi protects your schedule","Lab: The Wireframe Blueprint","Exit Ticket"],'et'=>"develop wireframes for initial responsive design concepts.",'ms'=>null],
31=>['ch'=>"Chapter 3: The Blueprint · Day 8 of 12",'min'=>false,'obj'=>["Differentiate voice, tone, and style in web writing.","Determine the primary and secondary purposes of web content."],'std'=>["NV 4.4.1 Discuss and differentiate voice, tone, and style as it applies to web writing","NV 4.4.2 Determine the primary and secondary purposes of web content"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"the same sentence on a bank site and a skate shop site. What has to change?",'tt'=>"Voice, Tone, and What the Page Is Actually For",'tasks'=>["Do Now & Clock In","Rewriting one paragraph in three different voices","Primary purpose vs. the thing you also want","Exit Ticket"],'et'=>"differentiate voice, tone, and style in web writing.",'ms'=>null],
32=>['ch'=>"Chapter 3: The Blueprint · Day 9 of 12",'min'=>false,'obj'=>["Apply grammar and spelling conventions to web content."],'std'=>["NV 4.4.5 Apply grammar and spelling conventions to content"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"name the primary purpose of your project homepage in one sentence.",'tt'=>"Writing That Does Not Embarrass the Client",'tasks'=>["Do Now & Clock In","Editing pass: real client copy, real errors","Scannable writing: chunks, front-loading, and 60 words","Lab: The Copy Edit","Exit Ticket"],'et'=>"apply grammar and spelling conventions to web content.",'ms'=>null],
33=>['ch'=>"Chapter 3: The Blueprint · Day 10 of 12",'min'=>true,'obj'=>["Create a list of keywords and meta descriptions for web content.","Describe best practices that foster indexing and ranking."],'std'=>["NV 4.4.4 Identify and create a list of keywords and descriptions (meta tags) to include in web content for search engine optimization (SEO)","NV 4.4.8 List and describe best practices in content creation that foster indexing and ranking of websites"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"two identical businesses, one on page 1 and one on page 4 of search results. What is that worth?",'tt'=>"Getting Found: Keywords and Meta Tags (45 min)",'tasks'=>["Do Now & Clock In","Title tags, meta descriptions, and honest SEO","Lab: The SEO Plan","Exit Ticket"],'et'=>"create a list of keywords and meta descriptions for web content.",'ms'=>null],
34=>['ch'=>"Chapter 3: The Blueprint · Day 11 of 12",'min'=>false,'obj'=>["Describe the role of social media in web development.","Explain how social platforms, advertising, and websites connect."],'std'=>["NV 2.4.1 Describe the role of social media in web development","NV 2.4.2 Explain the correlation between social media platforms and web links","NV 2.4.3 Describe the relationship of advertising, marketing, social media, and websites","NV 2.4.4 Discuss current trends in social media"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"name one keyword you chose and the evidence that people actually search it.",'tt'=>"Social Media and Where Traffic Comes From",'tasks'=>["Do Now & Clock In","Why every site has share links and what they send back","Current platform trends and how fast they expire","Exit Ticket"],'et'=>"describe the role of social media in web development.",'ms'=>null],
35=>['ch'=>"Chapter 3: The Blueprint · Day 12 of 12",'min'=>false,'obj'=>["Create and implement a strategy that uses social networks to drive traffic to a website."],'std'=>["NV 2.4.5 Create and implement a strategy that uses social networks to drive traffic to a website"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"you post a link and nobody clicks. Name one reason that has nothing to do with the website.",'tt'=>"Driving Real Traffic — Milestone Due",'tasks'=>["Do Now & Clock In","Building a 30-day posting strategy with a measurable goal","Milestone: Project 1 — The Blueprint [100 pts]","Exit Ticket"],'et'=>"create and implement a strategy that uses social networks to drive traffic to a website.",'ms'=>['title'=>"Project 1 — The Blueprint",'pts'=>100]],
36=>['ch'=>"Chapter 4: The Artist · Day 1 of 9",'min'=>true,'obj'=>["Explain and apply the elements of design."],'std'=>["NV 2.2.3 Explain and apply the elements of design"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"your blueprint is done. What is the one decision in it you would defend hardest?",'tt'=>"UI, UX, and the Elements of Design (45 min)",'tasks'=>["Do Now & Clock In","Line, shape, space, texture, value: naming what you already see","Exit Ticket"],'et'=>"explain and apply the elements of design.",'ms'=>null],
37=>['ch'=>"Chapter 4: The Artist · Day 2 of 9",'min'=>false,'obj'=>["Explain and apply the principles of design."],'std'=>["NV 2.2.2 Explain and apply the principles of design"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"a page is beautiful and nobody can find the button. Whose fault is that?",'tt'=>"Principles of Design and What Your Eye Does First",'tasks'=>["Do Now & Clock In","Balance, contrast, emphasis, repetition, hierarchy","Lab: The Hierarchy Audit","Exit Ticket"],'et'=>"explain and apply the principles of design.",'ms'=>null],
38=>['ch'=>"Chapter 4: The Artist · Day 3 of 9",'min'=>false,'obj'=>["Explain and apply color theory."],'std'=>["NV 2.2.1 Explain and apply color theory"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"name the design principle that made your eye land where it did in yesterday's audit.",'tt'=>"Color Theory and Why Banks Are Blue",'tasks'=>["Do Now & Clock In","The wheel, the relationships, and the 60-30-10 rule","Color meaning is cultural: same color, different message","Exit Ticket"],'et'=>"explain and apply color theory.",'ms'=>null],
39=>['ch'=>"Chapter 4: The Artist · Day 4 of 9",'min'=>true,'obj'=>["Evaluate the use of white space."],'std'=>["NV 2.2.5 Evaluate the use of white space"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"what happens to a page when you remove half the content but change nothing else?",'tt'=>"White Space Is Not Wasted Space (45 min)",'tasks'=>["Do Now & Clock In","Before and after: the same page with room to breathe","Exit Ticket"],'et'=>"evaluate the use of white space.",'ms'=>null],
40=>['ch'=>"Chapter 4: The Artist · Day 5 of 9",'min'=>false,'obj'=>["Explain and apply effective typography."],'std'=>["NV 2.2.4 Explain and apply effective typography"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"name one thing white space did for the page that adding content could not.",'tt'=>"Typography: Two Fonts and a Reason",'tasks'=>["Do Now & Clock In","Serif, sans, mono, display — and where each belongs","Type scale, line length, line height","Lab: Brand UI Kit","Exit Ticket"],'et'=>"explain and apply effective typography.",'ms'=>null],
41=>['ch'=>"Chapter 4: The Artist · Day 6 of 9",'min'=>false,'obj'=>["Identify commonly used layout techniques for web design."],'std'=>["NV 4.3.1 Identify commonly used layout techniques for web design"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"why do most shopping carts work the same way? Laziness or strategy?",'tt'=>"Layout Patterns That Already Work",'tasks'=>["Do Now & Clock In","F-pattern, Z-pattern, hero, card grid","Components and the states every button needs","Lab: The Component Lab","Exit Ticket"],'et'=>"identify commonly used layout techniques for web design.",'ms'=>null],
42=>['ch'=>"Chapter 4: The Artist · Day 7 of 9",'min'=>true,'obj'=>["Create a branding message that presents a professional image."],'std'=>["NV 4.4.7 Create a branding message that will present a professional image"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"which layout pattern did you choose, and which did you reject?",'tt'=>"Branding: Sounding Like Someone On Purpose (45 min)",'tasks'=>["Do Now & Clock In","One sentence that says who you are and who you serve","Exit Ticket"],'et'=>"create a branding message that presents a professional image.",'ms'=>null],
43=>['ch'=>"Chapter 4: The Artist · Day 8 of 9",'min'=>false,'obj'=>["Explain website usability procedures."],'std'=>["NV 4.6.4 Explain website usability procedures"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"how many people do you need to test with before you find most of the big problems?",'tt'=>"Prototyping and Watching a Real Person Struggle",'tasks'=>["Do Now & Clock In","Linking screens into a clickable flow","Think-aloud testing: say nothing, write everything down","Lab: The Linked Flow Lab","Exit Ticket"],'et'=>"explain website usability procedures.",'ms'=>null],
44=>['ch'=>"Chapter 4: The Artist · Day 9 of 9",'min'=>false,'obj'=>["Deliver client-ready screens built entirely from your own design system."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Reflect','dn'=>"what did a tester do with your prototype that you never expected?",'tt'=>"High-Fidelity Mockups — Milestone Due",'tasks'=>["Do Now & Clock In","Real content only — no lorem ipsum reaches a client","Developer hand-off: tokens, spacing, exported assets","Milestone: Project 1 Phase 2 — High-Fi Mockup [100 pts]","Exit Ticket"],'et'=>"deliver client-ready screens built entirely from your own design system.",'ms'=>['title'=>"Project 1 Phase 2 — High-Fi Mockup",'pts'=>100]],
45=>['ch'=>"Chapter 5: The \"Bones\" · Day 1 of 13",'min'=>false,'obj'=>["Explain the purpose of HTML in website development."],'std'=>["NV 5.1.1 Explain the purpose of Hypertext Markup Language (HTML) in website development"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"your mockup is beautiful. What has to happen before a browser can show it to anyone?",'tt'=>"What HTML Is and Why It Exists",'tasks'=>["Do Now & Clock In","View Source on a real site: the matrix behind the page","Setting up VS Code and Live Server","Lab: Project 2 Setup","Exit Ticket"],'et'=>"explain the purpose of HTML in website development.",'ms'=>null],
46=>['ch'=>"Chapter 5: The \"Bones\" · Day 2 of 13",'min'=>false,'obj'=>["Differentiate among the versions of HTML.","Code a basic web page with proper document structure."],'std'=>["NV 5.1.2 Differentiate among the different versions of HTML","NV 5.1.4 Code a basic web page utilizing proper HTML document structure in a text editor"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"what is HTML actually responsible for, and what is it NOT responsible for?",'tt'=>"Versions, the Boilerplate, and Your First Real Page",'tasks'=>["Do Now & Clock In","HTML4, XHTML, HTML5: what changed and why you care","Building the boilerplate by hand, line by line","Exit Ticket"],'et'=>"differentiate among the versions of HTML.",'ms'=>null],
47=>['ch'=>"Chapter 5: The \"Bones\" · Day 3 of 13",'min'=>true,'obj'=>["Identify HTML tags for authoring a web page document."],'std'=>["NV 5.1.3 Identify HTML tags for authoring a web page document"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"what happens if you close tags in the wrong order? Does the browser tell you?",'tt'=>"Tags, Nesting, and Attributes (45 min)",'tasks'=>["Do Now & Clock In","First-in, last-out: nesting like parentheses","Exit Ticket"],'et'=>"identify HTML tags for authoring a web page document.",'ms'=>null],
48=>['ch'=>"Chapter 5: The \"Bones\" · Day 4 of 13",'min'=>false,'obj'=>["Use text elements that carry meaning, not just size."],'std'=>["NV 5.1.3 Identify HTML tags for authoring a web page document"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"name one attribute you used yesterday and what it did.",'tt'=>"Headings and Text That Means Something",'tasks'=>["Do Now & Clock In","h1 through h6 as an outline, not a size control","strong and em vs. b and i","Lab: Typography Translation","Exit Ticket"],'et'=>"use text elements that carry meaning, not just size.",'ms'=>null],
49=>['ch'=>"Chapter 5: The \"Bones\" · Day 5 of 13",'min'=>false,'obj'=>["Build ordered, unordered, and description lists correctly."],'std'=>["NV 5.1.3 Identify HTML tags for authoring a web page document"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"why is a navigation menu almost always coded as a list?",'tt'=>"Lists and Why Your Nav Is One",'tasks'=>["Do Now & Clock In","Inspecting a real nav bar to find the hidden ul","Nesting rules: inside the li, not beside it","Lab: Nav List Structure","Exit Ticket"],'et'=>"build ordered, unordered, and description lists correctly.",'ms'=>null],
50=>['ch'=>"Chapter 5: The \"Bones\" · Day 6 of 13",'min'=>false,'obj'=>["Describe correct file paths for relative and absolute links."],'std'=>["NV 4.2.3 Describe the usage of correct file paths for relative and absolute links"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"where does a nested list actually go — inside the li or after it?",'tt'=>"Links and the Paths That Break on Upload",'tasks'=>["Do Now & Clock In","Absolute vs. relative, and what ../ really means","Why a link that works on your laptop 404s on the server","Lab: The Network Link Lab","Exit Ticket"],'et'=>"describe correct file paths for relative and absolute links.",'ms'=>null],
51=>['ch'=>"Chapter 5: The \"Bones\" · Day 7 of 13",'min'=>false,'obj'=>["Identify semantic HTML tags.","Code a page using proper semantic document structure."],'std'=>["NV 5.1.3 Identify HTML tags for authoring a web page document","NV 5.1.4 Code a basic web page utilizing proper HTML document structure in a text editor"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"what does a page built entirely from div tags sound like to a screen reader?",'tt'=>"Semantic Layout: Giving the Page Landmarks",'tasks'=>["Do Now & Clock In","header, nav, main, footer, aside — the Big 5","Div soup vs. semantic markup in the accessibility tree","Lab: The Global Skeleton","Exit Ticket"],'et'=>"identify semantic HTML tags.",'ms'=>null],
52=>['ch'=>"Chapter 5: The \"Bones\" · Day 8 of 13",'min'=>true,'obj'=>["Choose between section, article, aside, and figure with a defensible test."],'std'=>["NV 5.1.3 Identify HTML tags for authoring a web page document"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"why is main better than div class=\"main\"?",'tt'=>"Sectioning and Grouping Content (45 min)",'tasks'=>["Do Now & Clock In","The RSS test: would this make sense on its own?","Lab: Content Blocks","Exit Ticket"],'et'=>"choose between section, article, aside, and figure with a defensible test.",'ms'=>null],
53=>['ch'=>"Chapter 5: The \"Bones\" · Day 9 of 13",'min'=>false,'obj'=>["Optimize web pages to accommodate users with special needs."],'std'=>["NV 4.6.3 Optimize websites to accommodate users with special needs"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"when should an image have EMPTY alt text? There is a correct answer.",'tt'=>"Images and Writing for Someone Who Cannot See Them",'tasks'=>["Do Now & Clock In","Turning images off and reading what is left","The alt text decision tree: decorative, informative, functional","Lab: Image Placeholders","Exit Ticket"],'et'=>"optimize web pages to accommodate users with special needs.",'ms'=>null],
54=>['ch'=>"Chapter 5: The \"Bones\" · Day 10 of 13",'min'=>false,'obj'=>["Build accessible forms with correctly associated labels."],'std'=>["NV 4.6.3 Optimize websites to accommodate users with special needs"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"what alt text belongs on a purely decorative divider image?",'tt'=>"Forms Everyone Can Actually Use",'tasks'=>["Do Now & Clock In","Why a placeholder is not a label","Input types, required, pattern, fieldset and legend","Lab: Full Contact Form","Exit Ticket"],'et'=>"build accessible forms with correctly associated labels.",'ms'=>null],
55=>['ch'=>"Chapter 5: The \"Bones\" · Day 11 of 13",'min'=>true,'obj'=>["Handle encoding and special characters correctly."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Predict','dn'=>"you paste a curly quote from a Word doc into your page. What shows up?",'tt'=>"Character Sets and Why Your Quotes Turn to Garbage (45 min)",'tasks'=>["Do Now & Clock In","UTF-8, entities, and the meta tag that has to come first","Exit Ticket"],'et'=>"handle encoding and special characters correctly.",'ms'=>null],
56=>['ch'=>"Chapter 5: The \"Bones\" · Day 12 of 13",'min'=>false,'obj'=>["Utilize verification tools to verify code."],'std'=>["NV 5.1.5 Utilize verification tools to verify code"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"why can you not just type a < character inside your page text?",'tt'=>"Proving It Works: Validation Tools",'tasks'=>["Do Now & Clock In","Reading a validator message: line, expected, actual","The five errors that cause most failures","Exit Ticket"],'et'=>"utilize verification tools to verify code.",'ms'=>null],
57=>['ch'=>"Chapter 5: The \"Bones\" · Day 13 of 13",'min'=>false,'obj'=>["Utilize verification tools to reach zero validation errors."],'std'=>["NV 5.1.5 Utilize verification tools to verify code"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"how many validation errors do you think your site has right now? Write the number.",'tt'=>"Zero Error Audit — Milestone Due",'tasks'=>["Do Now & Clock In","Validating every page to zero","Peer code review: comment on the code, not the coder","Milestone: The Zero Error Audit [50 pts]","Exit Ticket"],'et'=>"utilize verification tools to reach zero validation errors.",'ms'=>['title'=>"The Zero Error Audit",'pts'=>50]],
58=>['ch'=>"Chapter 6: The \"Clothes\" · Day 1 of 13",'min'=>false,'obj'=>["Describe the role of CSS in relation to web design.","Identify the uses of Cascading Style Sheets."],'std'=>["NV 5.2.1 Describe the role of CSS in relation to web design","NV 4.3.5 Identify the uses of Cascading Style Sheets (CSS)"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"your HTML validates and it is ugly. Whose job is it to fix that?",'tt'=>"What CSS Does and Why It Is Separate",'tasks'=>["Do Now & Clock In","Disabling CSS on a real site: what survives","Lab: The External Sheet","Exit Ticket"],'et'=>"describe the role of CSS in relation to web design.",'ms'=>null],
59=>['ch'=>"Chapter 6: The \"Clothes\" · Day 2 of 13",'min'=>false,'obj'=>["Identify the structure of CSS style rules."],'std'=>["NV 5.2.2 Identify the structure of CSS style rules"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"what are the three parts of a CSS rule? Guess before we name them.",'tt'=>"The Anatomy of a Rule",'tasks'=>["Do Now & Clock In","Selector, property, value — and the semicolon that ruins your day","Comments and why professionals leave them","Exit Ticket"],'et'=>"identify the structure of CSS style rules.",'ms'=>null],
60=>['ch'=>"Chapter 6: The \"Clothes\" · Day 3 of 13",'min'=>false,'obj'=>["Differentiate between internal, external, and inline style sheets."],'std'=>["NV 5.2.4 Differentiate between internal, external, and inline style sheets"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"write one complete CSS rule from memory. No notes.",'tt'=>"Inline, Internal, External: Pick One",'tasks'=>["Do Now & Clock In","The same rule three ways, and which one scales to 40 pages","Lab: The Style Hierarchy","Exit Ticket"],'et'=>"differentiate between internal, external, and inline style sheets.",'ms'=>null],
61=>['ch'=>"Chapter 6: The \"Clothes\" · Day 4 of 13",'min'=>true,'obj'=>["Diagnose style problems in the browser instead of guessing."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Predict','dn'=>"your rule is definitely correct and nothing changed on screen. Name one reason.",'tt'=>"DevTools: Your Fastest Feedback Loop (45 min)",'tasks'=>["Do Now & Clock In","Inspect, Styles, Computed, and the box model diagram","Exit Ticket"],'et'=>"diagnose style problems in the browser instead of guessing.",'ms'=>null],
62=>['ch'=>"Chapter 6: The \"Clothes\" · Day 5 of 13",'min'=>false,'obj'=>["Describe CSS selector types."],'std'=>["NV 5.2.3 Describe CSS selector types"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"which DevTools panel shows the value that actually won?",'tt'=>"Selectors: Aiming at the Right Thing",'tasks'=>["Do Now & Clock In","Tag, class, id, descendant, child, attribute","Naming classes by purpose, not by what they look like","Lab: Structural Targeting","Exit Ticket"],'et'=>"describe CSS selector types.",'ms'=>null],
63=>['ch'=>"Chapter 6: The \"Clothes\" · Day 6 of 13",'min'=>false,'obj'=>["Predict which rule wins a style conflict and explain why."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Predict','dn'=>"two rules target the same element and disagree. How does the browser decide?",'tt'=>"The Cascade, Inheritance, and Who Wins",'tasks'=>["Do Now & Clock In","Specificity math: 100-10-1","Why !important is usually an admission of defeat","Lab: Specificity Audit","Exit Ticket"],'et'=>"predict which rule wins a style conflict and explain why.",'ms'=>null],
64=>['ch'=>"Chapter 6: The \"Clothes\" · Day 7 of 13",'min'=>true,'obj'=>["Use CSS to style webpage content, starting with color."],'std'=>["NV 5.2.5 Use CSS to style webpage content (e.g., typography, web fonts)"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"score .nav a against #main. Show your math.",'tt'=>"Color in Code (45 min)",'tasks'=>["Do Now & Clock In","Hex, RGB, HSL, and why designers think in HSL","Lab: CSS Variables","Exit Ticket"],'et'=>"use CSS to style webpage content, starting with color.",'ms'=>null],
65=>['ch'=>"Chapter 6: The \"Clothes\" · Day 8 of 13",'min'=>false,'obj'=>["Use CSS to style typography and web fonts."],'std'=>["NV 5.2.5 Use CSS to style webpage content (e.g., typography, web fonts)"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"your custom font fails to download on a slow connection. What does the visitor see?",'tt'=>"Web Fonts and What Happens When They Fail",'tasks'=>["Do Now & Clock In","Font stacks, fallbacks, and font-display","The performance cost of loading five weights","Lab: Brand Typography","Exit Ticket"],'et'=>"use CSS to style typography and web fonts.",'ms'=>null],
66=>['ch'=>"Chapter 6: The \"Clothes\" · Day 9 of 13",'min'=>false,'obj'=>["Choose units that respect the user's own browser settings."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Reflect','dn'=>"why does a font stack always end with a generic family?",'tt'=>"Sizing Text for People Who Changed Their Settings",'tasks'=>["Do Now & Clock In","px vs. em vs. rem, and the accessibility reason it matters","Setting the browser to 24px and seeing what breaks","Exit Ticket"],'et'=>"choose units that respect the user's own browser settings.",'ms'=>null],
67=>['ch'=>"Chapter 6: The \"Clothes\" · Day 10 of 13",'min'=>true,'obj'=>["Compute the true rendered size of an element."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Predict','dn'=>"width 300px plus 20px padding. How wide is it on screen? Commit to a number.",'tt'=>"The Box Model and Spacing Math (45 min)",'tasks'=>["Do Now & Clock In","Content, padding, border, margin — and border-box","Lab: Spacing & Breathing","Exit Ticket"],'et'=>"compute the true rendered size of an element.",'ms'=>null],
68=>['ch'=>"Chapter 6: The \"Clothes\" · Day 11 of 13",'min'=>false,'obj'=>["Apply decorative styling that clarifies rather than decorates."],'std'=>["NV 5.2.5 Use CSS to style webpage content (e.g., typography, web fonts)"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"width 200, padding 10, border 5. What is the rendered width by default?",'tt'=>"Borders, Backgrounds, and Restraint",'tasks'=>["Do Now & Clock In","Gradients, radius, and what a shadow should communicate","Lab: Visual Accents","Exit Ticket"],'et'=>"apply decorative styling that clarifies rather than decorates.",'ms'=>null],
69=>['ch'=>"Chapter 6: The \"Clothes\" · Day 12 of 13",'min'=>false,'obj'=>["Utilize online validation tools for CSS."],'std'=>["NV 5.2.7 Utilize online validation tools for CSS"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"why does the same page look slightly different in Chrome and Safari?",'tt'=>"Resets, Normalize, and Checking Your Work",'tasks'=>["Do Now & Clock In","Reset vs. normalize and why it goes first","Reading CSS validator output; typos fail silently","Lab: Browser Reset","Exit Ticket"],'et'=>"utilize online validation tools for CSS.",'ms'=>null],
70=>['ch'=>"Chapter 6: The \"Clothes\" · Day 13 of 13",'min'=>true,'obj'=>["Apply a complete design system across every page of a site."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Reflect','dn'=>"name one duplicated rule you refactored and how many places it fixed.",'tt'=>"Base CSS Integration — Milestone Due (45 min)",'tasks'=>["Do Now & Clock In","Milestone: Project 3 — Base CSS Integration [100 pts]","Exit Ticket"],'et'=>"apply a complete design system across every page of a site.",'ms'=>['title'=>"Project 3 — Base CSS Integration",'pts'=>100]],
71=>['ch'=>"Chapter 7: The \"Style\" · Day 1 of 12",'min'=>true,'obj'=>["Control how elements stack and sit using display types."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Reflect','dn'=>"your site is styled and every element is stacked in one column. Why?",'tt'=>"Document Flow: Bricks and Beads (45 min)",'tasks'=>["Do Now & Clock In","Block, inline, inline-block — and why width does nothing on a span","Lab: Display Fixes","Exit Ticket"],'et'=>"control how elements stack and sit using display types.",'ms'=>null],
72=>['ch'=>"Chapter 7: The \"Style\" · Day 2 of 12",'min'=>false,'obj'=>["Use CSS to lay out webpage content with flexbox."],'std'=>["NV 5.2.6 Use CSS to lay out webpage content (e.g., flexbox, grid, positioning: static, relative, absolute, fixed)"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"before flexbox, centering something vertically was famously hard. Why would that be?",'tt'=>"Flexbox: One Direction at a Time",'tasks'=>["Do Now & Clock In","Container and items: the parent controls the children","flex-direction, and what the main axis actually is","Lab: Flexbox Navigation","Exit Ticket"],'et'=>"use CSS to lay out webpage content with flexbox.",'ms'=>null],
73=>['ch'=>"Chapter 7: The \"Style\" · Day 3 of 12",'min'=>true,'obj'=>["Align, distribute, and wrap content along both axes."],'std'=>["NV 5.2.6 Use CSS to lay out webpage content (e.g., flexbox, grid, positioning: static, relative, absolute, fixed)"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"what does flex-direction column do to the main axis?",'tt'=>"Flexbox Alignment and Wrapping",'tasks'=>["Do Now & Clock In","justify-content vs. align-items","gap, wrap, and flex: 1","Lab: Centering & Wrapping","Exit Ticket"],'et'=>"align, distribute, and wrap content along both axes.",'ms'=>null],
74=>['ch'=>"Chapter 7: The \"Style\" · Day 4 of 12",'min'=>false,'obj'=>["Use CSS to lay out webpage content with grid."],'std'=>["NV 5.2.6 Use CSS to lay out webpage content (e.g., flexbox, grid, positioning: static, relative, absolute, fixed)"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"flexbox handles one direction. What problem does that create for a whole page layout?",'tt'=>"CSS Grid: Two Dimensions at Once",'tasks'=>["Do Now & Clock In","Tracks, fr units, and the grid overlay in DevTools","repeat(auto-fit, minmax()) — responsive with zero media queries","Lab: The Grid Skeleton","Exit Ticket"],'et'=>"use CSS to lay out webpage content with grid.",'ms'=>null],
75=>['ch'=>"Chapter 7: The \"Style\" · Day 5 of 12",'min'=>false,'obj'=>["Build multi-region layouts using named grid areas."],'std'=>["NV 5.2.6 Use CSS to lay out webpage content (e.g., flexbox, grid, positioning: static, relative, absolute, fixed)"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"what does 1fr actually mean? Explain it without using the word \"fraction.\"",'tt'=>"Named Areas and Rearranging Without Touching HTML",'tasks'=>["Do Now & Clock In","grid-template-areas and line-based placement","The accessibility trap: visual order vs. reading order","Lab: The Grid Gallery","Exit Ticket"],'et'=>"build multi-region layouts using named grid areas.",'ms'=>null],
76=>['ch'=>"Chapter 7: The \"Style\" · Day 6 of 12",'min'=>true,'obj'=>["Use positioning: static, relative, absolute, fixed, and sticky."],'std'=>["NV 5.2.6 Use CSS to lay out webpage content (e.g., flexbox, grid, positioning: static, relative, absolute, fixed)"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"an absolutely positioned element with no positioned parent. Where does it go?",'tt'=>"Positioning and Z-Index (45 min)",'tasks'=>["Do Now & Clock In","Sticky headers, pinned badges, and stacking contexts","Lab: The Sticky Header","Exit Ticket"],'et'=>"use positioning: static, relative, absolute, fixed, and sticky.",'ms'=>null],
77=>['ch'=>"Chapter 7: The \"Style\" · Day 7 of 12",'min'=>false,'obj'=>["Develop responsive design for various devices."],'std'=>["NV 4.3.4 Develop responsive design for various devices"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"what is the difference between fixed and sticky?",'tt'=>"Stop Using Pixels",'tasks'=>["Do Now & Clock In","%, em, rem, vw, vh, ch — and when each is correct","max-width in ch and readable line length","Lab: Relative Units","Exit Ticket"],'et'=>"develop responsive design for various devices.",'ms'=>null],
78=>['ch'=>"Chapter 7: The \"Style\" · Day 8 of 12",'min'=>true,'obj'=>["Develop responsive design using media queries."],'std'=>["NV 4.3.4 Develop responsive design for various devices"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"should a breakpoint come from a popular phone size, or from something else?",'tt'=>"Media Queries: Letting Content Set the Breakpoint",'tasks'=>["Do Now & Clock In","Narrowing the browser until it breaks — that is your breakpoint","prefers-reduced-motion and prefers-color-scheme","Lab: Breakpoints","Exit Ticket"],'et'=>"develop responsive design using media queries.",'ms'=>null],
79=>['ch'=>"Chapter 7: The \"Style\" · Day 9 of 12",'min'=>false,'obj'=>["Refactor a stylesheet to mobile-first and cut the override count."],'std'=>["NV 4.3.4 Develop responsive design for various devices"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"name your two breakpoints and the content problem that set each one.",'tt'=>"Mobile-First Refactoring (45 min)",'tasks'=>["Do Now & Clock In","min-width vs. max-width and why one produces less code","Lab: Mobile-First Refactoring","Exit Ticket"],'et'=>"refactor a stylesheet to mobile-first and cut the override count.",'ms'=>null],
80=>['ch'=>"Chapter 7: The \"Style\" · Day 10 of 12",'min'=>false,'obj'=>["Describe the function of a CSS preprocessor."],'std'=>["NV 5.2.8 Describe the function of a CSS preprocessor"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"your stylesheet is 900 lines and you use the same blue in 40 places. What would help?",'tt'=>"Preprocessors: What Sass Is For",'tasks'=>["Do Now & Clock In","Variables, nesting, partials — and what compiles to plain CSS","Exit Ticket"],'et'=>"describe the function of a CSS preprocessor.",'ms'=>null],
81=>['ch'=>"Chapter 7: The \"Style\" · Day 11 of 12",'min'=>true,'obj'=>["Audit a layout across every breakpoint and triage what breaks."],'std'=>["NV 4.3.4 Develop responsive design for various devices"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"name one thing a preprocessor does that plain CSS now does too.",'tt'=>"The Architecture Audit",'tasks'=>["Do Now & Clock In","320, 768, 1440: no horizontal scroll, no orphans","Peer device testing on real hardware","Lab: Cross-Device Triage","Exit Ticket"],'et'=>"audit a layout across every breakpoint and triage what breaks.",'ms'=>null],
82=>['ch'=>"Chapter 7: The \"Style\" · Day 12 of 12",'min'=>true,'obj'=>["Deliver a layout that works from phone to desktop."],'std'=>["NV 5.2.6 Use CSS to lay out webpage content (e.g., flexbox, grid, positioning: static, relative, absolute, fixed)"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"what will break on a device you do not own? Name one thing before you test.",'tt'=>"Project 3 Architecture — Milestone Due (45 min)",'tasks'=>["Do Now & Clock In","Milestone: Project 3 — Architecture [100 pts]","Exit Ticket"],'et'=>"deliver a layout that works from phone to desktop.",'ms'=>['title'=>"Project 3 — Architecture",'pts'=>100]],
83=>['ch'=>"Chapter 8: Sights & Sounds · Day 1 of 9",'min'=>false,'obj'=>["Describe common media file formats."],'std'=>["NV 4.5.1 Describe common media file formats"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"your layout works everywhere. What is still making the page slow?",'tt'=>"Media File Formats and What They Cost (45 min)",'tasks'=>["Do Now & Clock In","JPG, PNG, WebP, SVG, MP4, MP3 — and when each wins","Exit Ticket"],'et'=>"describe common media file formats.",'ms'=>null],
84=>['ch'=>"Chapter 8: Sights & Sounds · Day 2 of 9",'min'=>true,'obj'=>["Identify appropriate software for media creation.","Create and edit media files."],'std'=>["NV 4.5.2 Identify appropriate software for media creation","NV 4.5.3 Create and edit media files (e.g., sound, video, graphics, interactive media, multimedia)"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"a 6 MB phone photo goes on a website. What has to happen to it first?",'tt'=>"The Tools Professionals Actually Use",'tasks'=>["Do Now & Clock In","Photoshop Image Size and Export As; Illustrator to clean SVG","Creating your own assets instead of hunting for them","Exit Ticket"],'et'=>"identify appropriate software for media creation.",'ms'=>null],
85=>['ch'=>"Chapter 8: Sights & Sounds · Day 3 of 9",'min'=>false,'obj'=>["Optimize media files for uploading using compression tools."],'std'=>["NV 4.5.4 Optimize media files for uploading using compression tools"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"name the right format for a logo and the right format for a photograph.",'tt'=>"Compression and the Performance Budget",'tasks'=>["Do Now & Clock In","Lossy vs. lossless, and loading a page on throttled 3G","Lab: Raster Compression","Exit Ticket"],'et'=>"optimize media files for uploading using compression tools.",'ms'=>null],
86=>['ch'=>"Chapter 8: Sights & Sounds · Day 4 of 9",'min'=>true,'obj'=>["Calculate and convert images to desired sizes and resolution."],'std'=>["NV 4.5.6 Calculate and convert images to desired sizes and resolution"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"an image is 1920 by 1080. What is its aspect ratio, and why does that matter?",'tt'=>"Doing the Math on Image Size (45 min)",'tasks'=>["Do Now & Clock In","Ratios, resolution, and object-fit instead of squishing","Lab: Proportions","Exit Ticket"],'et'=>"calculate and convert images to desired sizes and resolution.",'ms'=>null],
87=>['ch'=>"Chapter 8: Sights & Sounds · Day 5 of 9",'min'=>true,'obj'=>["Embed media files in a web design."],'std'=>["NV 4.5.5 Embed media files in a web design"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"your gallery images are all different sizes. What is the amateur fix and what is the real one?",'tt'=>"Putting Media on the Page",'tasks'=>["Do Now & Clock In","figure and figcaption; srcset and picture","Lab: Responsive Imagery","Exit Ticket"],'et'=>"embed media files in a web design.",'ms'=>null],
88=>['ch'=>"Chapter 8: Sights & Sounds · Day 6 of 9",'min'=>true,'obj'=>["Embed accessible video and audio with text alternatives."],'std'=>["NV 4.5.5 Embed media files in a web design"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"who benefits from video captions besides people who are deaf?",'tt'=>"Video and Audio Everyone Can Use (45 min)",'tasks'=>["Do Now & Clock In","WebVTT captions, transcripts, and why autoplay is blocked","Lab: Code Correction (Video & Audio)","Exit Ticket"],'et'=>"embed accessible video and audio with text alternatives.",'ms'=>null],
89=>['ch'=>"Chapter 8: Sights & Sounds · Day 7 of 9",'min'=>false,'obj'=>["Evaluate existing content for web use."],'std'=>["NV 4.4.6 Evaluate existing content for web use (e.g., images, print documents, text, video)"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"name three groups helped by captions besides deaf users.",'tt'=>"Judging Content You Did Not Make",'tasks'=>["Do Now & Clock In","A client hands you a folder of assets. What do you keep?","Licensing, quality, and format triage","Exit Ticket"],'et'=>"evaluate existing content for web use.",'ms'=>null],
90=>['ch'=>"Chapter 8: Sights & Sounds · Day 8 of 9",'min'=>true,'obj'=>["Build semantic data tables and embed third-party content responsibly."],'std'=>["NV 4.5.5 Embed media files in a web design"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"what is the difference between using a table for data and using one for layout?",'tt'=>"Tables, Embeds, and the Accessibility Pass",'tasks'=>["Do Now & Clock In","caption, thead, th scope — what a screen reader hears","iframes: title, lazy loading, and the privacy cost","Lab: Semantic Data Tables","Exit Ticket"],'et'=>"build semantic data tables and embed third-party content responsibly.",'ms'=>null],
91=>['ch'=>"Chapter 8: Sights & Sounds · Day 9 of 9",'min'=>false,'obj'=>["Participate in a service-learning or community project.","Deliver an optimized, accessible media build."],'std'=>["NV 1.3.2 Participate in a service learning (program related) and/or community service project or activity"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"what is your heaviest page right now, and what is on it?",'tt'=>"Media Integration — Milestone Due",'tasks'=>["Do Now & Clock In","Broken link hunt and the final Lighthouse pass","Community project check-in: who are you actually helping?","Milestone: Project 3 — Media Integration [100 pts]","Exit Ticket"],'et'=>"participate in a service-learning or community project.",'ms'=>['title'=>"Project 3 — Media Integration",'pts'=>100]],
92=>['ch'=>"Chapter 9: The \"Brains\" · Day 1 of 8",'min'=>true,'obj'=>["Compare and contrast static versus dynamic websites."],'std'=>["NV 5.3.5 Compare and contrast static versus dynamic websites"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"your site looks finished. Name one thing it still cannot do for a visitor.",'tt'=>"Static vs. Dynamic: Poster or Robot (45 min)",'tasks'=>["Do Now & Clock In","A poster says the same thing to everyone. A robot responds.","Exit Ticket"],'et'=>"compare and contrast static versus dynamic websites.",'ms'=>null],
93=>['ch'=>"Chapter 9: The \"Brains\" · Day 2 of 8",'min'=>true,'obj'=>["Explain the use of current web scripting technologies."],'std'=>["NV 5.3.1 Explain the use of current web scripting technologies"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"if HTML is the noun and CSS is the adjective, what is JavaScript?",'tt'=>"Current Scripting Technologies and Where They Run",'tasks'=>["Do Now & Clock In","Opening the console and changing a live page","Where the script tag goes and why it matters","Lab: The Console Lab","Exit Ticket"],'et'=>"explain the use of current web scripting technologies.",'ms'=>null],
94=>['ch'=>"Chapter 9: The \"Brains\" · Day 3 of 8",'min'=>false,'obj'=>["Compare and contrast client scripting and server scripting."],'std'=>["NV 5.3.3 Compare and contrast client (browser) scripting and server scripting (e.g., PHP, JavaScript)"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"name one thing on a real site that could not work without JavaScript.",'tt'=>"Client-Side vs. Server-Side",'tasks'=>["Do Now & Clock In","Who you can trust: the browser belongs to the user","Why a price is never validated only on the client","Exit Ticket"],'et'=>"compare and contrast client scripting and server scripting.",'ms'=>null],
95=>['ch'=>"Chapter 9: The \"Brains\" · Day 4 of 8",'min'=>false,'obj'=>["Store and compare data correctly in a script."],'std'=>["NV 5.3.2 Implement scripting (e.g., rollovers, form scripts)"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"what does \"5\" + 5 give you? What about \"5\" - 5? Commit to both answers.",'tt'=>"Variables, Types, and the Rules of Equality",'tasks'=>["Do Now & Clock In","let, const, and why var is gone","== vs. === and the falsy values that bite","Lab: The Data Vault Lab","Exit Ticket"],'et'=>"store and compare data correctly in a script.",'ms'=>null],
96=>['ch'=>"Chapter 9: The \"Brains\" · Day 5 of 8",'min'=>false,'obj'=>["Implement reusable scripted logic."],'std'=>["NV 5.3.2 Implement scripting (e.g., rollovers, form scripts)"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"why do professionals use === instead of ==?",'tt'=>"Functions: Writing It Once (45 min)",'tasks'=>["Do Now & Clock In","Parameters, arguments, return, and scope","Lab: Reusable UI Functions","Exit Ticket"],'et'=>"implement reusable scripted logic.",'ms'=>null],
97=>['ch'=>"Chapter 9: The \"Brains\" · Day 6 of 8",'min'=>false,'obj'=>["Implement conditional logic that handles every case."],'std'=>["NV 5.3.2 Implement scripting (e.g., rollovers, form scripts)"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"a form accepts a negative age. Where should that have been caught?",'tt'=>"Making Decisions in Code",'tasks'=>["Do Now & Clock In","if, else if, switch, and the ternary","The three cases: happy path, empty, invalid","Lab: Decision Engine Lab","Exit Ticket"],'et'=>"implement conditional logic that handles every case.",'ms'=>null],
98=>['ch'=>"Chapter 9: The \"Brains\" · Day 7 of 8",'min'=>false,'obj'=>["Implement scripting such as rollovers and form scripts."],'std'=>["NV 5.3.2 Implement scripting (e.g., rollovers, form scripts)"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"name the three cases every conditional should cover.",'tt'=>"Events: Making the Page Respond",'tasks'=>["Do Now & Clock In","querySelector, textContent, addEventListener","Why a real button beats a clickable div","Lab: The Interactive Wire Lab","Exit Ticket"],'et'=>"implement scripting such as rollovers and form scripts.",'ms'=>null],
99=>['ch'=>"Chapter 9: The \"Brains\" · Day 8 of 8",'min'=>false,'obj'=>["Deliver a working interactive feature and hand off the year's portfolio."],'std'=>["NV 5.3.2 Implement scripting (e.g., rollovers, form scripts)"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"one year from now, what is the first thing you will have forgotten? Write it down.",'tt'=>"Year 1 Hand-Off — Final Milestone",'tasks'=>["Do Now & Clock In","Milestone: The Profile App [100 pts]","Year 1 portfolio walkthrough: 3 minutes each","Year 1 reflection and one goal for Level 2","Exit Ticket"],'et'=>"deliver a working interactive feature and hand off the year's portfolio.",'ms'=>['title'=>"The Profile App",'pts'=>100]],
];

$dates = [
1=>'2026-08-18',2=>'2026-08-20',3=>'2026-08-24',4=>'2026-08-25',5=>'2026-08-27',6=>'2026-08-31',7=>'2026-09-01',8=>'2026-09-03',9=>'2026-09-08',10=>'2026-09-10',
11=>'2026-09-14',12=>'2026-09-15',13=>'2026-09-17',14=>'2026-09-22',15=>'2026-09-24',16=>'2026-09-28',17=>'2026-09-29',18=>'2026-10-01',19=>'2026-10-05',20=>'2026-10-06',
21=>'2026-10-08',22=>'2026-10-13',23=>'2026-10-15',24=>'2026-10-19',25=>'2026-10-20',26=>'2026-10-22',27=>'2026-10-27',28=>'2026-10-29',29=>'2026-11-03',30=>'2026-11-05',
31=>'2026-11-10',32=>'2026-11-12',33=>'2026-11-16',34=>'2026-11-17',35=>'2026-11-19',36=>'2026-11-30',37=>'2026-12-01',38=>'2026-12-03',39=>'2026-12-07',40=>'2026-12-08',
41=>'2026-12-10',42=>'2026-12-14',43=>'2026-12-15',44=>'2026-12-17',45=>'2027-01-05',46=>'2027-01-07',47=>'2027-01-11',48=>'2027-01-12',49=>'2027-01-14',50=>'2027-01-19',
51=>'2027-01-21',52=>'2027-01-25',53=>'2027-01-26',54=>'2027-01-28',55=>'2027-02-01',56=>'2027-02-02',57=>'2027-02-04',58=>'2027-02-09',59=>'2027-02-16',60=>'2027-02-18',
61=>'2027-02-22',62=>'2027-02-23',63=>'2027-02-25',64=>'2027-03-01',65=>'2027-03-02',66=>'2027-03-04',67=>'2027-03-08',68=>'2027-03-09',69=>'2027-03-11',70=>'2027-03-15',
71=>'2027-03-16',72=>'2027-03-18',73=>'2027-03-22',74=>'2027-03-23',75=>'2027-03-25',76=>'2027-04-06',77=>'2027-04-08',78=>'2027-04-12',79=>'2027-04-13',80=>'2027-04-15',
81=>'2027-04-19',82=>'2027-04-20',83=>'2027-04-22',84=>'2027-04-26',85=>'2027-04-27',86=>'2027-04-29',87=>'2027-05-03',88=>'2027-05-04',89=>'2027-05-06',90=>'2027-05-10',
91=>'2027-05-11',92=>'2027-05-13',93=>'2027-05-17',94=>'2027-05-18',95=>'2027-05-20',96=>'2027-05-25',97=>'2027-05-27',98=>'2027-06-01',99=>'2027-06-03',
];

$db = getDB();
$db->query("CREATE TABLE IF NOT EXISTS agenda_content (course VARCHAR(20) NOT NULL, block_num INT NOT NULL, content LONGTEXT NOT NULL, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (course, block_num)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$db->query("CREATE TABLE IF NOT EXISTS agenda_schedule (course VARCHAR(20) NOT NULL, track VARCHAR(10) NOT NULL DEFAULT 'main', block_num INT NOT NULL, event_date DATE NOT NULL, PRIMARY KEY (course, track, block_num), KEY idx_lookup (course, track, event_date)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

$stmtC = $db->prepare("INSERT INTO agenda_content (course, block_num, content) VALUES (?,?,?) ON DUPLICATE KEY UPDATE content=VALUES(content)");
foreach ($blocks as $num => $b) {
    $content = ['chapterLabel'=>$b['ch'],'minimumDay'=>$b['min'],'objective'=>$b['obj'],'standards'=>$b['std'],'standardsNote'=>$b['stdNote'],'doNowType'=>$b['dnType'],'doNowPrompt'=>$b['dn'],'tasksTitle'=>$b['tt'],'tasksList'=>$b['tasks'],'exitTicket'=>$b['et'],'milestone'=>$b['ms']];
    $json = json_encode($content);
    $stmtC->bind_param('sis', $course, $num, $json);
    $stmtC->execute();
}
$stmtC->close();

$stmtS = $db->prepare("INSERT INTO agenda_schedule (course, track, block_num, event_date) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE event_date=VALUES(event_date)");
foreach ($dates as $num => $date) {
    $stmtS->bind_param('ssis', $course, $track, $num, $date);
    $stmtS->execute();
}
$stmtS->close();
$db->close();
echo "Seeded $course: " . count($blocks) . " content rows, " . count($dates) . " schedule rows\n";
