<?php
require_once __DIR__ . '/../db_config.php';
$course = 'wd1';
$track = 'main';

$blocks = [
1=>['ch'=>"Chapter 1: The Developer's World · Day 1 of 14",'min'=>false,'obj'=>["Set up every account and tool you will use this year.","Build a folder structure a real web server can read."],'std'=>["NV 4.2.1 Create a maintainable directory structure for a website","NV 4.2.2 Apply appropriate file naming protocols"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"what do you think a web designer actually spends most of their day doing? Write one sentence. We will come back to this in June.",'tt'=>"Launching the Agency",'tasks'=>["Do Now & Clock In","Syllabus, class website, and Madlearn accounts","The file rules: lowercase, no spaces, hyphens","Lab: Know Your Guild","Exit Ticket"],'et'=>"set up every account and tool you will use this year.",'ms'=>null],
2=>['ch'=>"Chapter 1: The Developer's World · Day 2 of 14",'min'=>false,'obj'=>["Explain the difference between the Internet and the World Wide Web.","Describe who sets the rules for the web and why."],'std'=>["NV 2.1.1 Describe the role of the World Wide Web Consortium (W3C) in defining web standards","NV 2.1.2 Research the history of the World Wide Web","NV 2.1.3 Compare and contrast the Internet and the World Wide Web"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"yesterday you named the file rules. Why would a server care about a capital letter in a filename?",'tt'=>"Internet vs. Web: What You Are Actually Building On",'tasks'=>["Do Now & Clock In","Submarine cable map: the web is physical","Tim Berners-Lee, the W3C, and where standards come from","Lab: The Infrastructure Map","Exit Ticket"],'et'=>"explain the difference between the Internet and the World Wide Web.",'ms'=>null],
3=>['ch'=>"Chapter 1: The Developer's World · Day 3 of 14",'min'=>true,'obj'=>["Define the industry terms and acronyms you will hear all year."],'std'=>["NV 2.3.1 Define common terminology and their acronyms"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"name one thing from last class that is the Internet but is NOT the World Wide Web.",'tt'=>"Speaking the Language of the Trade (45 min)",'tasks'=>["Do Now & Clock In","Vocabulary sprint: 25 terms that show up on every job posting","Exit Ticket"],'et'=>"define the industry terms and acronyms you will hear all year.",'ms'=>null],
4=>['ch'=>"Chapter 1: The Developer's World · Day 4 of 14",'min'=>false,'obj'=>["Differentiate front-end from back-end development.","Explain the roles and careers in this industry."],'std'=>["NV 2.3.2 Differentiate between front-end and back-end development","NV 2.3.3 Explain the various roles and careers related to web design"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"a website has a \"front\" and a \"back.\" What do you think lives in the back that users never see?",'tt'=>"Front-End, Back-End, and Who Gets Paid What",'tasks'=>["Do Now & Clock In","Role teardown: four real job postings, four different jobs","Salary reality check for each pathway","Lab: The Professional Portfolio Audit","Exit Ticket"],'et'=>"differentiate front-end from back-end development.",'ms'=>null],
5=>['ch'=>"Chapter 1: The Developer's World · Day 5 of 14",'min'=>false,'obj'=>["Explain the relationship between a client and a server.","Describe what you are renting when you buy a domain and hosting."],'std'=>["NV 6.1.3 Explain the relationship between client and server"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"last class you picked a career class. Name one task that role does every single day.",'tt'=>"How You Actually Get a Website",'tasks'=>["Do Now & Clock In","Registrar vs. host: two different bills","The client-server request cycle on the board","Lab: Digital Real Estate","Exit Ticket"],'et'=>"explain the relationship between a client and a server.",'ms'=>null],
6=>['ch'=>"Chapter 1: The Developer's World · Day 6 of 14",'min'=>true,'obj'=>["Trace how a domain name becomes a physical server."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Predict','dn'=>"you type a domain into your browser. Before the page loads, what has to happen first?",'tt'=>"DNS: The Internet's Address Book (45 min)",'tasks'=>["Do Now & Clock In","Live ping and nslookup on the projector","Lab: The DNS Trace Log","Exit Ticket"],'et'=>"trace how a domain name becomes a physical server.",'ms'=>null],
7=>['ch'=>"Chapter 1: The Developer's World · Day 7 of 14",'min'=>false,'obj'=>["Break a URL into its parts.","Explain what the padlock does and does not promise."],'std'=>["NV 6.1.3 Explain the relationship between client and server"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"in your own words, what does DNS do? Do not look at your notes.",'tt'=>"URL Anatomy, HTTPS, and Reading a Link Before You Click It",'tasks'=>["Do Now & Clock In","Anatomy of an ugly Amazon URL","Real bank page vs. phishing clone: vote before the reveal","Lab: Secure URL Audit","Exit Ticket"],'et'=>"break a URL into its parts.",'ms'=>null],
8=>['ch'=>"Chapter 1: The Developer's World · Day 8 of 14",'min'=>false,'obj'=>["Create a maintainable directory structure for a website.","Apply professional file naming protocols."],'std'=>["NV 4.2.1 Create a maintainable directory structure for a website","NV 4.2.2 Apply appropriate file naming protocols"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"a server holds a million files. How does it know which one to hand you first?",'tt'=>"File Architecture and the index.html Rule",'tasks'=>["Do Now & Clock In","Rename the homepage, break the site, fix it","IaaS, PaaS, SaaS with the pizza analogy","Lab: Root Setup","Exit Ticket"],'et'=>"create a maintainable directory structure for a website.",'ms'=>null],
9=>['ch'=>"Chapter 1: The Developer's World · Day 9 of 14",'min'=>false,'obj'=>["Name the specific reasons a page reads as professional or amateur."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Reflect','dn'=>"what is the one filename rule you will never break again, and what happens if you do?",'tt'=>"Why Some Sites Look Expensive",'tasks'=>["Do Now & Clock In","The Squint Test on a clean site and a cluttered one","What your eye lands on first, and who decided that","Lab: The Design Teardown","Exit Ticket"],'et'=>"name the specific reasons a page reads as professional or amateur.",'ms'=>null],
10=>['ch'=>"Chapter 1: The Developer's World · Day 10 of 14",'min'=>false,'obj'=>["Define e-commerce as it relates to web development.","Evaluate payment-processing options and their security concerns."],'std'=>["NV 2.5.1 Define e-commerce as it relates to web development","NV 2.5.3 Evaluate payment-processing options","NV 2.5.4 Discuss security concerns as they relate to e-commerce"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"a small shop wants to sell online. Name one thing that could go wrong that has nothing to do with design.",'tt'=>"Getting Paid: E-Commerce, Payments, and Risk",'tasks'=>["Do Now & Clock In","Payment processors compared: fees, speed, and who carries the risk","What a breach actually costs a small business","Lab: The Payment Options Brief","Exit Ticket"],'et'=>"define e-commerce as it relates to web development.",'ms'=>null],
11=>['ch'=>"Chapter 1: The Developer's World · Day 11 of 14",'min'=>true,'obj'=>["Describe what a CTSO is and the requirements to participate.","Explain how federal law created this program."],'std'=>["NV 1.1.1 Discuss the requirements of CTSO participation/involvement as described in Carl D. Perkins Law","NV 1.1.2 Research nationally recognized CTSOs","NV 1.1.3 Investigate the impact of federal and state government regarding the progression and operation of CTSOs (e.g., Federal Statutes and Regulations, Nevada Administrative Code [NAC], Nevada Revised Statutes [NRS])"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"name one e-commerce security risk from last class and one way to reduce it.",'tt'=>"CTSOs and Where This Program Came From (45 min)",'tasks'=>["Do Now & Clock In","SkillsUSA and FBLA competition rules scavenger hunt","The Perkins Act: why this class is funded","Exit Ticket"],'et'=>"describe what a CTSO is and the requirements to participate.",'ms'=>null],
12=>['ch'=>"Chapter 1: The Developer's World · Day 12 of 14",'min'=>false,'obj'=>["Use parliamentary procedure correctly.","Explain offices, committees, and why a chapter has bylaws."],'std'=>["NV 1.2.1 Discuss the purpose of parliamentary procedure","NV 1.2.2 Demonstrate the proper use of parliamentary procedure","NV 1.2.3 Differentiate between an office and a committee","NV 1.2.6 Describe the importance of a constitution and bylaws to the operation of a CTSO chapter"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"what is the single thing that makes a meeting pointless? Write one sentence.",'tt'=>"Running a Meeting That Is Not a Waste of Time",'tasks'=>["Do Now & Clock In","Motion, second, discussion, vote — run it live","Officers vs. committees: who actually decides","Lab: Mock Chapter Meeting","Exit Ticket"],'et'=>"use parliamentary procedure correctly.",'ms'=>null],
13=>['ch'=>"Chapter 1: The Developer's World · Day 13 of 14",'min'=>false,'obj'=>["Explore community-service work-based learning opportunities.","Describe professional workplace attire and why it matters."],'std'=>["NV 1.3.1 Explore opportunities in community service-related work-based learning (WBL)","NV 1.3.3 Engage with business and industry partners for community service","NV 1.4.2 Describe the appropriate professional/workplace attire and its importance","NV 1.4.4 Participate in authentic contextualized instructional activities"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"from the mock meeting, what is one action item you owned and when was it due?",'tt'=>"Community Service, Work-Based Learning, and Looking the Part",'tasks'=>["Do Now & Clock In","Real local organizations that need web work","Dress, email tone, and the first ten seconds","Lab: Community Service Proposal","Exit Ticket"],'et'=>"explore community-service work-based learning opportunities.",'ms'=>null],
14=>['ch'=>"Chapter 1: The Developer's World · Day 14 of 14",'min'=>false,'obj'=>["Connect the program standards to a real career pathway.","Explain what completing this program of study gets you."],'std'=>["NV 1.5.1 Make a connection between program standards to career pathway(s)","NV 1.5.2 Explain the importance of participation and completion of a program of study","NV 1.5.3 Promote community awareness of local student organizations associated with CTE programs"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"what do you think \"CTE Program Completer\" appears on, and who reads it?",'tt'=>"Your Path to Completer Status — Milestone Due",'tasks'=>["Do Now & Clock In","Mapping your two-year path, credential, and assessment","Milestone: The Agency Founder's Blueprint [100 pts]","Founder pitches: 3 minutes each","Exit Ticket"],'et'=>"connect the program standards to a real career pathway.",'ms'=>['title'=>"The Agency Founder's Blueprint",'pts'=>100]],
15=>['ch'=>"Chapter 2: The \"Rules\" · Day 1 of 4",'min'=>false,'obj'=>["Research the laws that govern intellectual property.","Explain how copyright, trademarks, and patents differ.","Evaluate Creative Commons and other free-content licenses."],'std'=>["NV 3.1.1 Research laws that govern intellectual property in diverse forms","NV 3.1.2 Evaluate Creative Commons licensing and other free-content license types","NV 3.1.3 Cite the boundaries of third-party work","NV 3.1.4 Explain terms related to copyright, trademarks, patents, and other intellectual property"],'stdNote'=>null,'dnType'=>"Predict",'dn'=>"you find the perfect photo on Google Images for a paying client. What is the risk?",'tt'=>"Copyright, Creative Commons, and What You're Actually Allowed to Use",'tasks'=>["Do Now & Clock In","Real takedown notices and a real settlement figure","Decoding BY, SA, NC, ND, and CC0","Lab: The Asset Integrity Lab","Exit Ticket"],'et'=>"explain how copyright, trademarks, and Creative Commons licensing differ.",'ms'=>null],
16=>['ch'=>"Chapter 2: The \"Rules\" · Day 2 of 4",'min'=>true,'obj'=>["Explain invasion of privacy in the use of technology.","Analyze the implications of a personal digital footprint.","Differentiate between secure and unsecure web protocols.","Model acceptable security practices."],'std'=>["NV 3.2.1 Explain invasion of privacy in the use of technology","NV 3.2.2 Model acceptable security practices","NV 3.2.3 Analyze the implications of a personal digital footprint","NV 3.2.4 Differentiate between secure and unsecure web protocols","NV 3.2.8 Describe how a security certificate protects a website"],'stdNote'=>null,'dnType'=>"Reflect",'dn'=>"an employer searches your name tonight. What are the first three results?",'tt'=>"Privacy, the Padlock, and Practices You'll Actually Follow (45 min)",'tasks'=>["Do Now & Clock In","Live search audit (volunteer only) and what a site can collect without telling you","HTTP vs. HTTPS in the Network panel; passwords, updates, least privilege","Exit Ticket"],'et'=>"differentiate between secure and unsecure web protocols and model acceptable security practices.",'ms'=>null],
17=>['ch'=>"Chapter 2: The \"Rules\" · Day 3 of 4",'min'=>false,'obj'=>["Explain the implications of GDPR and the Nevada Consumer Privacy Act.","Compare global privacy policies and their cultural impacts.","Describe the purpose of a non-disclosure agreement."],'std'=>["NV 3.2.5 Explain the implications of General Data Protection Regulations (GDPR)","NV 3.2.6 Explain the implications of Nevada Consumer Privacy Act","NV 3.2.7 Compare and contrast global privacy policies and cultural impacts","NV 3.3.2 Describe the purpose of a non-disclosure agreement (NDA)"],'stdNote'=>null,'dnType'=>"Predict",'dn'=>"your client collects names and emails through a form. Name one obligation that creates.",'tt'=>"GDPR, CCPA, and the NDA You Will Sign",'tasks'=>["Do Now & Clock In","Three laws, one form: what each one demands","Writing a privacy notice a human can read; what an NDA actually stops you from saying","Exit Ticket"],'et'=>"explain the implications of GDPR and the Nevada Consumer Privacy Act.",'ms'=>null],
18=>['ch'=>"Chapter 2: The \"Rules\" · Day 4 of 4",'min'=>false,'obj'=>["Describe the legal requirements and standards for accessibility.","Identify types of disabilities that affect web design.","Model legal and ethical use of information.","Analyze content for bias."],'std'=>["NV 4.6.1 Describe regional, national, and international legal requirements and standards for accessibility on the web","NV 4.6.2 Identify types of disabilities that should be considered when designing websites","NV 4.6.5 Research Americans with Disabilities Act (ADA) compliance regulations and policies","NV 3.3.1 Model legal and ethical use of information","NV 3.3.3 Analyze content for bias"],'stdNote'=>null,'dnType'=>"Reflect",'dn'=>"name one trick a website has used on you that you noticed but could not name.",'tt'=>"Designing for People You Will Never Meet — Project Due",'tasks'=>["Do Now & Clock In","Tab-key-only navigation on a real site; ADA, WCAG, and the Domino's case","Lab: The Inclusive Design Proposal","Dark patterns: roach motel, confirmshaming, forced continuity","Project: Ethics & A11y Audit [100 pts]","Exit Ticket"],'et'=>"describe the legal requirements and standards for accessibility.",'ms'=>['title'=>"Ethics & A11y Audit",'pts'=>100]],
19=>['ch'=>"Chapter 3: The Blueprint · Day 1 of 8",'min'=>true,'obj'=>["Describe the web design and development cycle.","Demonstrate the cycle on a live project."],'std'=>["NV 4.1.1 Describe the web design and development cycle","NV 4.1.2 Demonstrate the web design and development cycle (e.g., analyze, design, develop, implement, evaluate)"],'stdNote'=>null,'dnType'=>"Reflect",'dn'=>"last chapter you audited a site for ethics and accessibility. What would you fix first if it were yours?",'tt'=>"The Design Cycle and Running It on a Real Client (45 min)",'tasks'=>["Do Now & Clock In","Analyze, design, develop, implement, evaluate — the loop","Intake meeting: what to ask before you agree to anything","Exit Ticket"],'et'=>"describe the web design and development cycle.",'ms'=>null],
20=>['ch'=>"Chapter 3: The Blueprint · Day 2 of 8",'min'=>false,'obj'=>["Identify target audiences and reading levels for a specific website."],'std'=>["NV 4.4.3 Identify target audiences and reading levels for specific websites"],'stdNote'=>null,'dnType'=>"Predict",'dn'=>"a client says \"just make it look nice.\" What is the first question you ask instead?",'tt'=>"Who Is This Actually For",'tasks'=>["Do Now & Clock In","Turning interview quotes into a person","Reading level: writing for the audience you actually have","Lab: The Pain Point Audit","Exit Ticket"],'et'=>"identify target audiences and reading levels for a specific website.",'ms'=>null],
21=>['ch'=>"Chapter 3: The Blueprint · Day 3 of 8",'min'=>false,'obj'=>["Build a persona from real research, not guesses."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>"Reflect",'dn'=>"name one pain point you found in your interview that you did not expect.",'tt'=>"Meet Your Persona",'tasks'=>["Do Now & Clock In","Turning interview quotes into a person's goals and frustrations","Lab: Meet Your Persona","Exit Ticket"],'et'=>"build a persona from real research, not guesses.",'ms'=>null],
22=>['ch'=>"Chapter 3: The Blueprint · Day 4 of 8",'min'=>false,'obj'=>["Audit competitors and identify the gap nobody is filling.","Scope a first release and defend what got cut."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>"Predict",'dn'=>"three competitors all do the same thing badly. Threat or opportunity? Why?",'tt'=>"Sizing Up the Competition and Deciding What You Won't Build",'tasks'=>["Do Now & Clock In","SWOT and the competitive feature matrix","Lab: The Blue Ocean Map","User stories and MoSCoW: four Musts, no more","Exit Ticket"],'et'=>"audit competitors and scope a first release.",'ms'=>null],
23=>['ch'=>"Chapter 3: The Blueprint · Day 5 of 8",'min'=>true,'obj'=>["Develop an appropriate navigation system and sitemap."],'std'=>["NV 4.3.2 Develop an appropriate navigation system (site map)"],'stdNote'=>null,'dnType'=>"Reflect",'dn'=>"what gap did you find in the market, and what evidence says it is real?",'tt'=>"Sitemaps and How People Find Things (45 min)",'tasks'=>["Do Now & Clock In","Card sorting with real content","From sitemap to folder structure to real filenames","Lab: The MVP Scope List","Exit Ticket"],'et'=>"develop an appropriate navigation system and sitemap.",'ms'=>null],
24=>['ch'=>"Chapter 3: The Blueprint · Day 6 of 8",'min'=>false,'obj'=>["Develop wireframes for initial responsive design concepts."],'std'=>["NV 4.3.3 Develop wireframes for initial responsive design concepts"],'stdNote'=>null,'dnType'=>"Predict",'dn'=>"how many clicks should it take to reach the most important page on a site?",'tt'=>"Wireframes: Building in Grayscale First",'tasks'=>["Do Now & Clock In","Six-up sketching: six homepages in six minutes","Why lo-fi protects your schedule","Lab: The File Tree Map","Exit Ticket"],'et'=>"develop wireframes for initial responsive design concepts.",'ms'=>null],
25=>['ch'=>"Chapter 3: The Blueprint · Day 7 of 8",'min'=>false,'obj'=>["Differentiate voice, tone, and style in web writing.","Apply grammar and spelling conventions to web content.","Create a list of keywords and meta descriptions for SEO."],'std'=>["NV 4.4.1 Discuss and differentiate voice, tone, and style as it applies to web writing","NV 4.4.2 Determine the primary and secondary purposes of web content","NV 4.4.5 Apply grammar and spelling conventions to content","NV 4.4.4 Identify and create a list of keywords and descriptions (meta tags) for SEO","NV 4.4.8 List and describe best practices in content creation that foster indexing and ranking"],'stdNote'=>null,'dnType'=>"Predict",'dn'=>"the same sentence on a bank site and a skate shop site. What has to change?",'tt'=>"Writing That Does Not Embarrass the Client, and Getting Found",'tasks'=>["Do Now & Clock In","Rewriting one paragraph in three different voices; scannable writing and the 60-word rule","Title tags, meta descriptions, and honest SEO","Exit Ticket"],'et'=>"differentiate voice, tone, and style, and apply SEO best practices to web content.",'ms'=>null],
26=>['ch'=>"Chapter 3: The Blueprint · Day 8 of 8",'min'=>false,'obj'=>["Describe the role of social media in web development.","Create and implement a strategy that uses social networks to drive traffic to a website."],'std'=>["NV 2.4.1 Describe the role of social media in web development","NV 2.4.2 Explain the correlation between social media platforms and web links","NV 2.4.3 Describe the relationship of advertising, marketing, social media, and websites","NV 2.4.4 Discuss current trends in social media","NV 2.4.5 Create and implement a strategy that uses social networks to drive traffic to a website"],'stdNote'=>null,'dnType'=>"Predict",'dn'=>"you post a link and nobody clicks. Name one reason that has nothing to do with the website.",'tt'=>"Driving Real Traffic — Project Due",'tasks'=>["Do Now & Clock In","Why every site has share links and what they send back","Building a 30-day posting strategy with a measurable goal","Project: Blueprint [100 pts]","Exit Ticket"],'et'=>"create and implement a strategy that uses social networks to drive traffic to a website.",'ms'=>['title'=>"Blueprint",'pts'=>100]],
27=>['ch'=>"Chapter 4: The Artist · Day 1 of 7",'min'=>true,'obj'=>["Explain and apply the elements and principles of design."],'std'=>["NV 2.2.3 Explain and apply the elements of design","NV 2.2.2 Explain and apply the principles of design"],'stdNote'=>null,'dnType'=>"Reflect",'dn'=>"your blueprint is done. What is the one decision in it you would defend hardest?",'tt'=>"Elements and Principles: What Your Eye Does First (45 min)",'tasks'=>["Do Now & Clock In","Line, shape, space, texture, value: naming what you already see","Balance, contrast, emphasis, repetition, hierarchy","Lab: The Hierarchy Audit","Exit Ticket"],'et'=>"explain and apply the elements and principles of design.",'ms'=>null],
28=>['ch'=>"Chapter 4: The Artist · Day 2 of 7",'min'=>false,'obj'=>["Explain and apply color theory.","Evaluate the use of white space."],'std'=>["NV 2.2.1 Explain and apply color theory","NV 2.2.5 Evaluate the use of white space"],'stdNote'=>null,'dnType'=>"Predict",'dn'=>"a page is beautiful and nobody can find the button. Whose fault is that?",'tt'=>"Color Theory and Why Banks Are Blue",'tasks'=>["Do Now & Clock In","The wheel, the relationships, and the 60-30-10 rule","Before and after: the same page with room to breathe","Exit Ticket"],'et'=>"explain and apply color theory and evaluate the use of white space.",'ms'=>null],
29=>['ch'=>"Chapter 4: The Artist · Day 3 of 7",'min'=>false,'obj'=>["Explain and apply effective typography.","Identify commonly used layout techniques for web design."],'std'=>["NV 2.2.4 Explain and apply effective typography","NV 4.3.1 Identify commonly used layout techniques for web design"],'stdNote'=>null,'dnType'=>"Reflect",'dn'=>"name one thing white space did for the page that adding content could not.",'tt'=>"Typography and Layout Patterns That Already Work",'tasks'=>["Do Now & Clock In","Serif, sans, mono, display — and where each belongs; type scale, line length, line height","F-pattern, Z-pattern, hero, card grid","Lab: Brand UI Kit","Exit Ticket"],'et'=>"explain and apply effective typography and identify common layout techniques.",'ms'=>null],
30=>['ch'=>"Chapter 4: The Artist · Day 4 of 7",'min'=>true,'obj'=>["Create a branding message that presents a professional image."],'std'=>["NV 4.4.7 Create a branding message that will present a professional image"],'stdNote'=>null,'dnType'=>"Predict",'dn'=>"why do most shopping carts work the same way? Laziness or strategy?",'tt'=>"Components, States, and Sounding Like Someone On Purpose (45 min)",'tasks'=>["Do Now & Clock In","Components and the states every button needs","One sentence that says who you are and who you serve","Lab: The Component Lab","Exit Ticket"],'et'=>"create a branding message that presents a professional image.",'ms'=>null],
31=>['ch'=>"Chapter 4: The Artist · Day 5 of 7",'min'=>false,'obj'=>["Explain website usability procedures."],'std'=>["NV 4.6.4 Explain website usability procedures"],'stdNote'=>null,'dnType'=>"Reflect",'dn'=>"which layout pattern did you choose, and which did you reject?",'tt'=>"Prototyping and Watching a Real Person Struggle",'tasks'=>["Do Now & Clock In","Linking screens into a clickable flow","Think-aloud testing: say nothing, write everything down","Lab: The Linked Flow Lab","Exit Ticket"],'et'=>"explain website usability procedures.",'ms'=>null],
32=>['ch'=>"Chapter 4: The Artist · Day 6 of 7",'min'=>false,'obj'=>["Deliver client-ready screens built entirely from your own design system."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>"Predict",'dn'=>"how many people do you need to test with before you find most of the big problems?",'tt'=>"High-Fidelity Mockups: Real Content Only",'tasks'=>["Do Now & Clock In","Real content only — no lorem ipsum reaches a client","Developer hand-off: tokens, spacing, exported assets","Exit Ticket"],'et'=>"build high-fidelity mockups using only real content.",'ms'=>null],
33=>['ch'=>"Chapter 4: The Artist · Day 7 of 7",'min'=>false,'obj'=>["Deliver client-ready screens built entirely from your own design system."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>"Reflect",'dn'=>"what did a tester do with your prototype that you never expected?",'tt'=>"High-Fidelity Mockups — Project Due",'tasks'=>["Do Now & Clock In","Final polish pass against your own Chapter 4 design system","Project: Phase 2 (High-Fi Mockup) [100 pts]","Exit Ticket"],'et'=>"deliver client-ready screens built entirely from your own design system.",'ms'=>['title'=>"Phase 2 High-Fi Mockup",'pts'=>100]],
34=>['ch'=>"Capstone: The Community App · Day 1 of 2",'min'=>true,'obj'=>["Assemble Chapters 3-4 deliverables into one cohesive project package."],'std'=>[],'stdNote'=>"Capstone assembly day — integrates Chapter 3 (Blueprint) and Chapter 4 (High-Fi Mockup) into one submission.",'dnType'=>"Reflect",'dn'=>"your blueprint and your mockup were built weeks apart. Where do they disagree?",'tt'=>"Capstone Execution (Phase 1): Reconciling Research and Design (45 min)",'tasks'=>["Do Now & Clock In","Cross-check your sitemap, wireframes, and persona against your final mockup","Flag and fix any place the mockup drifted from the blueprint's own research","Exit Ticket"],'et'=>"reconcile a project's research phase against its final design phase.",'ms'=>null],
35=>['ch'=>"Capstone: The Community App · Day 2 of 2",'min'=>false,'obj'=>["Assemble Chapters 3-4 deliverables into one cohesive project package."],'std'=>[],'stdNote'=>"Capstone assembly day — final packaging and presentation.",'dnType'=>"Predict",'dn'=>"a stranger opens your Community App package cold. What do they need to see first?",'tt'=>"Capstone: The Community App — Assembly & Pitch",'tasks'=>["Do Now & Clock In","Assemble sitemap, wireframes, persona, and high-fi mockup into one package","Founder pitches: 3 minutes each, defend one design decision","Exit Ticket"],'et'=>"assemble and present a complete multi-chapter project package.",'ms'=>null],
36=>['ch'=>"Chapter 5: The \"Bones\" · Day 1 of 12",'min'=>false,'obj'=>["Explain the purpose of HTML in website development."],'std'=>["NV 5.1.1 Explain the purpose of Hypertext Markup Language (HTML) in website development"],'stdNote'=>null,'dnType'=>"Predict",'dn'=>"your mockup is beautiful. What has to happen before a browser can show it to anyone?",'tt'=>"What HTML Is and Why It Exists",'tasks'=>["Do Now & Clock In","View Source on a real site: the matrix behind the page","Setting up VS Code and Live Server","Lab: Capstone Setup","Exit Ticket"],'et'=>"explain the purpose of HTML in website development.",'ms'=>null],
37=>['ch'=>"Chapter 5: The \"Bones\" · Day 2 of 12",'min'=>false,'obj'=>["Differentiate among the versions of HTML.","Code a basic web page with proper document structure.","Identify HTML tags for authoring a web page document."],'std'=>["NV 5.1.2 Differentiate among the different versions of HTML","NV 5.1.4 Code a basic web page utilizing proper HTML document structure in a text editor","NV 5.1.3 Identify HTML tags for authoring a web page document"],'stdNote'=>null,'dnType'=>"Reflect",'dn'=>"what is HTML actually responsible for, and what is it NOT responsible for?",'tt'=>"Versions, the Boilerplate, and Your First Real Page",'tasks'=>["Do Now & Clock In","HTML4, XHTML, HTML5: what changed and why you care","Building the boilerplate by hand, line by line; nesting like parentheses","Exit Ticket"],'et'=>"differentiate among the versions of HTML and identify HTML tags.",'ms'=>null],
38=>['ch'=>"Chapter 5: The \"Bones\" · Day 3 of 12",'min'=>true,'obj'=>["Use text elements that carry meaning, not just size.","Build ordered, unordered, and description lists correctly."],'std'=>["NV 5.1.3 Identify HTML tags for authoring a web page document"],'stdNote'=>null,'dnType'=>"Predict",'dn'=>"why is a navigation menu almost always coded as a list?",'tt'=>"Headings, Text, and Lists (45 min)",'tasks'=>["Do Now & Clock In","h1 through h6 as an outline, not a size control; strong and em vs. b and i","Inspecting a real nav bar to find the hidden ul","Lab: Typography Translation","Exit Ticket"],'et'=>"use text elements that carry meaning and build lists correctly.",'ms'=>null],
39=>['ch'=>"Chapter 5: The \"Bones\" · Day 4 of 12",'min'=>false,'obj'=>["Describe correct file paths for relative and absolute links."],'std'=>["NV 4.2.3 Describe the usage of correct file paths for relative and absolute links"],'stdNote'=>null,'dnType'=>"Reflect",'dn'=>"where does a nested list actually go — inside the li or after it?",'tt'=>"Links and the Paths That Break on Upload",'tasks'=>["Do Now & Clock In","Absolute vs. relative, and what ../ really means","Why a link that works on your laptop 404s on the server","Lab: Nav List Structure","Exit Ticket"],'et'=>"describe correct file paths for relative and absolute links.",'ms'=>null],
40=>['ch'=>"Chapter 5: The \"Bones\" · Day 5 of 12",'min'=>false,'obj'=>["Identify semantic HTML tags.","Code a page using proper semantic document structure."],'std'=>["NV 5.1.3 Identify HTML tags for authoring a web page document","NV 5.1.4 Code a basic web page utilizing proper HTML document structure in a text editor"],'stdNote'=>null,'dnType'=>"Predict",'dn'=>"what does a page built entirely from div tags sound like to a screen reader?",'tt'=>"Semantic Layout: Giving the Page Landmarks",'tasks'=>["Do Now & Clock In","header, nav, main, footer, aside — the Big 5","Div soup vs. semantic markup in the accessibility tree","Lab: The Network Link Lab","Exit Ticket"],'et'=>"identify semantic HTML tags and code a page using semantic structure.",'ms'=>null],
41=>['ch'=>"Chapter 5: The \"Bones\" · Day 6 of 12",'min'=>true,'obj'=>["Choose between section, article, aside, and figure with a defensible test."],'std'=>["NV 5.1.3 Identify HTML tags for authoring a web page document"],'stdNote'=>null,'dnType'=>"Reflect",'dn'=>"why is main better than div class=\"main\"?",'tt'=>"Sectioning and Grouping Content (45 min)",'tasks'=>["Do Now & Clock In","The RSS test: would this make sense on its own?","Lab: The Global Skeleton","Exit Ticket"],'et'=>"choose between section, article, aside, and figure with a defensible test.",'ms'=>null],
42=>['ch'=>"Chapter 5: The \"Bones\" · Day 7 of 12",'min'=>false,'obj'=>["Optimize web pages to accommodate users with special needs."],'std'=>["NV 4.6.3 Optimize websites to accommodate users with special needs"],'stdNote'=>null,'dnType'=>"Predict",'dn'=>"when should an image have EMPTY alt text? There is a correct answer.",'tt'=>"Images and Writing for Someone Who Cannot See Them",'tasks'=>["Do Now & Clock In","Turning images off and reading what is left","The alt text decision tree: decorative, informative, functional","Lab: Content Blocks","Exit Ticket"],'et'=>"optimize web pages to accommodate users with special needs.",'ms'=>null],
43=>['ch'=>"Chapter 5: The \"Bones\" · Day 8 of 12",'min'=>false,'obj'=>["Build accessible forms with correctly associated labels."],'std'=>["NV 4.6.3 Optimize websites to accommodate users with special needs"],'stdNote'=>null,'dnType'=>"Reflect",'dn'=>"what alt text belongs on a purely decorative divider image?",'tt'=>"Forms Everyone Can Actually Use",'tasks'=>["Do Now & Clock In","Why a placeholder is not a label","Input types, required, pattern, fieldset and legend","Lab: Image Placeholders","Exit Ticket"],'et'=>"build accessible forms with correctly associated labels.",'ms'=>null],
44=>['ch'=>"Chapter 5: The \"Bones\" · Day 9 of 12",'min'=>true,'obj'=>["Handle encoding and special characters correctly."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>"Predict",'dn'=>"you paste a curly quote from a Word doc into your page. What shows up?",'tt'=>"Character Sets and Your Full Contact Form (45 min)",'tasks'=>["Do Now & Clock In","UTF-8, entities, and the meta tag that has to come first","Lab: Full Contact Form","Exit Ticket"],'et'=>"handle encoding and special characters correctly.",'ms'=>null],
45=>['ch'=>"Chapter 5: The \"Bones\" · Day 10 of 12",'min'=>false,'obj'=>["Utilize verification tools to verify code."],'std'=>["NV 5.1.5 Utilize verification tools to verify code"],'stdNote'=>null,'dnType'=>"Reflect",'dn'=>"why can you not just type a < character inside your page text?",'tt'=>"Proving It Works: Validation Tools",'tasks'=>["Do Now & Clock In","Reading a validator message: line, expected, actual","The five errors that cause most failures","Exit Ticket"],'et'=>"utilize verification tools to verify code.",'ms'=>null],
46=>['ch'=>"Chapter 5: The \"Bones\" · Day 11 of 12",'min'=>false,'obj'=>["Utilize verification tools to reach zero validation errors."],'std'=>["NV 5.1.5 Utilize verification tools to verify code"],'stdNote'=>null,'dnType'=>"Predict",'dn'=>"how many validation errors do you think your site has right now? Write the number.",'tt'=>"Zero Error Audit — Milestone Due",'tasks'=>["Do Now & Clock In","Validating every page to zero","Peer code review: comment on the code, not the coder","Milestone: The Zero Error Audit [50 pts]","Exit Ticket"],'et'=>"utilize verification tools to reach zero validation errors.",'ms'=>['title'=>"The Zero Error Audit",'pts'=>50]],
47=>['ch'=>"Chapter 5: The \"Bones\" · Day 12 of 12",'min'=>false,'obj'=>["Prepare a clean, validated HTML build for Capstone assembly."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>"Reflect",'dn'=>"what is the single most common error you fixed across your whole site?",'tt'=>"Final HTML Polish Before the Capstone",'tasks'=>["Do Now & Clock In","Last validation pass; confirm every semantic landmark is in place","Organize files for Capstone hand-off","Exit Ticket"],'et'=>"prepare a clean, validated HTML build for Capstone assembly.",'ms'=>null],
48=>['ch'=>"Capstone: Q1/Q2 HTML · Day 1 of 2",'min'=>true,'obj'=>["Assemble a complete, validated, semantic multi-page HTML site."],'std'=>[],'stdNote'=>"Capstone assembly day — no new performance indicator introduced.",'dnType'=>"Reflect",'dn'=>"your foundation is cracked, your CSS house will collapse. What foundation problem worries you most?",'tt'=>"Capstone Setup: Assembling Home, About, and Contact (45 min)",'tasks'=>["Do Now & Clock In","Confirm index.html, about.html, and contact.html are all present, semantic, and validated","Cross-link the three pages and re-test every path","Exit Ticket"],'et'=>"assemble a complete multi-page HTML site with working navigation.",'ms'=>null],
49=>['ch'=>"Capstone: Q1/Q2 HTML · Day 2 of 2",'min'=>false,'obj'=>["Assemble a complete, validated, semantic multi-page HTML site."],'std'=>[],'stdNote'=>"Capstone assembly day — final submission.",'dnType'=>"Predict",'dn'=>"what is the first thing a validator will flag on a rushed page? Commit to a guess.",'tt'=>"Capstone: Q1/Q2 HTML — Final Validation & Submission",'tasks'=>["Do Now & Clock In","Final W3C validation pass on all three pages","Submit the Capstone HTML build","Exit Ticket"],'et'=>"submit a complete, validated, semantic multi-page HTML build.",'ms'=>null],
50=>['ch'=>"Chapter 6: The \"Clothes\" · Day 1 of 16",'min'=>false,'obj'=>["Describe the role of CSS in relation to web design.","Identify the uses of Cascading Style Sheets."],'std'=>["NV 5.2.1 Describe the role of CSS in relation to web design","NV 4.3.5 Identify the uses of Cascading Style Sheets (CSS)"],'stdNote'=>null,'dnType'=>"Reflect",'dn'=>"your HTML validates and it is ugly. Whose job is it to fix that?",'tt'=>"What CSS Does and Why It Is Separate",'tasks'=>["Do Now & Clock In","Disabling CSS on a real site: what survives","Lab: The External Sheet","Exit Ticket"],'et'=>"describe the role of CSS in relation to web design.",'ms'=>null],
51=>['ch'=>"Chapter 6: The \"Clothes\" · Day 2 of 16",'min'=>false,'obj'=>["Identify the structure of CSS style rules."],'std'=>["NV 5.2.2 Identify the structure of CSS style rules"],'stdNote'=>null,'dnType'=>"Predict",'dn'=>"what are the three parts of a CSS rule? Guess before we name them.",'tt'=>"The Anatomy of a Rule",'tasks'=>["Do Now & Clock In","Selector, property, value — and the semicolon that ruins your day","Comments and why professionals leave them","Exit Ticket"],'et'=>"identify the structure of CSS style rules.",'ms'=>null],
52=>['ch'=>"Chapter 6: The \"Clothes\" · Day 3 of 16",'min'=>false,'obj'=>["Differentiate between internal, external, and inline style sheets."],'std'=>["NV 5.2.4 Differentiate between internal, external, and inline style sheets"],'stdNote'=>null,'dnType'=>"Reflect",'dn'=>"write one complete CSS rule from memory. No notes.",'tt'=>"Inline, Internal, External: Pick One",'tasks'=>["Do Now & Clock In","The same rule three ways, and which one scales to 40 pages","Lab: Structural Targeting","Exit Ticket"],'et'=>"differentiate between internal, external, and inline style sheets.",'ms'=>null],
53=>['ch'=>"Chapter 6: The \"Clothes\" · Day 4 of 16",'min'=>true,'obj'=>["Diagnose style problems in the browser instead of guessing."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>"Predict",'dn'=>"your rule is definitely correct and nothing changed on screen. Name one reason.",'tt'=>"DevTools: Your Fastest Feedback Loop (45 min)",'tasks'=>["Do Now & Clock In","Inspect, Styles, Computed, and the box model diagram","Exit Ticket"],'et'=>"diagnose style problems in the browser instead of guessing.",'ms'=>null],
54=>['ch'=>"Chapter 6: The \"Clothes\" · Day 5 of 16",'min'=>false,'obj'=>["Describe CSS selector types."],'std'=>["NV 5.2.3 Describe CSS selector types"],'stdNote'=>null,'dnType'=>"Reflect",'dn'=>"which DevTools panel shows the value that actually won?",'tt'=>"Selectors: Aiming at the Right Thing",'tasks'=>["Do Now & Clock In","Tag, class, id, descendant, child, attribute","Naming classes by purpose, not by what they look like","Exit Ticket"],'et'=>"describe CSS selector types.",'ms'=>null],
55=>['ch'=>"Chapter 6: The \"Clothes\" · Day 6 of 16",'min'=>false,'obj'=>["Predict which rule wins a style conflict and explain why."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>"Predict",'dn'=>"two rules target the same element and disagree. How does the browser decide?",'tt'=>"The Cascade, Inheritance, and Who Wins",'tasks'=>["Do Now & Clock In","Specificity math: 100-10-1","Why !important is usually an admission of defeat","Lab: Specificity Audit","Exit Ticket"],'et'=>"predict which rule wins a style conflict and explain why.",'ms'=>null],
56=>['ch'=>"Chapter 6: The \"Clothes\" · Day 7 of 16",'min'=>true,'obj'=>["Use CSS to style webpage content, starting with color."],'std'=>["NV 5.2.5 Use CSS to style webpage content (e.g., typography, web fonts)"],'stdNote'=>null,'dnType'=>"Reflect",'dn'=>"score .nav a against #main. Show your math.",'tt'=>"Color in Code (45 min)",'tasks'=>["Do Now & Clock In","Hex, RGB, HSL, and why designers think in HSL","Lab: CSS Variables","Exit Ticket"],'et'=>"use CSS to style webpage content, starting with color.",'ms'=>null],
57=>['ch'=>"Chapter 6: The \"Clothes\" · Day 8 of 16",'min'=>false,'obj'=>["Use CSS to style typography and web fonts."],'std'=>["NV 5.2.5 Use CSS to style webpage content (e.g., typography, web fonts)"],'stdNote'=>null,'dnType'=>"Predict",'dn'=>"your custom font fails to download on a slow connection. What does the visitor see?",'tt'=>"Web Fonts and What Happens When They Fail",'tasks'=>["Do Now & Clock In","Font stacks, fallbacks, and font-display","The performance cost of loading five weights","Lab: Brand Typography","Exit Ticket"],'et'=>"use CSS to style typography and web fonts.",'ms'=>null],
58=>['ch'=>"Chapter 6: The \"Clothes\" · Day 9 of 16",'min'=>false,'obj'=>["Choose units that respect the user's own browser settings."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>"Reflect",'dn'=>"why does a font stack always end with a generic family?",'tt'=>"Sizing Text for People Who Changed Their Settings",'tasks'=>["Do Now & Clock In","px vs. em vs. rem, and the accessibility reason it matters","Setting the browser to 24px and seeing what breaks","Exit Ticket"],'et'=>"choose units that respect the user's own browser settings.",'ms'=>null],
59=>['ch'=>"Chapter 6: The \"Clothes\" · Day 10 of 16",'min'=>true,'obj'=>["Compute the true rendered size of an element."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>"Predict",'dn'=>"width 300px plus 20px padding. How wide is it on screen? Commit to a number.",'tt'=>"The Box Model and Spacing Math (45 min)",'tasks'=>["Do Now & Clock In","Content, padding, border, margin — and border-box","Lab: Spacing & Breathing","Exit Ticket"],'et'=>"compute the true rendered size of an element.",'ms'=>null],
60=>['ch'=>"Chapter 6: The \"Clothes\" · Day 11 of 16",'min'=>false,'obj'=>["Apply decorative styling that clarifies rather than decorates."],'std'=>["NV 5.2.5 Use CSS to style webpage content (e.g., typography, web fonts)"],'stdNote'=>null,'dnType'=>"Reflect",'dn'=>"width 200, padding 10, border 5. What is the rendered width by default?",'tt'=>"Borders, Backgrounds, and Restraint",'tasks'=>["Do Now & Clock In","Gradients, radius, and what a shadow should communicate","Lab: Visual Accents","Exit Ticket"],'et'=>"apply decorative styling that clarifies rather than decorates.",'ms'=>null],
61=>['ch'=>"Chapter 6: The \"Clothes\" · Day 12 of 16",'min'=>false,'obj'=>["Utilize online validation tools for CSS."],'std'=>["NV 5.2.7 Utilize online validation tools for CSS"],'stdNote'=>null,'dnType'=>"Predict",'dn'=>"why does the same page look slightly different in Chrome and Safari?",'tt'=>"Resets, Normalize, and Checking Your Work",'tasks'=>["Do Now & Clock In","Reset vs. normalize and why it goes first","Reading CSS validator output; typos fail silently","Lab: Browser Reset","Exit Ticket"],'et'=>"utilize online validation tools for CSS.",'ms'=>null],
62=>['ch'=>"Chapter 6: The \"Clothes\" · Day 13 of 16",'min'=>true,'obj'=>["Organize a stylesheet so another developer could maintain it."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>"Reflect",'dn'=>"name one CSS rule you wrote weeks ago that you would not recognize today.",'tt'=>"Stylesheet Organization: Sections, Order, and Naming (45 min)",'tasks'=>["Do Now & Clock In","Grouping rules by component instead of by page; a consistent naming convention","Peer swap: can your partner find the button styles in 10 seconds?","Exit Ticket"],'et'=>"organize a stylesheet so another developer could maintain it.",'ms'=>null],
63=>['ch'=>"Chapter 6: The \"Clothes\" · Day 14 of 16",'min'=>false,'obj'=>["Apply a complete design system consistently across every page of a site."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>"Predict",'dn'=>"you have three pages. How many places define your primary blue right now?",'tt'=>"Refactor Pass: Hunting Duplicate Rules",'tasks'=>["Do Now & Clock In","Find-and-replace hardcoded colors with your CSS variables","Confirm every page pulls from the same external sheet","Exit Ticket"],'et'=>"apply a complete design system consistently across every page of a site.",'ms'=>null],
64=>['ch'=>"Chapter 6: The \"Clothes\" · Day 15 of 16",'min'=>false,'obj'=>["Apply a complete design system across every page of a site."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>"Reflect",'dn'=>"name one duplicated rule you refactored and how many places it fixed.",'tt'=>"Cross-Browser and Cross-Device Spot Check",'tasks'=>["Do Now & Clock In","Checking your site in a second browser","Fixing anything that only worked by accident","Exit Ticket"],'et'=>"verify a design system renders consistently across browsers.",'ms'=>null],
65=>['ch'=>"Chapter 6: The \"Clothes\" · Day 16 of 16",'min'=>true,'obj'=>["Apply a complete design system across every page of a site."],'std'=>[],'stdNote'=>"Project due day.",'dnType'=>"Predict",'dn'=>"what will a stranger notice first when they open your finished site?",'tt'=>"Base CSS Integration — Project Due (45 min)",'tasks'=>["Do Now & Clock In","Final integration check across every page","Project: Base CSS Integration [100 pts]","Exit Ticket"],'et'=>"apply a complete design system across every page of a site.",'ms'=>['title'=>"Base CSS Integration",'pts'=>100]],
66=>['ch'=>"Chapter 7: The \"Style\" · Day 1 of 15",'min'=>true,'obj'=>["Control how elements stack and sit using display types."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>"Reflect",'dn'=>"your site is styled and every element is stacked in one column. Why?",'tt'=>"Document Flow: Bricks and Beads (45 min)",'tasks'=>["Do Now & Clock In","Block, inline, inline-block — and why width does nothing on a span","Lab: Display Fixes","Exit Ticket"],'et'=>"control how elements stack and sit using display types.",'ms'=>null],
67=>['ch'=>"Chapter 7: The \"Style\" · Day 2 of 15",'min'=>false,'obj'=>["Use CSS to lay out webpage content with flexbox."],'std'=>["NV 5.2.6 Use CSS to lay out webpage content (e.g., flexbox, grid, positioning: static, relative, absolute, fixed)"],'stdNote'=>null,'dnType'=>"Predict",'dn'=>"before flexbox, centering something vertically was famously hard. Why would that be?",'tt'=>"Flexbox: One Direction at a Time",'tasks'=>["Do Now & Clock In","Container and items: the parent controls the children","flex-direction, and what the main axis actually is","Milestones 2 & 3: Flexbox Navigation","Exit Ticket"],'et'=>"use CSS to lay out webpage content with flexbox.",'ms'=>null],
68=>['ch'=>"Chapter 7: The \"Style\" · Day 3 of 15",'min'=>true,'obj'=>["Align, distribute, and wrap content along both axes."],'std'=>["NV 5.2.6 Use CSS to lay out webpage content (e.g., flexbox, grid, positioning: static, relative, absolute, fixed)"],'stdNote'=>null,'dnType'=>"Reflect",'dn'=>"what does flex-direction column do to the main axis?",'tt'=>"Flexbox Alignment and Wrapping",'tasks'=>["Do Now & Clock In","justify-content vs. align-items","gap, wrap, and flex: 1","Lab: Centering & Wrapping","Exit Ticket"],'et'=>"align, distribute, and wrap content along both axes.",'ms'=>null],
69=>['ch'=>"Chapter 7: The \"Style\" · Day 4 of 15",'min'=>false,'obj'=>["Use CSS to lay out webpage content with grid."],'std'=>["NV 5.2.6 Use CSS to lay out webpage content (e.g., flexbox, grid, positioning: static, relative, absolute, fixed)"],'stdNote'=>null,'dnType'=>"Predict",'dn'=>"flexbox handles one direction. What problem does that create for a whole page layout?",'tt'=>"CSS Grid: Two Dimensions at Once",'tasks'=>["Do Now & Clock In","Tracks, fr units, and the grid overlay in DevTools","repeat(auto-fit, minmax()) — responsive with zero media queries","Milestones 4 & 5: The Grid Skeleton","Exit Ticket"],'et'=>"use CSS to lay out webpage content with grid.",'ms'=>null],
70=>['ch'=>"Chapter 7: The \"Style\" · Day 5 of 15",'min'=>false,'obj'=>["Build multi-region layouts using named grid areas."],'std'=>["NV 5.2.6 Use CSS to lay out webpage content (e.g., flexbox, grid, positioning: static, relative, absolute, fixed)"],'stdNote'=>null,'dnType'=>"Reflect",'dn'=>"what does 1fr actually mean? Explain it without using the word \"fraction.\"",'tt'=>"Named Areas and Rearranging Without Touching HTML",'tasks'=>["Do Now & Clock In","grid-template-areas and line-based placement","The accessibility trap: visual order vs. reading order","Lab: The Grid Gallery","Exit Ticket"],'et'=>"build multi-region layouts using named grid areas.",'ms'=>null],
71=>['ch'=>"Chapter 7: The \"Style\" · Day 6 of 15",'min'=>true,'obj'=>["Use positioning: static, relative, absolute, fixed, and sticky."],'std'=>["NV 5.2.6 Use CSS to lay out webpage content (e.g., flexbox, grid, positioning: static, relative, absolute, fixed)"],'stdNote'=>null,'dnType'=>"Predict",'dn'=>"an absolutely positioned element with no positioned parent. Where does it go?",'tt'=>"Positioning and Z-Index (45 min)",'tasks'=>["Do Now & Clock In","Sticky headers, pinned badges, and stacking contexts","Lab: The Sticky Header","Exit Ticket"],'et'=>"use positioning: static, relative, absolute, fixed, and sticky.",'ms'=>null],
72=>['ch'=>"Chapter 7: The \"Style\" · Day 7 of 15",'min'=>false,'obj'=>["Develop responsive design for various devices."],'std'=>["NV 4.3.4 Develop responsive design for various devices"],'stdNote'=>null,'dnType'=>"Reflect",'dn'=>"what is the difference between fixed and sticky?",'tt'=>"Stop Using Pixels",'tasks'=>["Do Now & Clock In","%, em, rem, vw, vh, ch — and when each is correct","max-width in ch and readable line length","Lab: The Viewport Meta","Exit Ticket"],'et'=>"develop responsive design for various devices.",'ms'=>null],
73=>['ch'=>"Chapter 7: The \"Style\" · Day 8 of 15",'min'=>true,'obj'=>["Develop responsive design using media queries."],'std'=>["NV 4.3.4 Develop responsive design for various devices"],'stdNote'=>null,'dnType'=>"Predict",'dn'=>"should a breakpoint come from a popular phone size, or from something else?",'tt'=>"Media Queries: Letting Content Set the Breakpoint",'tasks'=>["Do Now & Clock In","Narrowing the browser until it breaks — that is your breakpoint","prefers-reduced-motion and prefers-color-scheme","Milestones 8 & 9: Breakpoints","Exit Ticket"],'et'=>"develop responsive design using media queries.",'ms'=>null],
74=>['ch'=>"Chapter 7: The \"Style\" · Day 9 of 15",'min'=>false,'obj'=>["Refactor a stylesheet to mobile-first and cut the override count."],'std'=>["NV 4.3.4 Develop responsive design for various devices"],'stdNote'=>null,'dnType'=>"Reflect",'dn'=>"name your two breakpoints and the content problem that set each one.",'tt'=>"Mobile-First Refactoring (45 min)",'tasks'=>["Do Now & Clock In","min-width vs. max-width and why one produces less code","Lab: Mobile-First Refactoring","Exit Ticket"],'et'=>"refactor a stylesheet to mobile-first and cut the override count.",'ms'=>null],
75=>['ch'=>"Chapter 7: The \"Style\" · Day 10 of 15",'min'=>false,'obj'=>["Describe the function of a CSS preprocessor."],'std'=>["NV 5.2.8 Describe the function of a CSS preprocessor"],'stdNote'=>null,'dnType'=>"Predict",'dn'=>"your stylesheet is 900 lines and you use the same blue in 40 places. What would help?",'tt'=>"Preprocessors: What Sass Is For",'tasks'=>["Do Now & Clock In","Variables, nesting, partials — and what compiles to plain CSS","Exit Ticket"],'et'=>"describe the function of a CSS preprocessor.",'ms'=>null],
76=>['ch'=>"Chapter 7: The \"Style\" · Day 11 of 15",'min'=>true,'obj'=>["Audit a layout across every breakpoint and triage what breaks."],'std'=>["NV 4.3.4 Develop responsive design for various devices"],'stdNote'=>null,'dnType'=>"Reflect",'dn'=>"name one thing a preprocessor does that plain CSS now does too.",'tt'=>"The Architecture Audit",'tasks'=>["Do Now & Clock In","320, 768, 1440: no horizontal scroll, no orphans","Peer device testing on real hardware","Lab: Cross-Device Triage","Exit Ticket"],'et'=>"audit a layout across every breakpoint and triage what breaks.",'ms'=>null],
77=>['ch'=>"Chapter 7: The \"Style\" · Day 12 of 15",'min'=>false,'obj'=>["Fix triaged responsive bugs found in the architecture audit."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>"Predict",'dn'=>"what will break on a device you do not own? Name one thing before you test.",'tt'=>"Fixing What the Audit Found",'tasks'=>["Do Now & Clock In","Working the triage list from yesterday's audit","Re-testing every breakpoint after each fix","Exit Ticket"],'et'=>"fix triaged responsive bugs found in a layout audit.",'ms'=>null],
78=>['ch'=>"Chapter 7: The \"Style\" · Day 13 of 15",'min'=>true,'obj'=>["Deliver a layout that works from phone to desktop."],'std'=>["NV 5.2.6 Use CSS to lay out webpage content (e.g., flexbox, grid, positioning: static, relative, absolute, fixed)"],'stdNote'=>null,'dnType'=>"Reflect",'dn'=>"which breakpoint gave you the most trouble, and why?",'tt'=>"Final Layout Polish (45 min)",'tasks'=>["Do Now & Clock In","Last pass on flex/grid layouts across all pages","Confirm sticky header and z-index stacking behave everywhere","Exit Ticket"],'et'=>"deliver a layout that works from phone to desktop.",'ms'=>null],
79=>['ch'=>"Chapter 7: The \"Style\" · Day 14 of 15",'min'=>false,'obj'=>["Deliver a layout that works from phone to desktop."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>"Predict",'dn'=>"if a client only tests on their own laptop, what will they never catch?",'tt'=>"Peer Device Testing Round 2",'tasks'=>["Do Now & Clock In","Trade devices with a partner one more time","Log and fix any remaining breakpoint bugs","Exit Ticket"],'et'=>"test a responsive layout on unfamiliar devices and fix what breaks.",'ms'=>null],
80=>['ch'=>"Chapter 7: The \"Style\" · Day 15 of 15",'min'=>false,'obj'=>["Deliver a layout that works from phone to desktop."],'std'=>[],'stdNote'=>"Project due day.",'dnType'=>"Reflect",'dn'=>"what is the one layout decision you are most proud of this chapter?",'tt'=>"Architecture — Project Due",'tasks'=>["Do Now & Clock In","Final submission check across every breakpoint","Project: Architecture [100 pts]","Exit Ticket"],'et'=>"deliver a layout that works from phone to desktop.",'ms'=>['title'=>"Architecture",'pts'=>100]],
81=>['ch'=>"Chapter 8: Sights & Sounds · Day 1 of 14",'min'=>false,'obj'=>["Describe common media file formats."],'std'=>["NV 4.5.1 Describe common media file formats"],'stdNote'=>null,'dnType'=>"Reflect",'dn'=>"your layout works everywhere. What is still making the page slow?",'tt'=>"Media File Formats and What They Cost",'tasks'=>["Do Now & Clock In","JPG, PNG, WebP, SVG, MP4, MP3 — and when each wins","Exit Ticket"],'et'=>"describe common media file formats.",'ms'=>null],
82=>['ch'=>"Chapter 8: Sights & Sounds · Day 2 of 14",'min'=>true,'obj'=>["Identify appropriate software for media creation.","Create and edit media files."],'std'=>["NV 4.5.2 Identify appropriate software for media creation","NV 4.5.3 Create and edit media files (e.g., sound, video, graphics, interactive media, multimedia)"],'stdNote'=>null,'dnType'=>"Predict",'dn'=>"a 6 MB phone photo goes on a website. What has to happen to it first?",'tt'=>"The Tools Professionals Actually Use (45 min)",'tasks'=>["Do Now & Clock In","Photoshop Image Size and Export As; Illustrator to clean SVG","Creating your own assets instead of hunting for them","Exit Ticket"],'et'=>"identify appropriate software for media creation.",'ms'=>null],
83=>['ch'=>"Chapter 8: Sights & Sounds · Day 3 of 14",'min'=>false,'obj'=>["Optimize media files for uploading using compression tools."],'std'=>["NV 4.5.4 Optimize media files for uploading using compression tools"],'stdNote'=>null,'dnType'=>"Reflect",'dn'=>"name the right format for a logo and the right format for a photograph.",'tt'=>"Compression and the Performance Budget",'tasks'=>["Do Now & Clock In","Lossy vs. lossless, and loading a page on throttled 3G","Milestone: Raster Compression","Exit Ticket"],'et'=>"optimize media files for uploading using compression tools.",'ms'=>null],
84=>['ch'=>"Chapter 8: Sights & Sounds · Day 4 of 14",'min'=>true,'obj'=>["Calculate and convert images to desired sizes and resolution."],'std'=>["NV 4.5.6 Calculate and convert images to desired sizes and resolution"],'stdNote'=>null,'dnType'=>"Predict",'dn'=>"an image is 1920 by 1080. What is its aspect ratio, and why does that matter?",'tt'=>"Doing the Math on Image Size (45 min)",'tasks'=>["Do Now & Clock In","Ratios, resolution, and object-fit instead of squishing","Exit Ticket"],'et'=>"calculate and convert images to desired sizes and resolution.",'ms'=>null],
85=>['ch'=>"Chapter 8: Sights & Sounds · Day 5 of 14",'min'=>true,'obj'=>["Create and embed a clean, optimized SVG logo."],'std'=>["NV 4.5.3 Create and edit media files (e.g., sound, video, graphics, interactive media, multimedia)"],'stdNote'=>null,'dnType'=>"Reflect",'dn'=>"why does a logo scale perfectly as an SVG but blur as a JPG?",'tt'=>"Vectors: The Logo That Never Blurs",'tasks'=>["Do Now & Clock In","Vector vs. raster, one more time, with your own logo","Milestone: The SVG Logo & Favicons","Exit Ticket"],'et'=>"create and embed a clean, optimized SVG logo.",'ms'=>null],
86=>['ch'=>"Chapter 8: Sights & Sounds · Day 6 of 14",'min'=>true,'obj'=>["Embed media files in a web design."],'std'=>["NV 4.5.5 Embed media files in a web design"],'stdNote'=>null,'dnType'=>"Predict",'dn'=>"your gallery images are all different sizes. What is the amateur fix and what is the real one?",'tt'=>"Putting Media on the Page (45 min)",'tasks'=>["Do Now & Clock In","figure and figcaption; srcset and picture","Milestone: Responsive Imagery","Exit Ticket"],'et'=>"embed media files in a web design.",'ms'=>null],
87=>['ch'=>"Chapter 8: Sights & Sounds · Day 7 of 14",'min'=>true,'obj'=>["Embed accessible video and audio with text alternatives."],'std'=>["NV 4.5.5 Embed media files in a web design"],'stdNote'=>null,'dnType'=>"Reflect",'dn'=>"who benefits from video captions besides people who are deaf?",'tt'=>"Video and Audio Everyone Can Use",'tasks'=>["Do Now & Clock In","WebVTT captions, transcripts, and why autoplay is blocked","Milestone: Code Correction (Video)","Exit Ticket"],'et'=>"embed accessible video with text alternatives.",'ms'=>null],
88=>['ch'=>"Chapter 8: Sights & Sounds · Day 8 of 14",'min'=>false,'obj'=>["Embed accessible video and audio with text alternatives."],'std'=>["NV 4.5.5 Embed media files in a web design"],'stdNote'=>null,'dnType'=>"Predict",'dn'=>"an audio player has no visible controls. Who does that lock out?",'tt'=>"Audio Everyone Can Use",'tasks'=>["Do Now & Clock In","Native audio controls, formats, and fallback text","Milestone: Code Correction (Audio)","Exit Ticket"],'et'=>"embed accessible audio with text alternatives.",'ms'=>null],
89=>['ch'=>"Chapter 8: Sights & Sounds · Day 9 of 14",'min'=>false,'obj'=>["Evaluate existing content for web use."],'std'=>["NV 4.4.6 Evaluate existing content for web use (e.g., images, print documents, text, video)"],'stdNote'=>null,'dnType'=>"Reflect",'dn'=>"name three groups helped by captions besides deaf users.",'tt'=>"Judging Content You Did Not Make",'tasks'=>["Do Now & Clock In","A client hands you a folder of assets. What do you keep?","Licensing, quality, and format triage","Exit Ticket"],'et'=>"evaluate existing content for web use.",'ms'=>null],
90=>['ch'=>"Chapter 8: Sights & Sounds · Day 10 of 14",'min'=>true,'obj'=>["Build semantic data tables and embed third-party content responsibly."],'std'=>["NV 4.5.5 Embed media files in a web design"],'stdNote'=>null,'dnType'=>"Predict",'dn'=>"what is the difference between using a table for data and using one for layout?",'tt'=>"Tables, Embeds, and the Accessibility Pass (45 min)",'tasks'=>["Do Now & Clock In","caption, thead, th scope — what a screen reader hears","iframes: title, lazy loading, and the privacy cost","Milestone: Semantic Data Tables","Exit Ticket"],'et'=>"build semantic data tables and embed third-party content responsibly.",'ms'=>null],
91=>['ch'=>"Chapter 8: Sights & Sounds · Day 11 of 14",'min'=>false,'obj'=>["Embed accessible maps and video responsibly."],'std'=>["NV 4.5.5 Embed media files in a web design"],'stdNote'=>null,'dnType'=>"Reflect",'dn'=>"why does a Google Map embed need fallback text?",'tt'=>"Map & Video Embeds",'tasks'=>["Do Now & Clock In","iframe title attributes and lazy loading","Milestone: Map & Video Embeds","Exit Ticket"],'et'=>"embed accessible maps and video responsibly.",'ms'=>null],
92=>['ch'=>"Chapter 8: Sights & Sounds · Day 12 of 14",'min'=>false,'obj'=>["Apply proportional sizing and interactive hover states."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>"Predict",'dn'=>"why does a stretched image look unprofessional even at the right pixel size?",'tt'=>"Proportions and Hover Effects",'tasks'=>["Do Now & Clock In","object-fit vs. forced dimensions","Milestone: Proportions & Hover Effects","Exit Ticket"],'et'=>"apply proportional sizing and interactive hover states.",'ms'=>null],
93=>['ch'=>"Chapter 8: Sights & Sounds · Day 13 of 14",'min'=>false,'obj'=>["Participate in a service-learning or community project."],'std'=>["NV 1.3.2 Participate in a service learning (program related) and/or community service project or activity"],'stdNote'=>null,'dnType'=>"Reflect",'dn'=>"what is your heaviest page right now, and what is on it?",'tt'=>"Broken Link Hunt and the Community Check-In",'tasks'=>["Do Now & Clock In","Broken link hunt across every page","Community project check-in: who are you actually helping?","Exit Ticket"],'et'=>"participate in a service-learning or community project.",'ms'=>null],
94=>['ch'=>"Chapter 8: Sights & Sounds · Day 14 of 14",'min'=>false,'obj'=>["Deliver an optimized, accessible media build."],'std'=>[],'stdNote'=>"Project due day.",'dnType'=>"Predict",'dn'=>"what is the first thing a Lighthouse audit will flag on a media-heavy page?",'tt'=>"Media Integration — Project Due",'tasks'=>["Do Now & Clock In","Final Lighthouse pass","Project: Media Integration [100 pts]","Exit Ticket"],'et'=>"deliver an optimized, accessible media build.",'ms'=>['title'=>"Media Integration",'pts'=>100]],
95=>['ch'=>"Capstone: Year 1 Portfolio · Day 1 of 4",'min'=>true,'obj'=>["Assemble every Year 1 chapter deliverable into one portfolio site."],'std'=>[],'stdNote'=>"Capstone assembly day — no new performance indicator introduced.",'dnType'=>"Reflect",'dn'=>"one year from now, what is the first thing you will have forgotten? Write it down.",'tt'=>"Capstone Assembly: Gathering the Year's Work (45 min)",'tasks'=>["Do Now & Clock In","Inventory every Chapter 2-8 deliverable that belongs in the portfolio","Confirm file paths and links survive being moved into one site","Exit Ticket"],'et'=>"inventory and organize a year's worth of deliverables into one site.",'ms'=>null],
96=>['ch'=>"Capstone: Year 1 Portfolio · Day 2 of 4",'min'=>false,'obj'=>["Deliver a working, accessible, responsive portfolio site."],'std'=>[],'stdNote'=>"Capstone assembly day — no new performance indicator introduced.",'dnType'=>"Predict",'dn'=>"a stranger has 10 seconds on your portfolio homepage. What do they need to see?",'tt'=>"Building the Portfolio Homepage",'tasks'=>["Do Now & Clock In","Design a homepage that links to every chapter's best work","Final accessibility and responsive spot check","Exit Ticket"],'et'=>"build a homepage that showcases a year's worth of work.",'ms'=>null],
97=>['ch'=>"Capstone: Year 1 Portfolio · Day 3 of 4",'min'=>true,'obj'=>["Deploy a complete portfolio site and verify every link works."],'std'=>[],'stdNote'=>"Capstone assembly day — no new performance indicator introduced.",'dnType'=>"Reflect",'dn'=>"what is the one piece of Year 1 work you are proudest to show a stranger?",'tt'=>"Deployment and the Broken Link Hunt (45 min)",'tasks'=>["Do Now & Clock In","Upload the finished portfolio site","Full link and asset check across every page","Exit Ticket"],'et'=>"deploy a portfolio site and verify every link works.",'ms'=>null],
98=>['ch'=>"Capstone: Year 1 Portfolio · Day 4 of 4",'min'=>false,'obj'=>["Present a completed Year 1 portfolio and reflect on program standards achieved."],'std'=>["NV 1.5.2 Explain the importance of participation and completion of a program of study"],'stdNote'=>null,'dnType'=>"Predict",'dn'=>"what do you think \"CTE Program Completer\" appears on, and who reads it?",'tt'=>"Year 1 Hand-Off — Capstone Due",'tasks'=>["Do Now & Clock In","Capstone: Year 1 Portfolio Build & Launch [100 pts]","Year 1 portfolio walkthrough: 3 minutes each","Year 1 reflection and one goal for Level 2","Exit Ticket"],'et'=>"present a completed Year 1 portfolio and reflect on program standards achieved.",'ms'=>['title'=>"Year 1 Portfolio Build & Launch",'pts'=>100]],
];

$dates = [
1=>'2026-08-18',2=>'2026-08-20',3=>'2026-08-24',4=>'2026-08-25',5=>'2026-08-27',6=>'2026-08-31',7=>'2026-09-01',8=>'2026-09-03',9=>'2026-09-08',10=>'2026-09-10',
11=>'2026-09-14',12=>'2026-09-10',13=>'2026-09-10',14=>'2026-09-14',15=>'2026-09-15',16=>'2026-09-17',17=>'2026-09-22',18=>'2026-09-24',19=>'2026-09-28',20=>'2026-09-29',
21=>'2026-10-01',22=>'2026-10-05',23=>'2026-10-06',24=>'2026-10-08',25=>'2026-10-13',26=>'2026-10-15',27=>'2026-10-19',28=>'2026-10-20',29=>'2026-10-22',30=>'2026-10-27',
31=>'2026-10-29',32=>'2026-11-03',33=>'2026-11-05',34=>'2026-11-10',35=>'2026-11-12',36=>'2026-11-16',37=>'2026-11-17',38=>'2026-11-19',39=>'2026-11-30',40=>'2026-12-01',
41=>'2026-12-03',42=>'2026-12-07',43=>'2026-12-08',44=>'2026-12-10',45=>'2027-01-05',46=>'2027-01-07',47=>'2027-01-11',48=>'2027-01-12',49=>'2027-01-14',50=>'2027-01-19',
51=>'2027-01-21',52=>'2027-01-25',53=>'2027-01-26',54=>'2027-01-28',55=>'2027-02-01',56=>'2027-02-02',57=>'2027-02-04',58=>'2027-02-09',59=>'2027-02-16',60=>'2027-02-18',
61=>'2027-02-22',62=>'2027-02-23',63=>'2027-02-25',64=>'2027-03-01',65=>'2027-03-02',66=>'2027-03-04',67=>'2027-03-08',68=>'2027-03-09',69=>'2027-03-11',70=>'2027-03-15',
71=>'2027-03-16',72=>'2027-03-18',73=>'2027-03-22',74=>'2027-03-23',75=>'2027-03-25',76=>'2027-04-06',77=>'2027-04-08',78=>'2027-04-12',79=>'2027-04-13',80=>'2027-04-15',
81=>'2027-04-19',82=>'2027-04-20',83=>'2027-04-22',84=>'2027-04-26',85=>'2027-04-27',86=>'2027-04-29',87=>'2027-05-03',88=>'2027-05-04',89=>'2027-05-06',90=>'2027-05-10',
91=>'2027-05-11',92=>'2027-05-13',93=>'2027-05-17',94=>'2027-05-18',95=>'2027-05-20',96=>'2027-05-25',97=>'2027-05-27',98=>'2027-06-01',
];

$db = getDB();
$db->query("CREATE TABLE IF NOT EXISTS agenda_content (course VARCHAR(20) NOT NULL, block_num INT NOT NULL, content LONGTEXT NOT NULL, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (course, block_num)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$db->query("CREATE TABLE IF NOT EXISTS agenda_schedule (course VARCHAR(20) NOT NULL, track VARCHAR(10) NOT NULL DEFAULT 'main', block_num INT NOT NULL, event_date DATE NOT NULL, PRIMARY KEY (course, track, block_num), KEY idx_lookup (course, track, event_date)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

$stmtC = $db->prepare("INSERT INTO agenda_content (course, block_num, content) VALUES (?,?,?) ON DUPLICATE KEY UPDATE content=VALUES(content)");
foreach ($blocks as $num => $b) {
    $content = ['chapterLabel'=>$b['ch'],'minimumDay'=>$b['min'],'objective'=>$b['obj'],'standards'=>$b['std'],'standardsNote'=>$b['stdNote'],'doNowType'=>$b['dnType'],'doNowPrompt'=>$b['dn'],'tasksTitle'=>$b['tt'],'tasksList'=>$b['tasks'],'exitTicket'=>$b['et'],'milestone'=>$b['ms']];
    $json = json_encode($content);
    $stmtC->bind_param('sis', $course, $num, $json);
    $stmtC->execute();
}
$stmtC->close();

$stmtS = $db->prepare("INSERT INTO agenda_schedule (course, track, block_num, event_date) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE event_date=VALUES(event_date)");
foreach ($dates as $num => $date) {
    $stmtS->bind_param('ssis', $course, $track, $num, $date);
    $stmtS->execute();
}
$stmtS->close();
$db->close();
echo "Seeded $course: " . count($blocks) . " content rows, " . count($dates) . " schedule rows\n";
