<?php
require_once __DIR__ . '/../db_config.php';
$course = 'cs_s1';

$blocks = [
1=>['ch'=>"Unit 0: Basic Computer Knowledge · Day 1 of 3",'min'=>false,'obj'=>["Set up every account and tool you will use this semester."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Predict','dn'=>"this class is self-paced with a test-out option. What is the biggest risk of that for you personally?",'tt'=>"Course Launch: How This Class Actually Works",'tasks'=>["Do Now & Clock In","Syllabus, clock-in rules, and the test-out policy","Accounts, Chromebook setup, and the class website","Exit Ticket"],'et'=>"set up every account and tool you will use this semester.",'ms'=>null],
2=>['ch'=>"Unit 0: Basic Computer Knowledge · Day 2 of 3",'min'=>false,'obj'=>["Design and develop artifacts working in team roles using collaborative tools."],'std'=>["9-12.AP.PD.4 Design and develop computational artifacts working in team roles using collaborative tools."],'stdNote'=>null,'dnType'=>'Predict','dn'=>"name one job that does NOT involve a document, a spreadsheet, or a slide deck.",'tt'=>"Office Software: The Tools You Will Actually Be Handed",'tasks'=>["Do Now & Clock In","Documents, spreadsheets, slides: what each is genuinely for","Cloud collaboration: comments, version history, and sharing","Lab: Create, Save & Open","Exit Ticket"],'et'=>"design and develop artifacts working in team roles using collaborative tools.",'ms'=>null],
3=>['ch'=>"Unit 0: Basic Computer Knowledge · Day 3 of 3",'min'=>true,'obj'=>["Work in a team role using shared collaborative tools."],'std'=>["9-12.AP.PD.4 Design and develop computational artifacts working in team roles using collaborative tools."],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"what is the difference between sharing a file and collaborating on one?",'tt'=>"Collaborating Without Chaos (Ch 0 assessment)",'tasks'=>["Do Now & Clock In","Team roles, shared ownership, and who breaks the document","Chapter 0 check for understanding","Exit Ticket"],'et'=>"work in a team role using shared collaborative tools.",'ms'=>null],
4=>['ch'=>"Unit 1: Digital Citizenship · Day 1 of 6",'min'=>false,'obj'=>["Demonstrate the everyday operating skills a workplace assumes you have."],'std'=>["9-12.DC.B.1"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"your teacher says \"attach the file.\" Where is it? Can you find it in under ten seconds?",'tt'=>"Essential Computer Skills: Files, Folders & Fluency",'tasks'=>["Do Now & Clock In","File systems, paths, search, and shortcuts that save real time","Hardware basics: what the parts do and what to call them","Lab: The File System Sprint","Exit Ticket"],'et'=>"demonstrate the everyday operating skills a workplace assumes you have.",'ms'=>null],
5=>['ch'=>"Unit 1: Digital Citizenship · Day 2 of 6",'min'=>false,'obj'=>["Apply systematic strategies to identify and fix common problems."],'std'=>["9-12.DC.B.2"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"name one shortcut from last class you will actually use again.",'tt'=>"Troubleshooting Like a Professional",'tasks'=>["Do Now & Clock In","Isolate, reproduce, test one change at a time","Writing a troubleshooting guide someone else could follow","Lab: The Fix-It Guide","Exit Ticket"],'et'=>"apply systematic strategies to identify and fix common problems.",'ms'=>null],
6=>['ch'=>"Unit 1: Digital Citizenship · Day 3 of 6",'min'=>true,'obj'=>["Explain the legal and ethical responsibilities that come with technology."],'std'=>["9-12.DC.A.1"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"you find a login left open on a school computer. What are your options, and what do you owe the person?",'tt'=>"Ethics, Privacy & The Law",'tasks'=>["Do Now & Clock In","Acceptable use, consent, and where your rights actually end","Copyright, licensing, and citing digital work","Exit Ticket"],'et'=>"explain the legal and ethical responsibilities that come with technology.",'ms'=>null],
7=>['ch'=>"Unit 1: Digital Citizenship · Day 4 of 6",'min'=>false,'obj'=>["Evaluate the long-term consequences of your online activity."],'std'=>["9-12.DC.D.1"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"name one thing you learned about acceptable use that surprised you.",'tt'=>"Your Digital Footprint",'tasks'=>["Do Now & Clock In","What a search for your name returns, and who is looking","Permanence: screenshots, archives, and the myth of deleting","Lab: The Footprint Audit","Exit Ticket"],'et'=>"evaluate the long-term consequences of your online activity.",'ms'=>null],
8=>['ch'=>"Unit 1: Digital Citizenship · Day 5 of 6",'min'=>false,'obj'=>["Give examples to illustrate how sensitive data can be affected by malware and other attacks."],'std'=>["9-12.NI.C.1 Give examples to illustrate how sensitive data can be affected by malware and other attacks."],'stdNote'=>null,'dnType'=>'Predict','dn'=>"how do most people actually get hacked? Guess before we look at the data.",'tt'=>"Cybersecurity Threats: How Data Actually Gets Stolen",'tasks'=>["Do Now & Clock In","Phishing, malware, ransomware, and social engineering","Real breaches: what got in, and what it cost","Lab: The Threat Teardown","Exit Ticket"],'et'=>"give examples to illustrate how sensitive data can be affected by malware and other attacks.",'ms'=>null],
9=>['ch'=>"Unit 1: Digital Citizenship · Day 6 of 6",'min'=>false,'obj'=>["Demonstrate mastery of digital citizenship and threat awareness."],'std'=>["9-12.NI.C.1 Give examples to illustrate how sensitive data can be affected by malware and other attacks."],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"which of the four attack types would fool you? Be honest — that is the one to study.",'tt'=>"Unit 1 Checkpoint (Ch 1–3 assessment)",'tasks'=>["Do Now & Clock In","Unit 1 assessment","Reteach the two lowest-scoring standards","Exit Ticket"],'et'=>"demonstrate mastery of digital citizenship and threat awareness.",'ms'=>null],
10=>['ch'=>"Unit 2: Computing Systems · Day 1 of 4",'min'=>false,'obj'=>["Explain how abstractions hide the underlying implementation details of computing systems."],'std'=>["9-12.CS.D.1 Explain how abstractions hide the underlying implementation details of computing systems embedded in everyday objects."],'stdNote'=>null,'dnType'=>'Predict','dn'=>"you press a key and a letter appears. Roughly how many layers are between those two events?",'tt'=>"How Computers Work: Abstraction",'tasks'=>["Do Now & Clock In","Abstraction: why you do not have to think about electrons","Input, processing, storage, output — traced end to end","Exit Ticket"],'et'=>"explain how abstractions hide the underlying implementation details of computing systems.",'ms'=>null],
11=>['ch'=>"Unit 2: Computing Systems · Day 2 of 4",'min'=>true,'obj'=>["Compare levels of abstraction and interactions between application software, system software, and hardware."],'std'=>["9-12.CS.HS.1 Compare levels of abstraction and interactions between application software, system software, and hardware layers."],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"name one thing an abstraction hides from you, and one cost of that.",'tt'=>"Hardware, Software & The Layers Between",'tasks'=>["Do Now & Clock In","Applications, operating system, firmware, hardware","What actually happens when a program crashes","Lab: The Layer Map","Exit Ticket"],'et'=>"compare levels of abstraction and interactions between application software, system software, and hardware.",'ms'=>null],
12=>['ch'=>"Unit 2: Computing Systems · Day 3 of 4",'min'=>false,'obj'=>["Translate between different bit representations of real-world phenomena."],'std'=>["9-12.DA.S.1 Translate between different bit representations of real-world phenomena, such as characters, numbers, and images (e.g., convert hexadecimal colors to decimal percentages, ASCII/Unicode representation)."],'stdNote'=>null,'dnType'=>'Predict','dn'=>"a computer only stores 0s and 1s. How does it store the letter A? Or a photo?",'tt'=>"The Language of Computers: Binary",'tasks'=>["Do Now & Clock In","Counting in binary and converting by hand","Bits to characters, colors, and sound","Lab: The Binary Translator","Exit Ticket"],'et'=>"translate between different bit representations of real-world phenomena.",'ms'=>null],
13=>['ch'=>"Unit 2: Computing Systems · Day 4 of 4",'min'=>false,'obj'=>["Represent text, numbers, images, and sound as bits."],'std'=>["9-12.DA.S.1 Translate between different bit representations of real-world phenomena, such as characters, numbers, and images (e.g., convert hexadecimal colors to decimal percentages, ASCII/Unicode representation)."],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"convert 1101 to decimal without looking. What did you do first?",'tt'=>"Representing the Real World (Ch 4–5 assessment)",'tasks'=>["Do Now & Clock In","Hex, RGB, and why file sizes are what they are","Unit 2 assessment","Exit Ticket"],'et'=>"represent text, numbers, images, and sound as bits.",'ms'=>null],
14=>['ch'=>"Unit 3: Data & Analysis · Day 1 of 7",'min'=>false,'obj'=>["Evaluate the tradeoffs in how data elements are organized and where data is stored."],'std'=>["9-12.DA.S.2 Evaluate the tradeoffs in how data elements are organized and where data is stored."],'stdNote'=>null,'dnType'=>'Predict','dn'=>"local drive, external drive, or cloud. Name one thing each is better at.",'tt'=>"Storing Data: Where It Goes and What It Costs",'tasks'=>["Do Now & Clock In","Local vs. network vs. cloud: speed, cost, risk, access","File formats and what you lose in each","Exit Ticket"],'et'=>"evaluate the tradeoffs in how data elements are organized and where data is stored.",'ms'=>null],
15=>['ch'=>"Unit 3: Data & Analysis · Day 2 of 7",'min'=>false,'obj'=>["Evaluate tradeoffs in data organization."],'std'=>["9-12.DA.S.2 Evaluate the tradeoffs in how data elements are organized and where data is stored."],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"name one tradeoff of storing everything in the cloud.",'tt'=>"Organizing Data So You Can Find It Later",'tasks'=>["Do Now & Clock In","Naming conventions, folder depth, and metadata","Backups: the 3-2-1 rule and why people ignore it","Lab: The Storage Tradeoff Brief","Exit Ticket"],'et'=>"evaluate tradeoffs in data organization.",'ms'=>null],
16=>['ch'=>"Unit 3: Data & Analysis · Day 3 of 7",'min'=>true,'obj'=>["Use software tools to organize and calculate over real data."],'std'=>["9-12.DA.CVT.1 Create interactive data visualizations or alternative representations using software tools to help others better understand real-world phenomena."],'stdNote'=>null,'dnType'=>'Predict','dn'=>"you have 500 rows of numbers. How long should it take to find the average?",'tt'=>"Mastering Spreadsheets: Formulas",'tasks'=>["Do Now & Clock In","Cells, ranges, absolute vs. relative references","SUM, AVERAGE, COUNT, MIN, MAX, and IF","Lab: The Formula Sprint","Exit Ticket"],'et'=>"use software tools to organize and calculate over real data.",'ms'=>null],
17=>['ch'=>"Unit 3: Data & Analysis · Day 4 of 7",'min'=>false,'obj'=>["Transform messy data into something you can actually analyze."],'std'=>["9-12.DA.CVT.1 Create interactive data visualizations or alternative representations using software tools to help others better understand real-world phenomena."],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"what does an absolute reference do, and when do you need one?",'tt'=>"Spreadsheets: Sorting, Filtering & Cleaning",'tasks'=>["Do Now & Clock In","Sorting, filtering, conditional formatting, and find/replace","Dirty data: duplicates, blanks, and inconsistent entries","Lab: The Data Cleanup","Exit Ticket"],'et'=>"transform messy data into something you can actually analyze.",'ms'=>null],
18=>['ch'=>"Unit 3: Data & Analysis · Day 5 of 7",'min'=>false,'obj'=>["Create interactive data visualizations or alternative representations to help others understand real phenomena."],'std'=>["9-12.DA.CVT.1 Create interactive data visualizations or alternative representations using software tools to help others better understand real-world phenomena."],'stdNote'=>null,'dnType'=>'Predict','dn'=>"same data, two different charts. Can one of them lie without being wrong?",'tt'=>"Creating Interactive Data Visualizations",'tasks'=>["Do Now & Clock In","Choosing a chart type that matches the question","Misleading axes, cherry-picked ranges, and honest labeling","Lab: The Visualization Build","Exit Ticket"],'et'=>"create interactive data visualizations or alternative representations to help others understand real phenomena.",'ms'=>null],
19=>['ch'=>"Unit 3: Data & Analysis · Day 6 of 7",'min'=>true,'obj'=>["Create computational models that represent relationships among data elements."],'std'=>["9-12.DA.IM.1 Create computational models that represent the relationships among different elements of data collected from a phenomenon, process, or model."],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"name one chart type you would never use for comparison, and why.",'tt'=>"Computational Modeling",'tasks'=>["Do Now & Clock In","Building a model: inputs, rules, outputs","What-if analysis and testing an assumption","Lab: The Model Build","Exit Ticket"],'et'=>"create computational models that represent relationships among data elements.",'ms'=>null],
20=>['ch'=>"Unit 3: Data & Analysis · Day 7 of 7",'min'=>false,'obj'=>["Demonstrate mastery of data storage, analysis, and modeling."],'std'=>["9-12.DA.IM.1 Create computational models that represent the relationships among different elements of data collected from a phenomenon, process, or model."],'stdNote'=>null,'dnType'=>'Predict','dn'=>"what will your model do if you feed it a number nobody expected?",'tt'=>"Unit 3 Checkpoint (Ch 6–8 assessment)",'tasks'=>["Do Now & Clock In","Unit 3 assessment","Reteach the two lowest-scoring standards","Exit Ticket"],'et'=>"demonstrate mastery of data storage, analysis, and modeling.",'ms'=>null],
21=>['ch'=>"Unit 4: Beginning Algorithms & Programming · Day 1 of 9",'min'=>false,'obj'=>["Create prototypes that use algorithms to solve computational problems."],'std'=>["9-12.AP.A.1 Create prototypes that use algorithms to solve computational problems by leveraging prior student knowledge and personal interests."],'stdNote'=>null,'dnType'=>'Predict','dn'=>"describe how to make a sandwich so precisely that a robot could not get it wrong.",'tt'=>"Problem Solving: Thinking Before Typing",'tasks'=>["Do Now & Clock In","Decomposition, pattern finding, abstraction, algorithms","Pseudocode and flowcharts before any code","Lab: The Algorithm Draft","Exit Ticket"],'et'=>"create prototypes that use algorithms to solve computational problems.",'ms'=>null],
22=>['ch'=>"Unit 4: Beginning Algorithms & Programming · Day 2 of 9",'min'=>false,'obj'=>["Build a working prototype from a problem you care about."],'std'=>["9-12.AP.A.1 Create prototypes that use algorithms to solve computational problems by leveraging prior student knowledge and personal interests."],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"where did your sandwich instructions break down?",'tt'=>"Building Your First Algorithm",'tasks'=>["Do Now & Clock In","From pseudocode to working steps","Tracing an algorithm by hand to find the bug","Lab: The Prototype Build","Exit Ticket"],'et'=>"build a working prototype from a problem you care about.",'ms'=>null],
23=>['ch'=>"Unit 4: Beginning Algorithms & Programming · Day 3 of 9",'min'=>false,'obj'=>["Test a prototype against cases you did not design for."],'std'=>["9-12.AP.A.1 Create prototypes that use algorithms to solve computational problems by leveraging prior student knowledge and personal interests."],'stdNote'=>null,'dnType'=>'Predict','dn'=>"your algorithm works on your example. Name one input that will break it.",'tt'=>"Testing & Refining an Algorithm (Ch 9 assessment)",'tasks'=>["Do Now & Clock In","Edge cases, invalid input, and the empty case","Chapter 9 check for understanding","Exit Ticket"],'et'=>"test a prototype against cases you did not design for.",'ms'=>null],
24=>['ch'=>"Unit 4: Beginning Algorithms & Programming · Day 4 of 9",'min'=>true,'obj'=>["Justify the selection of specific control structures when tradeoffs involve readability and performance."],'std'=>["9-12.AP.C.1 Justify the selection of specific control structures when tradeoffs involve implementation, readability, and program performance, and explain the benefits and drawbacks of choices made."],'stdNote'=>null,'dnType'=>'Predict','dn'=>"a program has to do something 1,000 times. Do you write it 1,000 times?",'tt'=>"Control Structures: Making Decisions",'tasks'=>["Do Now & Clock In","Sequence, selection, repetition","if/else, and choosing between a loop and a conditional","Lab: The Decision Tree","Exit Ticket"],'et'=>"justify the selection of specific control structures when tradeoffs involve readability and performance.",'ms'=>null],
25=>['ch'=>"Unit 4: Beginning Algorithms & Programming · Day 5 of 9",'min'=>false,'obj'=>["Explain the benefits and drawbacks of the control structures you chose."],'std'=>["9-12.AP.C.1 Justify the selection of specific control structures when tradeoffs involve implementation, readability, and program performance, and explain the benefits and drawbacks of choices made."],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"name one thing that is easier to read but slower to run.",'tt'=>"Loops & The Tradeoffs You Are Making",'tasks'=>["Do Now & Clock In","Counted vs. conditional loops, and infinite loop traps","Readability vs. performance: defending your choice","Lab: The Loop Lab","Exit Ticket"],'et'=>"explain the benefits and drawbacks of the control structures you chose.",'ms'=>null],
26=>['ch'=>"Unit 4: Beginning Algorithms & Programming · Day 6 of 9",'min'=>false,'obj'=>["Design and iteratively develop computational artifacts using events to initiate instructions."],'std'=>["9-12.AP.C.2 Design and iteratively develop computational artifacts for practical intent, personal expression, or to address a societal issue by using events to initiate instructions."],'stdNote'=>null,'dnType'=>'Predict','dn'=>"a program that runs top to bottom and stops. What can it never do?",'tt'=>"Events: Programs That Respond",'tasks'=>["Do Now & Clock In","Event-driven thinking: waiting instead of running","Building something that reacts to a user","Lab: The Event Build","Exit Ticket"],'et'=>"design and iteratively develop computational artifacts using events to initiate instructions.",'ms'=>null],
27=>['ch'=>"Unit 4: Beginning Algorithms & Programming · Day 7 of 9",'min'=>false,'obj'=>["Decompose problems into smaller components through systematic analysis."],'std'=>["9-12.AP.M.1 Decompose problems into smaller components through systematic analysis, using constructs such as procedures, modules, and/or objects."],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"name one thing your event program does that a linear program could not.",'tt'=>"Modularity: Breaking Big Problems Apart",'tasks'=>["Do Now & Clock In","Procedures, modules, and objects as containers for logic","Why one 300-line block is a maintenance disaster","Lab: The Decomposition Lab","Exit Ticket"],'et'=>"decompose problems into smaller components through systematic analysis.",'ms'=>null],
28=>['ch'=>"Unit 4: Beginning Algorithms & Programming · Day 8 of 9",'min'=>false,'obj'=>["Create artifacts by using procedures within a program."],'std'=>["9-12.AP.M.2 Create artifacts by using procedures within a program, combinations of data and procedures, or independent but interrelated programs."],'stdNote'=>null,'dnType'=>'Predict','dn'=>"you wrote the same eight lines in four places. What is about to go wrong?",'tt'=>"Writing & Reusing Procedures",'tasks'=>["Do Now & Clock In","Parameters, return values, and naming things well","Refactoring: same behavior, less code","Lab: The Procedure Refactor","Exit Ticket"],'et'=>"create artifacts by using procedures within a program.",'ms'=>null],
29=>['ch'=>"Unit 4: Beginning Algorithms & Programming · Day 9 of 9",'min'=>false,'obj'=>["Demonstrate mastery of algorithms, control structures, and modularity."],'std'=>["9-12.AP.M.2 Create artifacts by using procedures within a program, combinations of data and procedures, or independent but interrelated programs."],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"what is the difference between a parameter and a return value?",'tt'=>"Unit 4 Checkpoint (Ch 9–11 assessment)",'tasks'=>["Do Now & Clock In","Unit 4 assessment","Reteach the two lowest-scoring standards","Exit Ticket"],'et'=>"demonstrate mastery of algorithms, control structures, and modularity.",'ms'=>null],
30=>['ch'=>"Unit 5: Impacts of Computing · Day 1 of 4",'min'=>false,'obj'=>["Test and refine computational artifacts to reduce bias and equity deficits."],'std'=>["9-12.IC.C.2 Test and refine computational artifacts to reduce bias and equity deficits."],'stdNote'=>null,'dnType'=>'Predict','dn'=>"a soap dispenser does not detect some people's hands. How does that happen?",'tt'=>"Culture, Equity & Bias in Computing",'tasks'=>["Do Now & Clock In","Who was in the room when the system was designed","Real cases: facial recognition, hiring tools, medical algorithms","Lab: The Bias Audit","Exit Ticket"],'et'=>"test and refine computational artifacts to reduce bias and equity deficits.",'ms'=>null],
31=>['ch'=>"Unit 5: Impacts of Computing · Day 2 of 4",'min'=>false,'obj'=>["Test and refine an artifact so it serves more people."],'std'=>["9-12.IC.C.2 Test and refine computational artifacts to reduce bias and equity deficits."],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"name one assumption a designer made that excluded someone.",'tt'=>"Refining an Artifact to Reduce Bias (Ch 12 assessment)",'tasks'=>["Do Now & Clock In","Testing with people unlike yourself","Chapter 12 check for understanding","Exit Ticket"],'et'=>"test and refine an artifact so it serves more people.",'ms'=>null],
32=>['ch'=>"Unit 5: Impacts of Computing · Day 3 of 4",'min'=>false,'obj'=>["Evaluate the ways computing impacts personal, ethical, social, economic, and cultural practices."],'std'=>["9-12.IC.C.1 Evaluate the ways computing impacts personal, ethical, social, economic, and cultural practices.","9-12.IC.SLE.1 Explain the beneficial and harmful effects that intellectual property laws can have on innovation."],'stdNote'=>null,'dnType'=>'Predict','dn'=>"name one job that exists today because of computing, and one it erased.",'tt'=>"How Computing Changes Society",'tasks'=>["Do Now & Clock In","Economic and cultural shifts, both directions","Intellectual property law: what it protects and what it blocks","Exit Ticket"],'et'=>"evaluate the ways computing impacts personal, ethical, social, economic, and cultural practices.",'ms'=>null],
33=>['ch'=>"Unit 5: Impacts of Computing · Day 4 of 4",'min'=>true,'obj'=>["Explain privacy concerns related to automated data collection and evaluate their implications."],'std'=>["9-12.IC.SLE.2 Explain the privacy concerns related to the collection and generation of data through automated processes that may not be evident to users.","9-12.IC.SLE.3 Evaluate the social and economic implications of privacy in the context of safety, law, or ethics."],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"name one benefit and one harm of the same piece of technology.",'tt'=>"Privacy, Data Collection & The Law (Ch 13 assessment)",'tasks'=>["Do Now & Clock In","What gets collected automatically, and by whom","Safety vs. privacy: the tradeoff nobody solves cleanly","Unit 5 assessment","Exit Ticket"],'et'=>"explain privacy concerns related to automated data collection and evaluate their implications.",'ms'=>null],
34=>['ch'=>"Unit 6: Intermediate Algorithms & Programming · Day 1 of 4",'min'=>false,'obj'=>["Demonstrate the use of arrays to generalize computational problems."],'std'=>["9-12.AP.V.1 Demonstrate the use of both linked lists and arrays to simplify solutions, generalizing computational problems instead of repeatedly using simple variables."],'stdNote'=>null,'dnType'=>'Predict','dn'=>"you need to store 200 student names. How many variables should you create?",'tt'=>"Advanced Data Structures: Arrays",'tasks'=>["Do Now & Clock In","Arrays: one name, many values, and an index","Looping an array instead of repeating yourself","Lab: The Array Lab","Exit Ticket"],'et'=>"demonstrate the use of arrays to generalize computational problems.",'ms'=>null],
35=>['ch'=>"Unit 6: Intermediate Algorithms & Programming · Day 2 of 4",'min'=>false,'obj'=>["Demonstrate the use of both linked lists and arrays to simplify solutions."],'std'=>["9-12.AP.V.1 Demonstrate the use of both linked lists and arrays to simplify solutions, generalizing computational problems instead of repeatedly using simple variables."],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"what is the index of the first item in an array, and why that number?",'tt'=>"Linked Lists & Choosing a Structure (Ch 14 assessment)",'tasks'=>["Do Now & Clock In","Linked lists: what they cost and what they buy you","Choosing between an array and a list, with a reason","Exit Ticket"],'et'=>"demonstrate the use of both linked lists and arrays to simplify solutions.",'ms'=>null],
36=>['ch'=>"Unit 6: Intermediate Algorithms & Programming · Day 3 of 4",'min'=>true,'obj'=>["Systematically design and develop programs for broad audiences by incorporating user feedback."],'std'=>["9-12.AP.PD.1 Systematically design and develop programs for broad audiences by incorporating feedback from users."],'stdNote'=>null,'dnType'=>'Predict','dn'=>"you build exactly what a client asked for and they hate it. What went wrong?",'tt'=>"The Software Development Lifecycle",'tasks'=>["Do Now & Clock In","Plan, design, build, test, deploy, maintain","Getting user feedback before you are finished","Lab: The Feedback Round","Exit Ticket"],'et'=>"systematically design and develop programs for broad audiences by incorporating user feedback.",'ms'=>null],
37=>['ch'=>"Unit 6: Intermediate Algorithms & Programming · Day 4 of 4",'min'=>false,'obj'=>["Work in team roles using collaborative tools and document design decisions."],'std'=>["9-12.AP.PD.4 Design and develop computational artifacts working in team roles using collaborative tools.","9-12.AP.PD.5 Document design decisions using text, graphics, presentations, and/or demonstrations in the development of complex programs."],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"name one thing a user told you that you did not want to hear.",'tt'=>"Team Roles & Documentation (Ch 15 assessment)",'tasks'=>["Do Now & Clock In","Splitting work without stepping on each other","Documenting decisions so the next person understands why","Unit 6 assessment","Exit Ticket"],'et'=>"work in team roles using collaborative tools and document design decisions.",'ms'=>null],
38=>['ch'=>"Unit 7: Networks & The Internet · Day 1 of 4",'min'=>false,'obj'=>["Describe the relationship between routers, switches, servers, and topology."],'std'=>["9-12.NI.NCO.1 Evaluate the scalability and reliability of networks, by describing the relationship between routers, switches, servers, topology, and addressing."],'stdNote'=>null,'dnType'=>'Predict','dn'=>"you load a page. How many machines touched that request before it reached you?",'tt'=>"How the Internet Actually Works",'tasks'=>["Do Now & Clock In","Packets, routers, switches, servers, and DNS","Tracing a real route from this room to another country","Lab: The Route Trace","Exit Ticket"],'et'=>"describe the relationship between routers, switches, servers, and topology.",'ms'=>null],
39=>['ch'=>"Unit 7: Networks & The Internet · Day 2 of 4",'min'=>true,'obj'=>["Evaluate the scalability and reliability of networks."],'std'=>["9-12.NI.NCO.1 Evaluate the scalability and reliability of networks, by describing the relationship between routers, switches, servers, topology, and addressing."],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"name one thing that has to work for this page to load, that you never think about.",'tt'=>"Scalability & Reliability (Ch 16 assessment)",'tasks'=>["Do Now & Clock In","What breaks when a million people show up at once","Redundancy, bandwidth, and single points of failure","Exit Ticket"],'et'=>"evaluate the scalability and reliability of networks.",'ms'=>null],
40=>['ch'=>"Unit 7: Networks & The Internet · Day 3 of 4",'min'=>false,'obj'=>["Recommend security measures based on efficiency, feasibility, and ethical impact."],'std'=>["9-12.NI.C.2 Recommend security measures to address various scenarios based on factors such as efficiency, feasibility, and ethical impacts."],'stdNote'=>null,'dnType'=>'Predict','dn'=>"the most secure system is one nobody can use. What is the real goal, then?",'tt'=>"Defending Systems: Choosing Security Measures",'tasks'=>["Do Now & Clock In","Authentication, encryption, firewalls, and access control","Recommending a measure for a specific scenario","Lab: The Security Recommendation","Exit Ticket"],'et'=>"recommend security measures based on efficiency, feasibility, and ethical impact.",'ms'=>null],
41=>['ch'=>"Unit 7: Networks & The Internet · Day 4 of 4",'min'=>false,'obj'=>["Compare security measures and explain the tradeoffs in implementing them."],'std'=>["9-12.NI.C.3 Compare various security measures, considering tradeoffs between the usability and security of a computing system.","9-12.NI.C.4 Explain tradeoffs when selecting and implementing cybersecurity recommendations."],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"name one security measure people bypass because it is annoying.",'tt'=>"Security Tradeoffs (Ch 17 assessment)",'tasks'=>["Do Now & Clock In","Usability vs. security, cost vs. risk","Unit 7 assessment","Exit Ticket"],'et'=>"compare security measures and explain the tradeoffs in implementing them.",'ms'=>null],
42=>['ch'=>"Unit 8: Artificial Intelligence · Day 1 of 3",'min'=>true,'obj'=>["Demonstrate ways a given algorithm applies to problems across disciplines."],'std'=>["9-12.IC.C.3 Demonstrate ways a given algorithm applies to problems across disciplines."],'stdNote'=>null,'dnType'=>'Predict','dn'=>"the same algorithm that recommends music also does something in medicine. What?",'tt'=>"Algorithms Across Disciplines",'tasks'=>["Do Now & Clock In","Pattern matching in music, medicine, farming, and finance","One algorithm, four industries","Lab: The Cross-Discipline Map","Exit Ticket"],'et'=>"demonstrate ways a given algorithm applies to problems across disciplines.",'ms'=>null],
43=>['ch'=>"Unit 8: Artificial Intelligence · Day 2 of 3",'min'=>false,'obj'=>["Explain the potential impacts of artificial intelligence on society."],'std'=>["9-12.IC.C.4 Explain the potential impacts of artificial intelligence on society."],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"name one field you did not expect to be using algorithms.",'tt'=>"The Impact of AI on Society",'tasks'=>["Do Now & Clock In","What AI is genuinely good at, and what it is sold as","Jobs, bias, energy cost, and who is accountable","Lab: The AI Impact Brief","Exit Ticket"],'et'=>"explain the potential impacts of artificial intelligence on society.",'ms'=>null],
44=>['ch'=>"Unit 8: Artificial Intelligence · Day 3 of 3",'min'=>false,'obj'=>["Demonstrate mastery across all nine units."],'std'=>["9-12.IC.C.4 Explain the potential impacts of artificial intelligence on society."],'stdNote'=>null,'dnType'=>'','dn'=>"Two minutes of silent review. Then everything goes away.",'tt'=>"Final Exam & Course Wrap",'tasks'=>["Clock In","Semester Final Exam","Course reflection and what to take into your next CS class","Exit Ticket"],'et'=>"demonstrate mastery across all nine units.",'ms'=>null],
];

$datesA = [
1=>'2026-08-18',2=>'2026-08-20',3=>'2026-08-24',4=>'2026-08-25',5=>'2026-08-27',6=>'2026-08-31',7=>'2026-09-01',8=>'2026-09-03',9=>'2026-09-08',10=>'2026-09-10',
11=>'2026-09-14',12=>'2026-09-15',13=>'2026-09-17',14=>'2026-09-22',15=>'2026-09-24',16=>'2026-09-28',17=>'2026-09-29',18=>'2026-10-01',19=>'2026-10-05',20=>'2026-10-06',
21=>'2026-10-08',22=>'2026-10-13',23=>'2026-10-15',24=>'2026-10-19',25=>'2026-10-20',26=>'2026-10-22',27=>'2026-10-27',28=>'2026-10-29',29=>'2026-11-03',30=>'2026-11-05',
31=>'2026-11-10',32=>'2026-11-12',33=>'2026-11-16',34=>'2026-11-17',35=>'2026-11-19',36=>'2026-11-30',37=>'2026-12-01',38=>'2026-12-03',39=>'2026-12-07',40=>'2026-12-08',
41=>'2026-12-10',42=>'2026-12-14',43=>'2026-12-15',44=>'2026-12-17',
];

$datesB = [
1=>'2026-08-19',2=>'2026-08-21',3=>'2026-08-24',4=>'2026-08-26',5=>'2026-08-28',6=>'2026-08-31',7=>'2026-09-02',8=>'2026-09-04',9=>'2026-09-09',10=>'2026-09-11',
11=>'2026-09-14',12=>'2026-09-16',13=>'2026-09-18',14=>'2026-09-23',15=>'2026-09-25',16=>'2026-09-28',17=>'2026-09-30',18=>'2026-10-02',19=>'2026-10-05',20=>'2026-10-07',
21=>'2026-10-09',22=>'2026-10-14',23=>'2026-10-16',24=>'2026-10-19',25=>'2026-10-21',26=>'2026-10-23',27=>'2026-10-26',28=>'2026-10-28',29=>'2026-11-04',30=>'2026-11-06',
31=>'2026-11-09',32=>'2026-11-13',33=>'2026-11-16',34=>'2026-11-18',35=>'2026-11-20',36=>'2026-11-30',37=>'2026-12-01',38=>'2026-12-03',39=>'2026-12-07',40=>'2026-12-08',
41=>'2026-12-09',42=>'2026-12-14',43=>'2026-12-15',44=>'2026-12-17',
];

$db = getDB();
$db->query("CREATE TABLE IF NOT EXISTS agenda_content (course VARCHAR(20) NOT NULL, block_num INT NOT NULL, content LONGTEXT NOT NULL, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (course, block_num)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$db->query("CREATE TABLE IF NOT EXISTS agenda_schedule (course VARCHAR(20) NOT NULL, track VARCHAR(10) NOT NULL DEFAULT 'main', block_num INT NOT NULL, event_date DATE NOT NULL, PRIMARY KEY (course, track, block_num), KEY idx_lookup (course, track, event_date)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

$stmtC = $db->prepare("INSERT INTO agenda_content (course, block_num, content) VALUES (?,?,?) ON DUPLICATE KEY UPDATE content=VALUES(content)");
foreach ($blocks as $num => $b) {
    $content = ['chapterLabel'=>$b['ch'],'minimumDay'=>$b['min'],'objective'=>$b['obj'],'standards'=>$b['std'],'standardsNote'=>$b['stdNote'],'doNowType'=>$b['dnType'],'doNowPrompt'=>$b['dn'],'tasksTitle'=>$b['tt'],'tasksList'=>$b['tasks'],'exitTicket'=>$b['et'],'milestone'=>$b['ms']];
    $json = json_encode($content);
    $stmtC->bind_param('sis', $course, $num, $json);
    $stmtC->execute();
}
$stmtC->close();

$stmtS = $db->prepare("INSERT INTO agenda_schedule (course, track, block_num, event_date) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE event_date=VALUES(event_date)");
foreach (['A' => $datesA, 'B' => $datesB] as $track => $dates) {
    foreach ($dates as $num => $date) {
        $stmtS->bind_param('ssis', $course, $track, $num, $date);
        $stmtS->execute();
    }
}
$stmtS->close();
$db->close();
echo "Seeded $course: " . count($blocks) . " content rows, " . (count($datesA) + count($datesB)) . " schedule rows (A+B)\n";
