<?php
require_once __DIR__ . '/../db_config.php';
$course = 'wd2';
$track = 'main';

$blocks = [
1=>['ch'=>"Boot Camp: Year 1 Recertification · Day 1 of 5",'min'=>false,'obj'=>["Re-establish the Agency standards you will be held to all year."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Predict','dn'=>"what is the one thing from Level 1 you have most forgotten over the summer? Be honest.",'tt'=>"Welcome Back to the Agency (45 min)",'tasks'=>["Do Now & Clock In","Level 2 syllabus, accounts, and the Year 2 folder structure","Diagnostic: 20 questions across all of Level 1","Exit Ticket"],'et'=>"re-establish the Agency standards you will be held to all year.",'ms'=>null],
2=>['ch'=>"Boot Camp: Year 1 Recertification · Day 2 of 5",'min'=>false,'obj'=>["Rebuild a semantic, validated page from memory."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Reflect','dn'=>"your diagnostic is scored. Which Level 1 topic did you lose the most points on?",'tt'=>"HTML & CSS Recertification",'tasks'=>["Do Now & Clock In","Semantic landmarks, headings, and accessible forms","Selectors, specificity, and the box model","Lab: The Recertification Rebuild","Exit Ticket"],'et'=>"rebuild a semantic, validated page from memory.",'ms'=>null],
3=>['ch'=>"Boot Camp: Year 1 Recertification · Day 3 of 5",'min'=>true,'obj'=>["Rebuild a responsive layout and optimize a media set."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Predict','dn'=>"you have 20 minutes to make a page work on a phone. What do you do first?",'tt'=>"Layout & Media Recertification",'tasks'=>["Do Now & Clock In","Flexbox, Grid, and content-driven breakpoints","Image formats, srcset, captions, and transcripts","Lab: The Responsive Retest","Exit Ticket"],'et'=>"rebuild a responsive layout and optimize a media set.",'ms'=>null],
4=>['ch'=>"Boot Camp: Year 1 Recertification · Day 4 of 5",'min'=>false,'obj'=>["Rebuild the interactive logic you learned at the end of Level 1."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Reflect','dn'=>"name the three cases every conditional should cover.",'tt'=>"JavaScript Recertification (45 min)",'tasks'=>["Do Now & Clock In","Variables, functions, conditionals, events, and the DOM","Lab: The Logic Retest","Exit Ticket"],'et'=>"rebuild the interactive logic you learned at the end of Level 1.",'ms'=>null],
5=>['ch'=>"Boot Camp: Year 1 Recertification · Day 5 of 5",'min'=>false,'obj'=>["Prove Level 1 mastery and stand up your Level 2 toolchain."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Predict','dn'=>"what will be the hardest thing about Level 2 compared to Level 1?",'tt'=>"Boot Camp Assessment & Environment Setup",'tasks'=>["Do Now & Clock In","Boot Camp summative and item analysis","Reteach the two lowest-scoring standards","VS Code, Live Server, and the Year 2 repo","Exit Ticket"],'et'=>"prove Level 1 mastery and stand up your Level 2 toolchain.",'ms'=>null],
6=>['ch'=>"Chapter 10: The Game Developer · Day 1 of 9",'min'=>true,'obj'=>["Explain why a client would pay for an interactive experience."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Predict','dn'=>"a client says \"nobody reads our website.\" What could you build instead of more text?",'tt'=>"Agency Gamification & Meet Gamer Gabe",'tasks'=>["Do Now & Clock In","Time-on-page: static content vs. an interactive feature","Meet Gamer Gabe and the brief for this chapter","Exit Ticket"],'et'=>"explain why a client would pay for an interactive experience.",'ms'=>null],
7=>['ch'=>"Chapter 10: The Game Developer · Day 2 of 9",'min'=>false,'obj'=>["Enhance interactivity of websites using current scripting trends."],'std'=>["NV 5.3.4 Enhance interactivity of websites using current scripting trends"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"in math class (0,0) is the center. Where is (0,0) on a screen, and why there?",'tt'=>"The Canvas API & Coordinates",'tasks'=>["Do Now & Clock In","Whiteboard coordinate grid: plotting by hand first","getContext(\"2d\"), fillStyle, and fillRect","Lab 1: Canvas Coordinate Art Lab","Exit Ticket"],'et'=>"enhance interactivity of websites using current scripting trends.",'ms'=>null],
8=>['ch'=>"Chapter 10: The Game Developer · Day 3 of 9",'min'=>false,'obj'=>["Implement a continuous animation loop."],'std'=>["NV 5.3.4 Enhance interactivity of websites using current scripting trends"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"if you increase an object's Y value, which way does it move?",'tt'=>"Animation & The Game Loop (45 min)",'tasks'=>["Do Now & Clock In","Clear, update, draw — and requestAnimationFrame","Lab 2: The Bouncing Box Lab","Exit Ticket"],'et'=>"implement a continuous animation loop.",'ms'=>null],
9=>['ch'=>"Chapter 10: The Game Developer · Day 4 of 9",'min'=>false,'obj'=>["Enhance interactivity using object-oriented scripting patterns."],'std'=>["NV 5.3.4 Enhance interactivity of websites using current scripting trends"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"you need 50 enemies with the same behavior. Should you write 50 objects by hand?",'tt'=>"Objects, Classes & The Blueprint",'tasks'=>["Do Now & Clock In","Class, constructor, properties, methods, and this","PascalCase, camelCase, and why naming matters at scale","Exit Ticket"],'et'=>"enhance interactivity using object-oriented scripting patterns.",'ms'=>null],
10=>['ch'=>"Chapter 10: The Game Developer · Day 5 of 9",'min'=>false,'obj'=>["Generate and manage many game objects from one blueprint."],'std'=>["NV 5.3.4 Enhance interactivity of websites using current scripting trends"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"what is the difference between a class and an instance?",'tt'=>"Building the Entity Factory",'tasks'=>["Do Now & Clock In","Instantiating with new and storing entities in an array","extends and super(): sharing behavior between entities","Lab 3: The Entity Factory","Exit Ticket"],'et'=>"generate and manage many game objects from one blueprint.",'ms'=>null],
11=>['ch'=>"Chapter 10: The Game Developer · Day 6 of 9",'min'=>true,'obj'=>["Implement collision detection and keyboard control."],'std'=>["NV 5.3.4 Enhance interactivity of websites using current scripting trends"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"how does a computer know two rectangles are touching? Say the rule in plain English.",'tt'=>"Physics, Collisions & User Input",'tasks'=>["Do Now & Clock In","AABB collision, proved on paper before it is coded","Held-key state objects, gravity, and friction","Lab 4: The Hitbox Detector","Exit Ticket"],'et'=>"implement collision detection and keyboard control.",'ms'=>null],
12=>['ch'=>"Chapter 10: The Game Developer · Day 7 of 9",'min'=>false,'obj'=>["Manage game state and draw a readable interface."],'std'=>["NV 5.3.4 Enhance interactivity of websites using current scripting trends"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"write the AABB condition for the x axis only.",'tt'=>"Advanced Game Logic & Graphics (45 min)",'tasks'=>["Do Now & Clock In","Start, playing, paused, game over — one state variable","drawImage, sprites, and a HUD with fillText","Exit Ticket"],'et'=>"manage game state and draw a readable interface.",'ms'=>null],
13=>['ch'=>"Chapter 10: The Game Developer · Day 8 of 9",'min'=>false,'obj'=>["Utilize online validation tools for web scripting."],'std'=>["NV 5.3.6 Utilize online validation tools for web scripting"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"your game freezes and the console is empty. Where do you look first?",'tt'=>"Debugging & Validating Your Scripts",'tasks'=>["Do Now & Clock In","Breakpoints, Step Over, and reading the call stack","Linting your JavaScript and fixing what it flags","Lab: The Clean Script Audit","Exit Ticket"],'et'=>"utilize online validation tools for web scripting.",'ms'=>null],
14=>['ch'=>"Chapter 10: The Game Developer · Day 9 of 9",'min'=>false,'obj'=>["Participate in a competitive event and demonstrate technical skill."],'std'=>["NV 1.2.4 Discuss the importance of participation in local, regional, state, and national conferences, events, and competitions","NV 1.2.5 Participate in local, regional, state, or national conferences, events, or competitions","NV 1.4.5 Demonstrate technical skills in various student organization activities/events"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"list every way a player could break your game in the first thirty seconds.",'tt'=>"Game Assembly & QA — Milestone Due",'tasks'=>["Do Now & Clock In","Playtest QA: a partner plays cold and logs every bug","CTSO competition brief: what SkillsUSA and FBLA judge","Milestone: Project 3 — Game Assembly & QA [100 pts]","Exit Ticket"],'et'=>"participate in a competitive event and demonstrate technical skill.",'ms'=>['title'=>"Project 3 — Game Assembly & QA",'pts'=>100]],
15=>['ch'=>"Chapter 11: The \"Cloud\" · Day 1 of 7",'min'=>false,'obj'=>["Recognize the relationship between local and remote site structures."],'std'=>["NV 4.2.4 Recognize the relationship between local and remote site structures"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"two developers edit the same file at the same time. What has to happen for both changes to survive?",'tt'=>"The Team Problem & CLI Navigation (45 min)",'tasks'=>["Do Now & Clock In","Junior Dev Dan overwrote three days of work. Why?","pwd, ls, cd, mkdir, touch — follow the leader","Lab 1: Agency File Architecture Setup","Exit Ticket"],'et'=>"recognize the relationship between local and remote site structures.",'ms'=>null],
16=>['ch'=>"Chapter 11: The \"Cloud\" · Day 2 of 7",'min'=>true,'obj'=>["Explain the role of version control when developing with a team."],'std'=>["NV 5.6.3 Explain the role of version control when developing with a team"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"what is one thing the command line can do that clicking folders cannot?",'tt'=>"Git vs. GitHub & Local Version Control",'tasks'=>["Do Now & Clock In","Git is the tool; GitHub is the website. Clarify it once.","Modified, staged, committed — and writing a real message","Lab 2: Local Agency Backup","Exit Ticket"],'et'=>"explain the role of version control when developing with a team.",'ms'=>null],
17=>['ch'=>"Chapter 11: The \"Cloud\" · Day 3 of 7",'min'=>false,'obj'=>["Explain version control in a collaborative team workflow."],'std'=>["NV 5.6.3 Explain the role of version control when developing with a team"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"you and a teammate both edit line 40 of the same file. What does Git do?",'tt'=>"Remotes, Branching & Pull Requests",'tasks'=>["Do Now & Clock In","origin, push, pull, clone","Branching, merging, and resolving a real conflict live","Lab 3: Syncing with the Agency Hub","Exit Ticket"],'et'=>"explain version control in a collaborative team workflow.",'ms'=>null],
18=>['ch'=>"Chapter 11: The \"Cloud\" · Day 4 of 7",'min'=>false,'obj'=>["Develop a data backup procedures plan."],'std'=>["NV 4.2.5 Develop a data backup procedures plan"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"why branch instead of editing main directly?",'tt'=>"Backups & The Recovery Plan",'tasks'=>["Do Now & Clock In","What actually gets lost when a laptop dies","Writing a backup procedure a client could follow","Lab: The Backup Plan","Exit Ticket"],'et'=>"develop a data backup procedures plan.",'ms'=>null],
19=>['ch'=>"Chapter 11: The \"Cloud\" · Day 5 of 7",'min'=>true,'obj'=>["Define cloud computing.","Compare various cloud computing platforms."],'std'=>["NV 5.6.1 Define cloud computing","NV 5.6.2 Compare various cloud computing platforms (e.g., Microsoft Azure, Amazon AWS, Google Cloud)"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"a client asks \"what is the cloud?\" You have 60 seconds. What do you say?",'tt'=>"What Is \"The Cloud\"?",'tasks'=>["Do Now & Clock In","IaaS, PaaS, SaaS with the pizza analogy","Azure, AWS, and Google Cloud compared honestly","Exit Ticket"],'et'=>"define cloud computing.",'ms'=>null],
20=>['ch'=>"Chapter 11: The \"Cloud\" · Day 6 of 7",'min'=>false,'obj'=>["Identify server operating systems and describe how servers work in a hosting environment."],'std'=>["NV 6.1.1 Identify the various server operating systems used to host web pages","NV 6.1.2 Describe how servers work in a hosting environment","NV 6.1.4 Explain common web server maintenance routines"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"define elasticity in one sentence a client would understand.",'tt'=>"How Hosting Actually Works",'tasks'=>["Do Now & Clock In","Linux vs. Windows servers and why it matters to your paths","Uptime, patching, and routine server maintenance","Exit Ticket"],'et'=>"identify server operating systems and describe how servers work in a hosting environment.",'ms'=>null],
21=>['ch'=>"Chapter 11: The \"Cloud\" · Day 7 of 7",'min'=>false,'obj'=>["Describe the technical requirements involved in choosing a web host."],'std'=>["NV 6.1.5 Describe the technical requirements involved in choosing a web host"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"two hosting plans, same price. Name three things that could make one much worse.",'tt'=>"Choosing a Host — Milestone Due",'tasks'=>["Do Now & Clock In","Bandwidth, storage, SSL, backups, and support windows","Lab 4: Client Infrastructure Proposal","Milestone: Project 4 — The Agency Codebase Sync [100 pts]","Exit Ticket"],'et'=>"describe the technical requirements involved in choosing a web host.",'ms'=>['title'=>"Project 4 — The Agency Codebase Sync",'pts'=>100]],
22=>['ch'=>"Chapter 12: The \"Manager\" · Day 1 of 9",'min'=>false,'obj'=>["Identify content management systems."],'std'=>["NV 5.5.1 Identify content management systems (CMS) (e.g., WordPress, Joomla)"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"a news site publishes 100 articles a day. Is someone hand-coding each page?",'tt'=>"Agency Scaling & Meet Manager Mike",'tasks'=>["Do Now & Clock In","The math on hand-coding 200 pages vs. generating them","WordPress, Joomla, and who actually uses what","Exit Ticket"],'et'=>"identify content management systems.",'ms'=>null],
23=>['ch'=>"Chapter 12: The \"Manager\" · Day 2 of 9",'min'=>false,'obj'=>["Evaluate current trends in CMS and recommend a platform."],'std'=>["NV 5.5.2 Evaluate current trends in CMS (e.g., blogging, online magazine, corporate websites) and learning management system (LMS [e.g., Canvas])"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"name one situation where a static site beats a CMS.",'tt'=>"Static vs. Dynamic & The Platform Matrix",'tasks'=>["Do Now & Clock In","Database + theme, assembled per request","Pitching WordPress vs. Shopify vs. Wix to a real client","Lab 1: The Platform Pitch Matrix","Exit Ticket"],'et'=>"evaluate current trends in CMS and recommend a platform.",'ms'=>null],
24=>['ch'=>"Chapter 12: The \"Manager\" · Day 3 of 9",'min'=>true,'obj'=>["Evaluate CMS structures for blogging, magazine, and corporate sites."],'std'=>["NV 5.5.2 Evaluate current trends in CMS (e.g., blogging, online magazine, corporate websites) and learning management system (LMS [e.g., Canvas])"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"what is the difference between a Page and a Post, and why does Mike care?",'tt'=>"Information Architecture & The Dashboard",'tasks'=>["Do Now & Clock In","Pages, Posts, Media, Categories, Tags, Menus, Users","The five areas a client touches and the twenty they should not","Lab 2: Information Architecture Lab","Exit Ticket"],'et'=>"evaluate CMS structures for blogging, magazine, and corporate sites.",'ms'=>null],
25=>['ch'=>"Chapter 12: The \"Manager\" · Day 4 of 9",'min'=>false,'obj'=>["Build client-editable content using the block editor."],'std'=>["NV 5.5.2 Evaluate current trends in CMS (e.g., blogging, online magazine, corporate websites) and learning management system (LMS [e.g., Canvas])"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"should a coffee shop menu be a Page or a Post? Defend it.",'tt'=>"Writing Content: The Block Editor (45 min)",'tasks'=>["Do Now & Clock In","Blocks, patterns, and reusable blocks","Exit Ticket"],'et'=>"build client-editable content using the block editor.",'ms'=>null],
26=>['ch'=>"Chapter 12: The \"Manager\" · Day 5 of 9",'min'=>false,'obj'=>["Explore WYSIWYG and theme-based development tools."],'std'=>["NV 5.5.3 Explore WYSIWYG software (e.g., Dreamweaver) for web development"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"you customize a theme, then it updates. What happens to your work?",'tt'=>"Themes & Child Themes",'tasks'=>["Do Now & Clock In","Updating a theme live and watching edits vanish","Child themes: what they inherit and what they override","Lab 3: The Design Skin","Exit Ticket"],'et'=>"explore WYSIWYG and theme-based development tools.",'ms'=>null],
27=>['ch'=>"Chapter 12: The \"Manager\" · Day 6 of 9",'min'=>false,'obj'=>["Vet and secure CMS extensions responsibly."],'std'=>["NV 5.5.1 Identify content management systems (CMS) (e.g., WordPress, Joomla)"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"why must customizations live in a child theme?",'tt'=>"Plugins, Security & SEO",'tasks'=>["Do Now & Clock In","Last updated, install count, compatibility: the vetting checklist","Least privilege, updates, backups, and spam protection","Lab 4: Forms & SEO Security","Exit Ticket"],'et'=>"vet and secure CMS extensions responsibly.",'ms'=>null],
28=>['ch'=>"Chapter 12: The \"Manager\" · Day 7 of 9",'min'=>false,'obj'=>["Demonstrate how to integrate a shopping cart into a web page."],'std'=>["NV 2.5.2 Demonstrate how to integrate a shopping cart into a web page"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"your client wants to sell online. Name one thing that is now your legal problem.",'tt'=>"Adding a Shopping Cart",'tasks'=>["Do Now & Clock In","Installing and configuring a cart on the CMS","Products, variants, shipping, and tax basics","Lab: The Storefront Build","Exit Ticket"],'et'=>"demonstrate how to integrate a shopping cart into a web page.",'ms'=>null],
29=>['ch'=>"Chapter 12: The \"Manager\" · Day 8 of 9",'min'=>false,'obj'=>["Deliver a complete, secured client site."],'std'=>["NV 5.5.1 Identify content management systems (CMS) (e.g., WordPress, Joomla)"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"name three things you check before installing any plugin on a client site.",'tt'=>"Client Site Assembly & QA (45 min)",'tasks'=>["Do Now & Clock In","Full assembly pass and Lighthouse audit inside the theme","Exit Ticket"],'et'=>"deliver a complete, secured client site.",'ms'=>null],
30=>['ch'=>"Chapter 12: The \"Manager\" · Day 9 of 9",'min'=>false,'obj'=>["Produce documentation a non-technical client can follow."],'std'=>["NV 5.5.2 Evaluate current trends in CMS (e.g., blogging, online magazine, corporate websites) and learning management system (LMS [e.g., Canvas])"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"could Mike add a blog post using only what you wrote? Be honest.",'tt'=>"Client Hand-Off — Milestone Due",'tasks'=>["Do Now & Clock In","Writing the one-page hand-off document","Peer hand-off test: your partner publishes without asking you","Milestone: Client Site Assembly & QA [100 pts]","Exit Ticket"],'et'=>"produce documentation a non-technical client can follow.",'ms'=>['title'=>"Client Site Assembly & QA",'pts'=>100]],
31=>['ch'=>"Chapter 13: The \"Network\" · Day 1 of 9",'min'=>false,'obj'=>["Analyze current programming languages and platforms used in web app development."],'std'=>["NV 7.1.1 Analyze current programming languages and/or platforms used in web app development"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"Anna wants live NASA data on her homepage forever. Who updates it?",'tt'=>"Agency Integration & Meet Astro Anna",'tasks'=>["Do Now & Clock In","The landscape: what people actually build web apps with","Where JavaScript fits and what it cannot do alone","Exit Ticket"],'et'=>"analyze current programming languages and platforms used in web app development.",'ms'=>null],
32=>['ch'=>"Chapter 13: The \"Network\" · Day 2 of 9",'min'=>false,'obj'=>["Explain the purpose of an API in app development."],'std'=>["NV 7.1.2 Explain the purpose of Application Programming Interface (API) in app development"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"name two platforms used to build web apps and one difference between them.",'tt'=>"What Is an API? The Waiter Analogy",'tasks'=>["Do Now & Clock In","The Human API activity: client, server, and a note on paper","You do not walk into the kitchen","Exit Ticket"],'et'=>"explain the purpose of an API in app development.",'ms'=>null],
33=>['ch'=>"Chapter 13: The \"Network\" · Day 3 of 9",'min'=>true,'obj'=>["Explain how applications create, read, update, and delete remote data."],'std'=>["NV 7.1.2 Explain the purpose of Application Programming Interface (API) in app development"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"name the four things any app does with data. Guess before we list them.",'tt'=>"CRUD Over HTTP (45 min)",'tasks'=>["Do Now & Clock In","GET, POST, PUT/PATCH, DELETE and what each one means","Exit Ticket"],'et'=>"explain how applications create, read, update, and delete remote data.",'ms'=>null],
34=>['ch'=>"Chapter 13: The \"Network\" · Day 4 of 9",'min'=>false,'obj'=>["Read and author the data format APIs exchange."],'std'=>["NV 7.1.2 Explain the purpose of Application Programming Interface (API) in app development"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"which HTTP method reads data, and which one creates it?",'tt'=>"JSON: The Language of the Web",'tasks'=>["Do Now & Clock In","Double quotes, braces, brackets, no trailing commas","Reading real API documentation before writing any code","Lab 1: The JSON Blueprint Lab","Exit Ticket"],'et'=>"read and author the data format APIs exchange.",'ms'=>null],
35=>['ch'=>"Chapter 13: The \"Network\" · Day 5 of 9",'min'=>false,'obj'=>["Develop an app that retrieves live remote data."],'std'=>["NV 7.1.3 Develop an app using a modern programming language and/or platform"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"your code asks a server 3,000 miles away for data. What does the rest of your program do?",'tt'=>"The Network Connection: Asynchronous Fetch",'tasks'=>["Do Now & Clock In","Three console.logs where the middle one is a fetch","Promises, .then(), and async/await","Lab 2: The Fetch Connection","Exit Ticket"],'et'=>"develop an app that retrieves live remote data.",'ms'=>null],
36=>['ch'=>"Chapter 13: The \"Network\" · Day 6 of 9",'min'=>true,'obj'=>["Develop an app that renders remote data dynamically."],'std'=>["NV 7.1.3 Develop an app using a modern programming language and/or platform"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"why does await make async code easier to read than chained .then() calls?",'tt'=>"Rendering Live Data to the Page",'tasks'=>["Do Now & Clock In","Looping the response and building elements","Clearing before re-rendering, and why that matters","Lab 3: Dynamic Search Lab","Exit Ticket"],'et'=>"develop an app that renders remote data dynamically.",'ms'=>null],
37=>['ch'=>"Chapter 13: The \"Network\" · Day 7 of 9",'min'=>false,'obj'=>["Handle API credentials and rate limits responsibly."],'std'=>["NV 7.1.3 Develop an app using a modern programming language and/or platform"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"how does one endpoint return different results for different users?",'tt'=>"Query Parameters & Key Security (45 min)",'tasks'=>["Do Now & Clock In","Template literals, API keys, rate limits, and CORS","Exit Ticket"],'et'=>"handle API credentials and rate limits responsibly.",'ms'=>null],
38=>['ch'=>"Chapter 13: The \"Network\" · Day 8 of 9",'min'=>false,'obj'=>["Develop an app that handles failure without lying to the user."],'std'=>["NV 7.1.3 Develop an app using a modern programming language and/or platform"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"why must an API key never appear in a public repository?",'tt'=>"Robustness: Status Codes & The Four UI States",'tasks'=>["Do Now & Clock In","200, 401, 404, 429, 500 — and checking response.ok","Loading, empty, error, success: all four, announced","Lab 4: UX States Lab","Exit Ticket"],'et'=>"develop an app that handles failure without lying to the user.",'ms'=>null],
39=>['ch'=>"Chapter 13: The \"Network\" · Day 9 of 9",'min'=>true,'obj'=>["Develop an app using a modern programming language and platform."],'std'=>["NV 7.1.3 Develop an app using a modern programming language and/or platform"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"name the input you are most afraid a tester will try on your app.",'tt'=>"The Client Real-Time App — Milestone Due",'tasks'=>["Do Now & Clock In","Peer QA: offline, bad query, and empty result","Milestone: Project 4 — The Client Real-Time App [100 pts]","Exit Ticket"],'et'=>"develop an app using a modern programming language and platform.",'ms'=>['title'=>"Project 4 — The Client Real-Time App",'pts'=>100]],
40=>['ch'=>"Chapter 14: The \"Brain\" · Day 1 of 9",'min'=>false,'obj'=>["Describe the purpose of a database as it relates to web development."],'std'=>["NV 5.4.3 Describe the purpose of a database as it relates to web development"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"your Chapter 10 game forgets every score on reload. What is missing?",'tt'=>"The Amnesia Problem & Meet Competitive Cody (45 min)",'tasks'=>["Do Now & Clock In","No memory means no leaderboard, no accounts, no business","Exit Ticket"],'et'=>"describe the purpose of a database as it relates to web development.",'ms'=>null],
41=>['ch'=>"Chapter 14: The \"Brain\" · Day 2 of 9",'min'=>false,'obj'=>["Identify and describe relational databases."],'std'=>["NV 5.4.1 Identify and describe relational databases"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"name one feature Cody would never come back for if the site forgets him.",'tt'=>"Describing the Database",'tasks'=>["Do Now & Clock In","The Human Database activity: rows, fields, and a query engine","Tables, rows, records, fields, and data types","Lab 1: The CRUD App Audit","Exit Ticket"],'et'=>"identify and describe relational databases.",'ms'=>null],
42=>['ch'=>"Chapter 14: The \"Brain\" · Day 3 of 9",'min'=>true,'obj'=>["Analyze various databases used in web development."],'std'=>["NV 5.4.2 Analyze various databases used in web development"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"not every app uses tables. What else could you store data in?",'tt'=>"Analyzing Database Types",'tasks'=>["Do Now & Clock In","Relational vs. NoSQL, and when each is the right call","MySQL, PostgreSQL, SQLite, MongoDB, Firebase","Exit Ticket"],'et'=>"analyze various databases used in web development.",'ms'=>null],
43=>['ch'=>"Chapter 14: The \"Brain\" · Day 4 of 9",'min'=>false,'obj'=>["Design a normalized schema with primary and foreign keys."],'std'=>["NV 5.4.1 Identify and describe relational databases"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"you store a customer address in all 40 of their orders. What breaks when they move?",'tt'=>"Relational Design & Keys",'tasks'=>["Do Now & Clock In","Primary keys, foreign keys, and the three relationship types","Normalization: store every fact exactly once","Lab 2: The Schema Architect Lab","Exit Ticket"],'et'=>"design a normalized schema with primary and foreign keys.",'ms'=>null],
44=>['ch'=>"Chapter 14: The \"Brain\" · Day 5 of 9",'min'=>false,'obj'=>["Query a relational database for precise answers."],'std'=>["NV 5.4.1 Identify and describe relational databases"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"how would you ask for \"every student in grade 11, sorted by last name\"?",'tt'=>"SQL: SELECT, WHERE & ORDER BY (45 min)",'tasks'=>["Do Now & Clock In","SELECT, FROM, WHERE, ORDER BY, LIMIT, LIKE","Exit Ticket"],'et'=>"query a relational database for precise answers.",'ms'=>null],
45=>['ch'=>"Chapter 14: The \"Brain\" · Day 6 of 9",'min'=>false,'obj'=>["Combine related tables and calculate summary values."],'std'=>["NV 5.4.1 Identify and describe relational databases"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"name the difference between a primary key and a foreign key.",'tt'=>"JOINs & Aggregates",'tasks'=>["Do Now & Clock In","INNER JOIN across two tables through their keys","COUNT, SUM, AVG, and GROUP BY","Lab 3: The Data Detective Lab","Exit Ticket"],'et'=>"combine related tables and calculate summary values.",'ms'=>null],
46=>['ch'=>"Chapter 14: The \"Brain\" · Day 7 of 9",'min'=>false,'obj'=>["Write data-modifying statements without destroying a table."],'std'=>["NV 5.4.1 Identify and describe relational databases"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"you run DELETE FROM users with no WHERE clause. What just happened?",'tt'=>"Modifying Data Safely",'tasks'=>["Do Now & Clock In","INSERT, UPDATE, DELETE — always with WHERE","Write the SELECT first, confirm the row count, then commit","Exit Ticket"],'et'=>"write data-modifying statements without destroying a table.",'ms'=>null],
47=>['ch'=>"Chapter 14: The \"Brain\" · Day 8 of 9",'min'=>true,'obj'=>["Secure a database and meet the Agency's legal obligations."],'std'=>["NV 5.4.4 Incorporate a database into a website where possible (e.g., local storage, external database)"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"what is the one clause that must never be forgotten on a DELETE?",'tt'=>"Security, Liability & The Law",'tasks'=>["Do Now & Clock In","SQL injection, live, against a sandbox form","Parameterized queries, hashing, and collecting less","GDPR and CCPA in plain developer terms","Lab 4: Secure Data Entry Lab","Exit Ticket"],'et'=>"secure a database and meet the Agency's legal obligations.",'ms'=>null],
48=>['ch'=>"Chapter 14: The \"Brain\" · Day 9 of 9",'min'=>false,'obj'=>["Incorporate a database into a website where possible."],'std'=>["NV 5.4.4 Incorporate a database into a website where possible (e.g., local storage, external database)"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"name one field you will refuse to collect, and why that is a security decision.",'tt'=>"Connecting a Database to a Site — Milestone Due",'tasks'=>["Do Now & Clock In","localStorage vs. an external database: what each is for","Milestone: Client Database Schema [100 pts]","Exit Ticket"],'et'=>"incorporate a database into a website where possible.",'ms'=>['title'=>"Client Database Schema",'pts'=>100]],
49=>['ch'=>"Chapter 15: The Game Never Ends · Day 1 of 5",'min'=>false,'obj'=>["Define Artificial Intelligence.","Explain the role of AI in web development."],'std'=>["NV 7.2.1 Define Artificial Intelligence","NV 7.2.2 Explain the role of AI in web development"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"if an AI writes 100 lines of code in two seconds, why do developers still have jobs?",'tt'=>"AI & Machine Learning: Copilot, Not Autopilot",'tasks'=>["Do Now & Clock In","Vague prompt vs. precise prompt, side by side on the projector","What an LLM actually does: prediction, not understanding","Lab 1: Prompt Engineering Lab","Exit Ticket"],'et'=>"define Artificial Intelligence.",'ms'=>null],
50=>['ch'=>"Chapter 15: The Game Never Ends · Day 2 of 5",'min'=>false,'obj'=>["Describe how AI changes the user experience."],'std'=>["NV 7.2.3 Describe how AI changes the user experience"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"what was the difference between your first prompt and your best one?",'tt'=>"How AI Changes the User Experience",'tasks'=>["Do Now & Clock In","Search, recommendations, chat, and personalization","When an AI feature helps and when it is just noise","Exit Ticket"],'et'=>"describe how AI changes the user experience.",'ms'=>null],
51=>['ch'=>"Chapter 15: The Game Never Ends · Day 3 of 5",'min'=>false,'obj'=>["Explain the significance of data in the development of AI."],'std'=>["NV 7.2.4 Explain the significance of data in the development of AI"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"an AI hiring tool trains on ten years of a company's hires. What does it learn?",'tt'=>"Data, Bias & The Dark Side (45 min)",'tasks'=>["Do Now & Clock In","Bias enters through data, not malice. A real documented case.","Lab 2: Ethics Case Study","Exit Ticket"],'et'=>"explain the significance of data in the development of AI.",'ms'=>null],
52=>['ch'=>"Chapter 15: The Game Never Ends · Day 4 of 5",'min'=>true,'obj'=>["Explore use of VR and AR in web design.","Research emerging AR/VR applications beyond entertainment."],'std'=>["NV 7.4.1 Explore use of VR and AR in web design","NV 7.4.2 Research emerging applications of VR and AR in non-entertainment venues"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"name two ethical obligations when you use AI in professional work.",'tt'=>"The Immersive Web: AR, VR & Voice",'tasks'=>["Do Now & Clock In","WebXR in the browser; AR overlay vs. VR replacement","Non-entertainment uses: training, medicine, retail, real estate","Lab 3: AR Integration Plan","Exit Ticket"],'et'=>"explore use of VR and AR in web design.",'ms'=>null],
53=>['ch'=>"Chapter 15: The Game Never Ends · Day 5 of 5",'min'=>false,'obj'=>["Research the Internet of Things as it relates to web development.","Explain the impact of digital assistants."],'std'=>["NV 7.3.1 Research Internet of Things (IoT) as it relates to web development","NV 7.3.2 Explain the impact of digital assistants on web development"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"a smart doorbell is a computer on the internet. Name one thing that makes it riskier than your laptop.",'tt'=>"IoT, Digital Assistants — Milestone Due",'tasks'=>["Do Now & Clock In","Device, gateway, cloud, dashboard — and default passwords","Voice assistants and what they change about interface design","Lab 4: IoT Security Audit","Milestone: Project 6 — The Future-Cast Expo [100 pts]","Exit Ticket"],'et'=>"research the Internet of Things as it relates to web development.",'ms'=>['title'=>"Project 6 — The Future-Cast Expo",'pts'=>100]],
54=>['ch'=>"Chapter 16: The Final Boss · Day 1 of 11",'min'=>false,'obj'=>["Identify the purpose of Secure File Transfer Protocol."],'std'=>["NV 6.2.1 Identify the purpose of Secure File Transfer Protocol (SFTP)"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"you email someone a link starting with C:/Users/. Why will it not load?",'tt'=>"Localhost vs. The Live Web & SFTP",'tasks'=>["Do Now & Clock In","Local pane vs. remote pane, side by side","Why plain FTP is unacceptable: credentials in clear text","Exit Ticket"],'et'=>"identify the purpose of Secure File Transfer Protocol.",'ms'=>null],
55=>['ch'=>"Chapter 16: The Final Boss · Day 2 of 11",'min'=>true,'obj'=>["Demonstrate the use of SFTP."],'std'=>["NV 6.2.2 Demonstrate the use of SFTP"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"what does a remote server have that your laptop does not?",'tt'=>"Publishing by Hand",'tasks'=>["Do Now & Clock In","public_html, index.html, and Linux case sensitivity","Lab 1: Manual FTP Upload","Exit Ticket"],'et'=>"demonstrate the use of SFTP.",'ms'=>null],
56=>['ch'=>"Chapter 16: The Final Boss · Day 3 of 11",'min'=>false,'obj'=>["Publish a site through an automated deployment pipeline."],'std'=>["NV 6.2.2 Demonstrate the use of SFTP"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"you fix a typo at 11pm. How many manual steps should stand between you and the live site?",'tt'=>"The New School Way: Git & CI/CD (45 min)",'tasks'=>["Do Now & Clock In","Push a commit, watch it deploy. Deploy previews and rollbacks.","Lab 2: Automated Cloud Launch","Exit Ticket"],'et'=>"publish a site through an automated deployment pipeline.",'ms'=>null],
57=>['ch'=>"Chapter 16: The Final Boss · Day 4 of 11",'min'=>false,'obj'=>["Diagnose failed deployments from build output."],'std'=>["NV 6.2.2 Demonstrate the use of SFTP"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"your site works locally and shows a blank white page live. Name three possible causes.",'tt'=>"Debugging the Build",'tasks'=>["Do Now & Clock In","Reading a build log from the bottom up","Wrong publish directory, case-sensitive paths, missing env vars","Lab: Launch Error Triage","Exit Ticket"],'et'=>"diagnose failed deployments from build output.",'ms'=>null],
58=>['ch'=>"Chapter 16: The Final Boss · Day 5 of 11",'min'=>false,'obj'=>["Describe the process of locating and registering a domain name."],'std'=>["NV 6.2.4 Describe the process of locating and registering a domain name"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"firstname-lastname.com costs about \$12 a year. Is that worth it? Defend your answer.",'tt'=>"Owning Your Identity: Domains",'tasks'=>["Do Now & Clock In","Registrars, renewals, WHOIS privacy, and squatting","Exit Ticket"],'et'=>"describe the process of locating and registering a domain name.",'ms'=>null],
59=>['ch'=>"Chapter 16: The Final Boss · Day 6 of 11",'min'=>false,'obj'=>["Explain domain name servers."],'std'=>["NV 6.2.5 Explain domain name servers (DNS)"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"what actually has to change on the internet for a domain to point at your site?",'tt'=>"DNS & Going Secure (45 min)",'tasks'=>["Do Now & Clock In","A records, CNAMEs, propagation, and forcing HTTPS","Exit Ticket"],'et'=>"explain domain name servers.",'ms'=>null],
60=>['ch'=>"Chapter 16: The Final Boss · Day 7 of 11",'min'=>false,'obj'=>["Preview and test web pages for compatibility using various browsers and output devices."],'std'=>["NV 6.2.3 Preview and test web pages for compatibility using various browsers and output devices"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"which browser is going to surprise you today?",'tt'=>"Cross-Browser & Cross-Device Testing",'tasks'=>["Do Now & Clock In","Three browsers, two real devices, one defect log","Reproducible defect reports: device, width, steps, expected, actual","Lab 3: The QA Audit","Exit Ticket"],'et'=>"preview and test web pages for compatibility using various browsers and output devices.",'ms'=>null],
61=>['ch'=>"Chapter 16: The Final Boss · Day 8 of 11",'min'=>false,'obj'=>["Audit a live site and improve it measurably."],'std'=>["NV 6.3.5 Analyze web analytics for purposes of improving traffic, user experience, and meeting targeted goals"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"what broke on a device you do not own?",'tt'=>"Performance, SEO & The Lighthouse Pass",'tasks'=>["Do Now & Clock In","All four Lighthouse categories and Core Web Vitals","sitemap.xml, robots.txt, and honest technical SEO","Lab 4: Lighthouse Polish","Exit Ticket"],'et'=>"audit a live site and improve it measurably.",'ms'=>null],
62=>['ch'=>"Chapter 16: The Final Boss · Day 9 of 11",'min'=>true,'obj'=>["Evaluate content with the client for relevancy and viability.","Monitor validity of hyperlinks."],'std'=>["NV 6.3.1 Evaluate content with client for relevancy","NV 6.3.2 Evaluate content for viability","NV 6.3.3 Monitor validity of hyperlinks"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"you launch and never touch it again. Name three things that rot within a year.",'tt'=>"Keeping a Site Alive: Content & Links",'tasks'=>["Do Now & Clock In","The content review meeting: what to cut, keep, and rewrite","Broken link monitoring and what a 404 costs you","Exit Ticket"],'et'=>"evaluate content with the client for relevancy and viability.",'ms'=>null],
63=>['ch'=>"Chapter 16: The Final Boss · Day 10 of 11",'min'=>false,'obj'=>["Maintain website documentation.","Analyze web analytics to improve traffic and user experience."],'std'=>["NV 6.3.4 Maintain and update all website documentation (e.g., prototype, site map, navigation)","NV 6.3.5 Analyze web analytics for purposes of improving traffic, user experience, and meeting targeted goals"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"name one thing on a site that rots if nobody maintains it.",'tt'=>"Documentation & Analytics (45 min)",'tasks'=>["Do Now & Clock In","Keeping the prototype, sitemap, and navigation docs current","Sessions, bounce rate, and what the numbers actually tell you","Exit Ticket"],'et'=>"maintain website documentation.",'ms'=>null],
64=>['ch'=>"Chapter 16: The Final Boss · Day 11 of 11",'min'=>false,'obj'=>["Demonstrate college and career readiness.","Investigate industry-standard credentials available in this cluster."],'std'=>["NV 1.4.1 Demonstrate college and career readiness (e.g., applications, resumes, interview skills, presentation skills)","NV 1.4.3 Investigate industry-standard credentials/certifications available within this Career Cluster"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"an employer opens your portfolio tonight. What is the first thing they see?",'tt'=>"Career Readiness & The Launch — Milestone Due",'tasks'=>["Do Now & Clock In","Resumes, applications, and interview basics","Industry certifications available to you and how to sit for them","Milestone: Project 6 — The Live Portfolio Launch [100 pts]","Exit Ticket"],'et'=>"demonstrate college and career readiness.",'ms'=>['title'=>"Project 6 — The Live Portfolio Launch",'pts'=>100]],
65=>['ch'=>"EOP Review & Exam · Day 1 of 7",'min'=>true,'obj'=>["Convert assessment data into a targeted study plan."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Predict','dn'=>"which domain will you score lowest on — front-end, JavaScript, data, or deployment?",'tt'=>"EOP Diagnostic & Your Personal Gap Map (45 min)",'tasks'=>["Do Now & Clock In","40-question diagnostic across both years","Building your gap map from the item analysis","Exit Ticket"],'et'=>"convert assessment data into a targeted study plan.",'ms'=>null],
66=>['ch'=>"EOP Review & Exam · Day 2 of 7",'min'=>false,'obj'=>["Close the front-end gaps your own data identified."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Reflect','dn'=>"was your prediction right? What surprised you about your results?",'tt'=>"Review Sprint 1: Front-End Foundations",'tasks'=>["Do Now & Clock In","Rapid review: semantics, box model, specificity, Flexbox, Grid, WCAG","Station rotation by gap","Exit Ticket"],'et'=>"close the front-end gaps your own data identified.",'ms'=>null],
67=>['ch'=>"EOP Review & Exam · Day 3 of 7",'min'=>false,'obj'=>["Close the scripting, data, and deployment gaps from your map."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Predict','dn'=>"name the one topic you are least confident about going into the exam.",'tt'=>"Review Sprint 2: Logic, Data & Systems",'tasks'=>["Do Now & Clock In","Code tracing, fetch and JSON, SQL, Git, and the deploy pipeline","Station rotation by gap","Exit Ticket"],'et'=>"close the scripting, data, and deployment gaps from your map.",'ms'=>null],
68=>['ch'=>"EOP Review & Exam · Day 4 of 7",'min'=>true,'obj'=>["Walk into the exam knowing exactly what you know."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Reflect','dn'=>"what moved from red to green on your gap map this week?",'tt'=>"Final Review (45 min)",'tasks'=>["Do Now & Clock In","Last pass on the two lowest class-wide standards","Testing logistics and what to bring","Exit Ticket"],'et'=>"walk into the exam knowing exactly what you know.",'ms'=>null],
69=>['ch'=>"EOP Review & Exam · Day 5 of 7",'min'=>false,'obj'=>["Demonstrate mastery across the full two-year program."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'','dn'=>"Two minutes with your gap map. Then everything goes away.",'tt'=>"End-of-Program Exam",'tasks'=>["Clock In","End-of-Program Comprehensive Exam","Exit Ticket"],'et'=>"demonstrate mastery across the full two-year program.",'ms'=>null],
70=>['ch'=>"EOP Review & Exam · Day 6 of 7",'min'=>false,'obj'=>["Demonstrate mastery across the full two-year program."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'','dn'=>"Testing continues. Anyone finished early begins the studio intake reading.",'tt'=>"End-of-Program Exam (continued)",'tasks'=>["Clock In","End-of-Program Comprehensive Exam","Studio intake reading for those finished","Exit Ticket"],'et'=>"demonstrate mastery across the full two-year program.",'ms'=>null],
71=>['ch'=>"EOP Review & Exam · Day 7 of 7",'min'=>true,'obj'=>["Complete the End-of-Program assessment and transition to the capstone."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Reflect','dn'=>"what is one thing the exam asked that you wish you had reviewed harder?",'tt'=>"Exam Window Closes (45 min)",'tasks'=>["Do Now & Clock In","Make-up testing","Studio kickoff briefing: two projects, both due in June","Exit Ticket"],'et'=>"complete the End-of-Program assessment and transition to the capstone.",'ms'=>null],
72=>['ch'=>"The Agency Studio — Two Projects, Running at Once · Day 1 of 28",'min'=>true,'obj'=>["Plan and defend how you will split your time between two live projects."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Predict','dn'=>"two projects, same deadline. What is the first thing that will go wrong for you personally?",'tt'=>"Sprint 1 · Studio Kickoff: Two Clients, One Calendar (45 min)",'tasks'=>["Do Now & Clock In","The brief: a community app AND a career portfolio, both due June 2","How a real agency runs concurrent work","Exit Ticket"],'et'=>"plan and defend how you will split your time between two live projects.",'ms'=>null],
73=>['ch'=>"The Agency Studio — Two Projects, Running at Once · Day 2 of 28",'min'=>false,'obj'=>["Identify a real community need and a client to serve."],'std'=>["NV 1.3.2 Participate in a service learning (program related) and/or community service project or activity"],'stdNote'=>null,'dnType'=>'Reflect','dn'=>"name one organization in this town whose website you have actually struggled to use.",'tt'=>"Sprint 1 · Finding a Community Worth Building For",'tasks'=>["Do Now & Clock In","Real partner vs. researched need: you choose your client","Scoping a problem an app can genuinely fix","Task: Client secured or need documented","Exit Ticket"],'et'=>"identify a real community need and a client to serve.",'ms'=>null],
74=>['ch'=>"The Agency Studio — Two Projects, Running at Once · Day 3 of 28",'min'=>true,'obj'=>["Inventory everything you have built across two years."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Predict','dn'=>"how many distinct pieces of work have you made since Level 1 started? Write a number.",'tt'=>"Sprint 1 · Two-Year Work Inventory",'tasks'=>["Do Now & Clock In","List everything first, judge second","What survives: evidence, screenshots, repos, live URLs","Task: Portfolio inventory complete","Exit Ticket"],'et'=>"inventory everything you have built across two years.",'ms'=>null],
75=>['ch'=>"The Agency Studio — Two Projects, Running at Once · Day 4 of 28",'min'=>false,'obj'=>["Select the three projects your portfolio will argue with."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Reflect','dn'=>"which piece of your own work had you completely forgotten about?",'tt'=>"Sprint 1 · User Research & Case Study Selection (45 min)",'tasks'=>["Do Now & Clock In","App: interviews and pain points.  Portfolio: pick your three","Exit Ticket"],'et'=>"select the three projects your portfolio will argue with.",'ms'=>null],
76=>['ch'=>"The Agency Studio — Two Projects, Running at Once · Day 5 of 28",'min'=>false,'obj'=>["Build and estimate a backlog for both projects and commit to a split."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Predict','dn'=>"you have 28 blocks total. How many go to the app and how many to the portfolio?",'tt'=>"Sprint 1 · Backlogs, Estimates & The Time Split — Gate",'tasks'=>["Do Now & Clock In","Turning both rubrics into tickets with estimates","Stand-up format for the rest of the semester","GATE: Both backlogs built, time split defended","Exit Ticket"],'et'=>"build and estimate a backlog for both projects and commit to a split.",'ms'=>null],
77=>['ch'=>"The Agency Studio — Two Projects, Running at Once · Day 6 of 28",'min'=>false,'obj'=>["Design the structure and data your app will need."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Reflect','dn'=>"which of your two backlogs did you underestimate? Be honest.",'tt'=>"Sprint 2 · App Wireframes & Data Model",'tasks'=>["Do Now & Clock In","Stand-up","Wireframing the core user flow","What data you store, and what you refuse to store","Exit Ticket"],'et'=>"design the structure and data your app will need.",'ms'=>null],
78=>['ch'=>"The Agency Studio — Two Projects, Running at Once · Day 7 of 28",'min'=>false,'obj'=>["Structure a portfolio so the best work is found first."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Predict','dn'=>"a hiring manager gives your portfolio 30 seconds. What must they see?",'tt'=>"Sprint 2 · Portfolio Information Architecture",'tasks'=>["Do Now & Clock In","Stand-up","Home, work index, three case studies, about, contact, resume","Task: Sitemap and brand direction","Exit Ticket"],'et'=>"structure a portfolio so the best work is found first.",'ms'=>null],
79=>['ch'=>"The Agency Studio — Two Projects, Running at Once · Day 8 of 28",'min'=>true,'obj'=>["Prove your app can actually be built in the time remaining."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Reflect','dn'=>"name the one app feature most likely to blow your schedule.",'tt'=>"Sprint 2 · Technical Plan & Feasibility (45 min)",'tasks'=>["Do Now & Clock In","Stand-up","Cutting scope now instead of failing in May","Exit Ticket"],'et'=>"prove your app can actually be built in the time remaining.",'ms'=>null],
80=>['ch'=>"The Agency Studio — Two Projects, Running at Once · Day 9 of 28",'min'=>false,'obj'=>["Write a case study that reasons from problem to outcome."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Predict','dn'=>"what is the most common thing missing from a student case study?",'tt'=>"Sprint 2 · Writing the First Case Study",'tasks'=>["Do Now & Clock In","Stand-up","Context, problem, constraints, decisions, outcome, limitation","Task: Case study one drafted","Exit Ticket"],'et'=>"write a case study that reasons from problem to outcome.",'ms'=>null],
81=>['ch'=>"The Agency Studio — Two Projects, Running at Once · Day 10 of 28",'min'=>false,'obj'=>["Present a design for critique and revise from it."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Reflect','dn'=>"what part of your design are you least willing to defend? That is the part to fix.",'tt'=>"Sprint 2 · Design Review — Gate",'tasks'=>["Do Now & Clock In","Five-minute design reviews, whole class critiques","GATE: App design reviewed, portfolio structure approved","Exit Ticket"],'et'=>"present a design for critique and revise from it.",'ms'=>null],
82=>['ch'=>"The Agency Studio — Two Projects, Running at Once · Day 11 of 28",'min'=>true,'obj'=>["Build the semantic structure and data layer of the app."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Predict','dn'=>"name the first thing that will break when you start wiring real data.",'tt'=>"Sprint 3 · App Build: Structure & Data",'tasks'=>["Do Now & Clock In","Stand-up","Semantic HTML, validated, before any styling","Exit Ticket"],'et'=>"build the semantic structure and data layer of the app.",'ms'=>null],
83=>['ch'=>"The Agency Studio — Two Projects, Running at Once · Day 12 of 28",'min'=>false,'obj'=>["Get a live portfolio URL before it is finished."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Reflect','dn'=>"your portfolio is not done. Why deploy it today anyway?",'tt'=>"Sprint 3 · Portfolio Build: Deploy Early (45 min)",'tasks'=>["Do Now & Clock In","Stand-up","Repo, pipeline, HTTPS — an empty site that is already live","Exit Ticket"],'et'=>"get a live portfolio URL before it is finished.",'ms'=>null],
84=>['ch'=>"The Agency Studio — Two Projects, Running at Once · Day 13 of 28",'min'=>false,'obj'=>["Build the feature that makes the app worth using."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Predict','dn'=>"which single feature, if it works, makes the whole app worth it?",'tt'=>"Sprint 3 · App Build: Core Interaction",'tasks'=>["Do Now & Clock In","Stand-up","The core loop: input, logic, rendered result","Exit Ticket"],'et'=>"build the feature that makes the app worth using.",'ms'=>null],
85=>['ch'=>"The Agency Studio — Two Projects, Running at Once · Day 14 of 28",'min'=>true,'obj'=>["Publish a complete case study with real evidence."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Reflect','dn'=>"what evidence do you still need to go find or recreate?",'tt'=>"Sprint 3 · Portfolio Build: Case Study One Live",'tasks'=>["Do Now & Clock In","Stand-up","Before/after screenshots, scores, and honest numbers","Exit Ticket"],'et'=>"publish a complete case study with real evidence.",'ms'=>null],
86=>['ch'=>"The Agency Studio — Two Projects, Running at Once · Day 15 of 28",'min'=>false,'obj'=>["Reconcile two half-finished projects against one calendar."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Predict','dn'=>"which project have you been quietly neglecting? Name it.",'tt'=>"Sprint 3 · Integration Day (45 min)",'tasks'=>["Do Now & Clock In","Stand-up","Backlog re-estimate and honest triage","Exit Ticket"],'et'=>"reconcile two half-finished projects against one calendar.",'ms'=>null],
87=>['ch'=>"The Agency Studio — Two Projects, Running at Once · Day 16 of 28",'min'=>false,'obj'=>["Demo working software and a deployed portfolio."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Reflect','dn'=>"what did you cut this sprint, and was it the right call?",'tt'=>"Sprint 3 · Sprint Review — Gate",'tasks'=>["Do Now & Clock In","App demos one complete user flow","GATE: Portfolio deployed and live, even if thin","Retrospective: what changes next sprint","Exit Ticket"],'et'=>"demo working software and a deployed portfolio.",'ms'=>null],
88=>['ch'=>"The Agency Studio — Two Projects, Running at Once · Day 17 of 28",'min'=>true,'obj'=>["Handle failure and make the app usable by everyone."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Predict','dn'=>"your app is offline. What does the user see right now? Is that acceptable?",'tt'=>"Sprint 4 · App: Data, Errors & Accessibility",'tasks'=>["Do Now & Clock In","Stand-up","Loading, empty, error, success — all four, announced","Keyboard-only sweep and contrast pass","Exit Ticket"],'et'=>"handle failure and make the app usable by everyone.",'ms'=>null],
89=>['ch'=>"The Agency Studio — Two Projects, Running at Once · Day 18 of 28",'min'=>false,'obj'=>["Write achievement bullets you can defend in an interview."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Reflect','dn'=>"how many seconds does a recruiter spend on a first resume pass?",'tt'=>"Sprint 4 · The Resume (45 min)",'tasks'=>["Do Now & Clock In","Action verb, what you built, tool, measurable result","Exit Ticket"],'et'=>"write achievement bullets you can defend in an interview.",'ms'=>null],
90=>['ch'=>"The Agency Studio — Two Projects, Running at Once · Day 19 of 28",'min'=>false,'obj'=>["Take real client feedback and act on it without defending."],'std'=>["NV 1.3.2 Participate in a service learning (program related) and/or community service project or activity"],'stdNote'=>null,'dnType'=>'Predict','dn'=>"your client asks for something that will not fit. What do you say?",'tt'=>"Sprint 4 · Client Feedback Round",'tasks'=>["Do Now & Clock In","Stand-up","Presenting to the community partner and logging every note","Scope negotiation: what fits, what does not, what it costs","Exit Ticket"],'et'=>"take real client feedback and act on it without defending.",'ms'=>null],
91=>['ch'=>"The Agency Studio — Two Projects, Running at Once · Day 20 of 28",'min'=>true,'obj'=>["Build the application package that surrounds the portfolio."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Reflect','dn'=>"search your own name. What are the first three results?",'tt'=>"Sprint 4 · Cover Letter & Professional Profiles",'tasks'=>["Do Now & Clock In","Stand-up","A targeted cover letter for a real posting","GitHub and profile cleanup: pinned repos, real READMEs","Exit Ticket"],'et'=>"build the application package that surrounds the portfolio.",'ms'=>null],
92=>['ch'=>"The Agency Studio — Two Projects, Running at Once · Day 21 of 28",'min'=>false,'obj'=>["Finish the evidence that makes the portfolio an argument."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Predict','dn'=>"which of your three case studies is weakest, and why?",'tt'=>"Sprint 4 · Remaining Case Studies (45 min)",'tasks'=>["Do Now & Clock In","Stand-up","Case studies two and three to completion","Exit Ticket"],'et'=>"finish the evidence that makes the portfolio an argument.",'ms'=>null],
93=>['ch'=>"The Agency Studio — Two Projects, Running at Once · Day 22 of 28",'min'=>false,'obj'=>["Review a peer's application package against real criteria."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Reflect','dn'=>"which resume bullet could you not defend if asked a follow-up?",'tt'=>"Sprint 4 · Career Package Peer Review — Gate",'tasks'=>["Do Now & Clock In","Peer review: every claim traced to something live","GATE: App client review done, career package reviewed","Exit Ticket"],'et'=>"review a peer's application package against real criteria.",'ms'=>null],
94=>['ch'=>"The Agency Studio — Two Projects, Running at Once · Day 23 of 28",'min'=>true,'obj'=>["Find and triage defects before a real user does."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Predict','dn'=>"name the input you are most afraid a tester will try.",'tt'=>"Sprint 5 · App QA & Bug Bash",'tasks'=>["Do Now & Clock In","Stand-up","Whole-class bug bash: ten minutes on two peer apps each","Severity triage: blockers first","Exit Ticket"],'et'=>"find and triage defects before a real user does.",'ms'=>null],
95=>['ch'=>"The Agency Studio — Two Projects, Running at Once · Day 24 of 28",'min'=>false,'obj'=>["Rehearse the answers your portfolio will provoke."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Reflect','dn'=>"what did a tester do with your app that you never anticipated?",'tt'=>"Sprint 5 · Portfolio Polish & Interview Prep (45 min)",'tasks'=>["Do Now & Clock In","STAR answers built from your own artifacts","Exit Ticket"],'et'=>"rehearse the answers your portfolio will provoke.",'ms'=>null],
96=>['ch'=>"The Agency Studio — Two Projects, Running at Once · Day 25 of 28",'min'=>false,'obj'=>["Publish the community app to a live, secure URL."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Predict','dn'=>"what will break the moment it is on a real server?",'tt'=>"Sprint 5 · App Deployment",'tasks'=>["Do Now & Clock In","Stand-up","Deploy, verify HTTPS, test on a device you did not build on","Exit Ticket"],'et'=>"publish the community app to a live, secure URL.",'ms'=>null],
97=>['ch'=>"The Agency Studio — Two Projects, Running at Once · Day 26 of 28",'min'=>false,'obj'=>["Answer hard questions about your own work calmly."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Reflect','dn'=>"\"Tell me about a time a project went wrong.\" Why do interviewers ask this?",'tt'=>"Sprint 5 · Mock Interviews",'tasks'=>["Do Now & Clock In","Paired mock interviews, five questions each, written feedback","Two-minute case study walkthrough for a non-technical listener","Exit Ticket"],'et'=>"answer hard questions about your own work calmly.",'ms'=>null],
98=>['ch'=>"The Agency Studio — Two Projects, Running at Once · Day 27 of 28",'min'=>false,'obj'=>["Ship both projects to production."],'std'=>[],'stdNote'=>"Practice & application day — no new performance indicator introduced.",'dnType'=>'Predict','dn'=>"paste both URLs. Do they both actually work right now?",'tt'=>"Sprint 5 · Both Live — Gate (45 min)",'tasks'=>["Do Now & Clock In","GATE: App and portfolio both live on HTTPS, URLs published","Leave-behind printed, defense script drafted","Exit Ticket"],'et'=>"ship both projects to production.",'ms'=>null],
99=>['ch'=>"The Agency Studio — Two Projects, Running at Once · Day 28 of 28",'min'=>false,'obj'=>["Defend both projects and the decisions behind how you spent your time."],'std'=>["NV 1.4.1 Demonstrate college and career readiness (e.g., applications, resumes, interview skills, presentation skills)"],'stdNote'=>null,'dnType'=>'','dn'=>"Write your opening line. Who you are and what you build, in under 25 words.",'tt'=>"Dual Defense & Program Hand-Off",'tasks'=>["Do Now & Clock In","Eight-minute defense covering both projects","Five minutes of panel questions","Submit: live URLs, repos, resume, cover letter, profiles, interview doc","Program exit reflection and your next concrete step, with a date","Exit Ticket"],'et'=>"defend both projects and the decisions behind how you spent your time.",'ms'=>null],
];

$dates = [
1=>'2026-08-19',2=>'2026-08-21',3=>'2026-08-24',4=>'2026-08-26',5=>'2026-08-28',6=>'2026-08-31',7=>'2026-09-02',8=>'2026-09-04',9=>'2026-09-09',10=>'2026-09-11',
11=>'2026-09-14',12=>'2026-09-16',13=>'2026-09-18',14=>'2026-09-23',15=>'2026-09-25',16=>'2026-09-28',17=>'2026-09-30',18=>'2026-10-02',19=>'2026-10-05',20=>'2026-10-07',
21=>'2026-10-09',22=>'2026-10-14',23=>'2026-10-16',24=>'2026-10-19',25=>'2026-10-21',26=>'2026-10-23',27=>'2026-10-26',28=>'2026-10-28',29=>'2026-11-04',30=>'2026-11-06',
31=>'2026-11-09',32=>'2026-11-13',33=>'2026-11-16',34=>'2026-11-18',35=>'2026-11-20',36=>'2026-11-30',37=>'2026-12-02',38=>'2026-12-04',39=>'2026-12-07',40=>'2026-12-09',
41=>'2026-12-11',42=>'2026-12-14',43=>'2026-12-16',44=>'2026-12-18',45=>'2027-01-06',46=>'2027-01-08',47=>'2027-01-11',48=>'2027-01-13',49=>'2027-01-15',50=>'2027-01-20',
51=>'2027-01-22',52=>'2027-01-25',53=>'2027-01-27',54=>'2027-01-29',55=>'2027-02-01',56=>'2027-02-03',57=>'2027-02-05',58=>'2027-02-08',59=>'2027-02-10',60=>'2027-02-17',
61=>'2027-02-19',62=>'2027-02-22',63=>'2027-02-24',64=>'2027-02-26',65=>'2027-03-01',66=>'2027-03-03',67=>'2027-03-05',68=>'2027-03-08',69=>'2027-03-10',70=>'2027-03-12',
71=>'2027-03-15',72=>'2027-03-17',73=>'2027-03-19',74=>'2027-03-22',75=>'2027-03-24',76=>'2027-03-26',77=>'2027-04-07',78=>'2027-04-09',79=>'2027-04-12',80=>'2027-04-14',
81=>'2027-04-16',82=>'2027-04-19',83=>'2027-04-21',84=>'2027-04-23',85=>'2027-04-26',86=>'2027-04-28',87=>'2027-04-30',88=>'2027-05-03',89=>'2027-05-05',90=>'2027-05-07',
91=>'2027-05-10',92=>'2027-05-12',93=>'2027-05-14',94=>'2027-05-17',95=>'2027-05-19',96=>'2027-05-21',97=>'2027-05-24',98=>'2027-05-26',99=>'2027-06-02',
];

$db = getDB();
$db->query("CREATE TABLE IF NOT EXISTS agenda_content (course VARCHAR(20) NOT NULL, block_num INT NOT NULL, content LONGTEXT NOT NULL, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (course, block_num)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$db->query("CREATE TABLE IF NOT EXISTS agenda_schedule (course VARCHAR(20) NOT NULL, track VARCHAR(10) NOT NULL DEFAULT 'main', block_num INT NOT NULL, event_date DATE NOT NULL, PRIMARY KEY (course, track, block_num), KEY idx_lookup (course, track, event_date)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

$stmtC = $db->prepare("INSERT INTO agenda_content (course, block_num, content) VALUES (?,?,?) ON DUPLICATE KEY UPDATE content=VALUES(content)");
foreach ($blocks as $num => $b) {
    $content = ['chapterLabel'=>$b['ch'],'minimumDay'=>$b['min'],'objective'=>$b['obj'],'standards'=>$b['std'],'standardsNote'=>$b['stdNote'],'doNowType'=>$b['dnType'],'doNowPrompt'=>$b['dn'],'tasksTitle'=>$b['tt'],'tasksList'=>$b['tasks'],'exitTicket'=>$b['et'],'milestone'=>$b['ms']];
    $json = json_encode($content);
    $stmtC->bind_param('sis', $course, $num, $json);
    $stmtC->execute();
}
$stmtC->close();

$stmtS = $db->prepare("INSERT INTO agenda_schedule (course, track, block_num, event_date) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE event_date=VALUES(event_date)");
foreach ($dates as $num => $date) {
    $stmtS->bind_param('ssis', $course, $track, $num, $date);
    $stmtS->execute();
}
$stmtS->close();
$db->close();
echo "Seeded $course: " . count($blocks) . " content rows, " . count($dates) . " schedule rows\n";
